### ISSUE TITLE
MDSwiper Crash if only one Item is given

### ISSUE THREAD

**Issue by heinrich26** [kivymd/KivyMD#1003]
### Description of the Bug

If you're attempting to place only one MDSwiperItem in the MDSwiper,
it'll crash! (with a **ZeroDivisionError**).
Interesingly, it doesnt if you're putting two after another with `add_widget()`. (because of the clock, but still interesting)

### Code and Logs
```
Traceback (most recent call last):
   File "C:\Users\Hendrik\Documents\Python\python-music-player\test-app\main.py", line 293, in <module>
     MainApp().run()
   File "C:\Python39\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Python39\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Python39\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Python39\lib\site-packages\kivy\base.py", line 387, in idle
     Clock.tick()
   File "C:\Python39\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Python39\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Python39\lib\site-packages\kivymd\uix\swiper.py", line 281, in <lambda>
     Clock.schedule_once(lambda x: self._root._reset_size())
   File "C:\Python39\lib\site-packages\kivymd\uix\swiper.py", line 473, in _reset_size
     scroll_x=view_x / total_width,
 ZeroDivisionError: division by zero
```

Codewise Self Explainatory, happens when using the Builder and on `add_widget(MDSwiperItem())`

### Versions

* OS: Win 10
* Python: 3.7
* Kivy: pip lastest
* KivyMD: github master

**Comment by Neizvestnyj** [comment]
I suggest closing the issue, since the bug has been fixed for a long time

https://user-images.githubusercontent.com/40869738/160463719-bb2f7068-2496-47ad-83ba-1db668656584.mp4
