### ISSUE TITLE
MagicBehavior causes crash

### ISSUE THREAD

**Issue by aorizondo** [kivymd/KivyMD#1004]
### Description of the Bug

App crashed on render buttons with MagicBehavior, on  previous version 0.104.1 works just fine.

### Code
```
from kivymd.app import MDApp
from kivy.lang import Builder

KV = '''
#:import MagicBehavior kivymd.uix.behaviors.MagicBehavior


<MagicButton@MagicBehavior+MDRectangleFlatButton>


FloatLayout:

    MagicButton:
        text: "WOBBLE EFFECT"
        on_release: self.wobble()
        pos_hint: {"center_x": .5, "center_y": .3}

    MagicButton:
        text: "GROW EFFECT"
        on_release: self.grow()
        pos_hint: {"center_x": .5, "center_y": .4}

    MagicButton:
        text: "SHAKE EFFECT"
        on_release: self.shake()
        pos_hint: {"center_x": .5, "center_y": .5}

    MagicButton:
        text: "TWIST EFFECT"
        on_release: self.twist()
        pos_hint: {"center_x": .5, "center_y": .6}

    MagicButton:
        text: "SHRINK EFFECT"
        on_release: self.shrink()
        pos_hint: {"center_x": .5, "center_y": .7}
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()

```
### Logs

```
[INFO   ] [Logger      ] Record log in .kivy/logs/kivy_21-06-09_42.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "venv/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
[INFO   ] [Python      ] Interpreter at "venv/bin/python"
[INFO   ] [Logger      ] Purge log fired. Analysing...
[INFO   ] [Logger      ] Purge 22 log files
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "venv/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 20.3.4'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 400 (BSW)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event7
[INFO   ] [MTD         ] Read event from </dev/input/event7>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 842, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 842, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 253, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 837, in kivy.graphics.instructions.RenderContext.push_states
   File "kivy/graphics/instructions.pyx", line 831, in kivy.graphics.instructions.RenderContext.push_state
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy/graphics/compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy/graphics/instructions.pyx", line 257, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "example.py", line 48, in <module>
     Example().run()
   File "/venv/lib/python3.9/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "venv/lib/python3.9/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "venv/lib/python3.9/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "venv/lib/python3.9/site-packages/kivy/base.py", line 408, in idle
     window.dispatch('on_draw')
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "venv/lib/python3.9/site-packages/kivy/core/window/__init__.py", line 1395, in on_draw
     self.render_context.draw()
   File "kivy/graphics/instructions.pyx", line 623, in kivy.graphics.instructions.Canvas.draw
   File "kivy/graphics/instructions.pyx", line 626, in kivy.graphics.instructions.Canvas.draw
   File "kivy/graphics/instructions.pyx", line 896, in kivy.graphics.instructions.RenderContext.apply
   File "kivy/graphics/instructions.pyx", line 849, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy/graphics/instructions.pyx", line 841, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list

Process finished with exit code 1

```

### Versions

* OS: Debian Buster 
* Python: 3.9.2
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by sujal-suhaas** [comment]
same issue
