### ISSUE TITLE
Unicode error in setup.py

### ISSUE THREAD

**Issue by gandriyko** [kivymd/KivyMD#102]
When make 

```
buildozer android update
```

buildozer.spec:
```
requirements = python3,kivy,android,git+https://github.com/HeaTTheatR/KivyMD.git
```

```
Traceback (most recent call last):
    File "/home/andrew/diary-build/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/andrew/diary-build/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/andrew/diary-build/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-luizt1is/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-luizt1is/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-luizt1is/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-luizt1is/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 5, in <module>
      ver_file_data = open(VERSION_FILE, "rt").read()
    File "/home/andrew/diary-build/.buildozer/android/platform/build/build/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
```
file ```__init__.py``` has non-Latin characters like in string Andrés Rodríguez
Maybe better to use io.open instead open?

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/issues/53

**Comment by gandriyko** [comment]
but I don't use python 2, it is python 3.6
