### ISSUE TITLE
TypeError when creating MDTextFieldRound outside of .kv file

### ISSUE THREAD

**Issue by oluwajomilojufamadewa** [kivymd/KivyMD#1043]
### Description of the Bug

Whenever I create an MDTextFieldRound outside of the .kv file, it results in TypeError: 'NoneType' object is not iterable.

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.button import MDRoundFlatButton
from kivymd.uix.textfield import MDTextFieldRound
from kivymd.uix.screen import Screen
from kivymd.uix.boxlayout import BoxLayout


class BasePage(Screen):
    def __init__(self, **kwargs):
        super(BasePage, self).__init__(**kwargs)

        chatTxtInput = MDTextFieldRound()
        chatTxtInput.normal_color = "accent"
        chatTxtInput.foreground_color = "accent"

        sendbtn = MDRoundFlatButton(
            text = 'Send',
            pos_hint = {'center_x': 0.92, 'center_y': 0.05}
            )
        
        self.add_widget(sendbtn)
        self.add_widget(chatTxtInput)



class Baseapp(MDApp):
    def build(self):
        self.theme_cls.primary_palette = "Blue"
        self.theme_cls.accent_palette = "Red"
        self.theme_cls.theme_style = "Dark"
        return BasePage()


Baseapp().run()



ERROR
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_21-07-20_27.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe"
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.0.0 - Build 10.18.10.4425'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4000'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 0
[INFO   ] [GL          ] Shading version <b'4.00 - Build 10.18.10.4425'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "c:\Users\User\OneDrive\Documents\Coding\Python_Files\Yoptu_Kivymd\main.py", line 42, in <module>
     Baseapp().run()
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "c:\Users\User\OneDrive\Documents\Coding\Python_Files\Yoptu_Kivymd\main.py", line 39, in build
     return BasePage()
   File "c:\Users\User\OneDrive\Documents\Coding\Python_Files\Yoptu_Kivymd\main.py", line 12, in __init__
     chatTxtInput = MDTextFieldRound()
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivymd\uix\textfield.py", line 1429, in __init__
     super().__init__(**kwargs)
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivymd\theming.py", line 1140, in __init__
     super().__init__(**kwargs)
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\textinput.py", line 528, in __init__
     super(TextInput, self).__init__(**kwargs)
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\behaviors\focus.py", line 367, in __init__
     super(FocusBehavior, self).__init__(**kwargs)
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 596, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 929, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 147:
 ...
     145:    canvas.before:
     146:        Color:
 >>  147:            rgba: self.normal_color if not self.focus else self._color_active
     148:        Ellipse:
     149:            angle_start: 180
 ...
 TypeError: 'NoneType' object is not iterable
   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
```

### Versions

* OS:  Windows 11 pro
* Python:  3.9.6
* Kivy:  2.0.0
* KivyMD:  0.104.2 I used pip install to download it

**Comment by HeaTTheatR** [comment]
@Jomiflexi 
```python
MDTextFieldRound(normal_color=[1, 0, 0, 1])
```
