### ISSUE TITLE
App crash with error: startswith should be str, not PureWindowsPath

### ISSUE THREAD

**Issue by aliasal** [kivymd/KivyMD#1052]
### Description of the Bug

I am new to Kivy/KivyMD and tried a toy project, a Image-Swiper-App, on Windows.
After building the App (simple, not single-file) the App crashed after starting with:
```
[5160] LOADER: Running swiper.py
 Traceback (most recent call last):
   File "swiper.py", line 2, in <module>
     from kivymd.app import MDApp
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\__init__.py", line 33, in <module>
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivy\__init__.py", line 272, in <module>
   File "C:\Users\Arnd\Desktop 3\kivy md\md\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
     assert pkg_path.startswith(SYS_PREFIX)
 TypeError: startswith first arg must be str or a tuple of str, not PureWindowsPath
[5160] Failed to execute script 'swiper' due to unhandled exception!
```

After changing spec-file, build-process, installed modules, etc... for about 2 days I finally got desparate and 
"fixed" this bug(?) by changing line 71 in pyi_rth_pkgutil.py from

assert pkg_path.startswith(SYS_PREFIX)
to
assert pkg_path.startswith(str(SYS_PREFIX))

After this change the App runs fine (as simple App; no luck so far with single-file: it crashes without error-message or anything).

### Code and Logs

```python
#from kivy.lang import Builder
from kivymd.app import MDApp
import os, sys
from kivy.resources import resource_add_path, resource_find

class SwiperApp(MDApp):

	def build(self):
		self.theme_cls.theme_style = "Dark"
		self.theme_cls.primary_palette = "BlueGray"
		return #Builder.load_file('swiper.kv')
	
if __name__ == '__main__':
    if hasattr(sys, '_MEIPASS'):
        resource_add_path(os.path.join(sys._MEIPASS))
    SwiperApp().run()

kv = """
<MySwiper@MDSwiperItem>
    
    #FitImage:
    #    source: "images/1.jpg"
    #    radius: [20,]

MDScreen:
    
    MDToolbar:
        id: toolbar
        title: "Our Swiper App"
        elevation: 10
        pos_hint: {"top": 1}

    MDSwiper:
        size_hint_y: None
        height: root.height - toolbar.height - dp(40)
        y: root.height - self.height - toolbar.height - dp(20)

        MySwiper:
            FitImage:
                source: "images/1.jpg"
                radius: [20,]
   
        MySwiper:
            FitImage:
                source: "images/2.jpg"
                radius: [20,]
        
        MySwiper:
            FitImage:
                source: "images/3.jpg"
                radius: [20,]
        
        MySwiper:
            FitImage:
                source: "images/4.jpg"
                radius: [20,]

        MySwiper:
            FitImage:
                source: "images/5.jpg"
                radius: [20,]
"""
```
During build I changed the spec-file to:
```
from kivy_deps import sdl2, glew

# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['swiper.py'],
             pathex=['C:\\Users\\Arnd\\Desktop 3\\kivy md\\swiper'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
a.datas += [('swiper.kv', '.', 'DATA')]
exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='swiper',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=True,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe, Tree('C:\\Users\\Arnd\\Desktop 3\\kivy md\\swiper\\'),
               a.binaries,
               a.zipfiles,
               a.datas, 
	       *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=True,
               upx_exclude=[],
               name='swiper')

```

### Versions

* OS: Win10, 64bit
* Python: 3.8.3rc1
* pip freeze
altgraph==0.17
certifi==2021.5.30
charset-normalizer==2.0.3
docutils==0.17.1
future==0.18.2
idna==3.2
Kivy==2.0.0
kivy-deps.angle==0.3.0
kivy-deps.glew==0.3.0
kivy-deps.gstreamer==0.3.2
kivy-deps.sdl2==0.3.1
Kivy-examples==2.0.0
Kivy-Garden==0.1.4
kivymd==0.104.2
pefile==2021.5.24
Pillow==8.3.1
Pygments==2.9.0
pyinstaller==4.4
pyinstaller-hooks-contrib==2021.2
pypiwin32==223
pywin32==301
pywin32-ctypes==0.2.0
requests==2.26.0
urllib3==1.26.6

[swiper.zip](https://github.com/kivymd/KivyMD/files/6873765/swiper.zip)

**Comment by HeaTTheatR** [comment]
@aliasal The error has nothing to do with the KivyMD library
