### ISSUE TITLE
Getting PyInstaller typeerror when deployed the simple kivymd app to windows (exe)

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#1053]
### Description of the Bug

Getting PyInstaller typeerror when deployed the simple kivymd app to windows (exe)

Used https://github.com/maltfield/cross-platform-python-gui to generate exe.
This error only occurs on windows not on linux (AppImage)

### Logs

```
 Traceback (most recent call last):
   File "main.py", line 4, in <module>
     from kivymd.app import MDApp
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\__init__.py", line 33, in <module>
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivy\__init__.py", line 272, in <module>
   File "PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
 TypeError: startswith first arg must be str or a tuple of str, not PureWindowsPath
[548] Failed to execute script 'main' due to unhandled exception!
```

### Versions

* OS: Windows 10
* Python: 3.7
* Kivy: 2.0.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
Has nothing to do with the KivyMD library.
