### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by bokonV2** [kivymd/KivyMD#1066]
### Description of the Bug

KivyMD = 1.0.0.dev0, crash if you switch the tab

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.tab import MDTabsBase

KV = '''
MDBoxLayout:
    orientation: "vertical"

    MDTabs:
        id: tabs

<Tab>

'''


class Tab(MDFloatLayout, MDTabsBase):
    pass


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.tabs.add_widget(Tab(tab_label_text=f"Звонки"))
        self.root.ids.tabs.add_widget(Tab(tab_label_text=f"Звонки2"))


Test().run()
```

```
[INFO   ] [Logger      ] Record log in C:\Users\bokon\.kivy\logs\kivy_21-08-10_45.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer_dev" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew_dev" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2_dev" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "D:\python\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\python\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [KivyMD      ] 1.0.0.dev0, git-Unknown, 2021-08-10 (installed at "D:\python\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 27.20.100.8681'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 27.20.100.8681'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[WARNING] Deprecated property "<StringProperty name=text>" of object "<__main__.Tab object at 0x000001B859832978>" has been set, it will be removed in a future version
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "D:\git\BGAEK_time_table\main.py", line 32, in <module>
     Test().run()
   File "D:\python\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "D:\python\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "D:\python\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "D:\python\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "D:\python\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "D:\python\lib\site-packages\kivy\base.py", line 248, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\core\window\__init__.py", line 1412, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\core\window\__init__.py", line 1428, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\scrollview.py", line 673, in on_touch_down
     if self.dispatch('on_scroll_start', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\scrollview.py", line 698, in on_scroll_start
     return self.simulate_touch_down(touch)
   File "D:\python\lib\site-packages\kivy\uix\scrollview.py", line 668, in simulate_touch_down
     ret = super(ScrollView, self).on_touch_down(touch)
   File "D:\python\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\python\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_touch_down
     if super(ButtonBehavior, self).on_touch_down(touch):
   File "D:\python\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 261, in on_touch_down
     if not self.disabled and list(touch.ud.keys())[0] is self:
 IndexError: list index out of range
```

### Versions

* OS: Windows 10 pro
* Python: v3.7.9
* Kivy: v2.0.0
* KivyMD: 1.0.0.dev0

**Comment by HeaTTheatR** [comment]
@bokonV2 Thanks for report We will fix this shortly.
