### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'G:\\virt\\lib\\site-packages\\kivymd\\uix\\label\\label.kv'

### ISSUE THREAD

**Issue by mishave** [kivymd/KivyMD#1070]
### Description of the Bug

Trying to update to kivy running:
pip install https://github.com/kivymd/KivyMD/archive/master.zip

once confirmed updated:
```Successfully built kivymd
Installing collected packages: kivymd
  Attempting uninstall: kivymd
    Found existing installation: kivymd 0.104.2
    Uninstalling kivymd-0.104.2:
      Successfully uninstalled kivymd-0.104.2
Successfully installed kivymd-1.0.0.dev0```

I can no longer run the file getting the following error:
```
``` Traceback (most recent call last):
   File "test.py", line 4, in <module>
     from kivymd.uix.list import MDList
   File "G:\virt\lib\site-packages\kivymd\uix\list\__init__.py", line 1, in <module>
     from .list import (
   File "G:\virt\lib\site-packages\kivymd\uix\list\list.py", line 517, in <module>
     from kivymd.uix.button import MDIconButton
   File "G:\virt\lib\site-packages\kivymd\uix\button\__init__.py", line 1, in <module>
     from .button import (
   File "G:\virt\lib\site-packages\kivymd\uix\button\button.py", line 475, in <module>
     from kivymd.uix.label import MDLabel
   File "G:\virt\lib\site-packages\kivymd\uix\label\__init__.py", line 1, in <module>
     from .label import MDIcon, MDLabel
   File "G:\virt\lib\site-packages\kivymd\uix\label\label.py", line 241, in <module>
     with open(
 FileNotFoundError: [Errno 2] No such file or directory: 'G:\\virt\\lib\\site-packages\\kivymd\\uix\\label\\label.kv'
```

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.list import MDList
from kivymd.uix.label import Label

KV = '''
ScrollView:

    MDList:

        OneLineIconListItem:
            text: 'Settings'

            IconLeftWidget:
                icon: 'cog'
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Versions

* OS: Windows
* Python: 3.8.2
* Kivy: 2.0.0
* KivyMD: 1.0.0

**Comment by HeaTTheatR** [comment]
@mishave You are not using the master branch.

**Comment by HeaTTheatR** [comment]
```python
from kivymd.uix import label

print(dir(label))
```

**Comment by mishave** [comment]
```from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.list import MDList
from kivymd.uix import label
print(dir(label))

KV = '''
ScrollView:

    MDList:

        OneLineIconListItem:
            text: 'Settings'

            IconLeftWidget:
                icon: 'cog'
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

Results in the same error @HeaTTheatR

**Comment by mishave** [comment]
rolling pack to kivy 0.104.2 fixes the problem however kivy1.0.0 it still happens

**Comment by HeaTTheatR** [comment]
@mishave You do not understand at all what is the matter?

**Comment by HLS-DEV** [comment]
I've got the same error and I would like to use kivy1.0.0. Did you get any solution about this error?

**Comment by omeco4christ** [comment]
creating this file G:\\virt\\lib\\site-packages\\kivymd\\uix\\label\\label.kv solved the problem for me

**Comment by ignacio1988** [comment]
Dear all, today I encountered the same error, but I discovered that Python 3.9.0 was the problem. So, I uninstalled it and installed Python 3.11, and now everything works again. Best regards.

**Comment by datashaman** [comment]
Noting for fellow sufferers that the package from _PyPI_ does not include `*.kv` files. So all the examples that show it being installed from `pypi` are misleading, and lead to nothing working.
It must be used from the master branch. Or better, fix the packaging.
