### ISSUE TITLE
Creating MDTabs Fails

### ISSUE THREAD

**Issue by buckeye17** [kivymd/KivyMD#1093]
### Description of the Bug

Following the examples for creating tabs in the [documentation](https://kivymd.readthedocs.io/en/0.104.1/components/tabs/index.html) fails to produce a functional app.

### Code

```
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs
        on_tab_switch: app.on_tab_switch(*args)


<Tab>:

    MDLabel:
        id: label
        text: "Tab 0"
        halign: "center"
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for i in range(20):
            self.root.ids.android_tabs.add_widget(Tab(text=f"Tab {i}"))

    def on_tab_switch(
        self, instance_tabs, instance_tab, instance_tab_label, tab_text
    ):
        '''Called when switching tabs.

        :type instance_tabs: <kivymd.uix.tab.MDTabs object>;
        :param instance_tab: <__main__.Tab object>;
        :param instance_tab_label: <kivymd.uix.tab.MDTabsLabel object>;
        :param tab_text: text or name icon of tab;
        '''

        instance_tab.ids.label.text = tab_text


Example().run()

```

### Logs

```
[INFO   ] [Logger      ] Record log in C:\Users\613186\.kivy\logs\kivy_21-09-29_122.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 01:40:49) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\613186\Anaconda3\envs\android_app\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7263'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics P630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7263'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 2023, in kivy.properties.ColorProperty.convert
   File "kivy\properties.pyx", line 2041, in kivy.properties.ColorProperty.parse_list
 ValueError: Invalid value for color (got [])

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 527, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 2025, in kivy.properties.ColorProperty.convert
 ValueError: MDTabsLabel.color has an invalid format (got [])

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "c:/Users/613186/OneDrive - BOOZ ALLEN HAMILTON/Documents/android_app/test.py", line 54, in <module>
     Example().run()
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\app.py", line 944, in _run_prepare
     self.dispatch('on_start')
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "c:/Users/613186/OneDrive - BOOZ ALLEN HAMILTON/Documents/android_app/test.py", line 38, in on_start
     self.root.ids.android_tabs.add_widget(Tab(text=f"Tab {i}"))
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivymd\uix\tab.py", line 374, in __init__
     self.tab_label = MDTabsLabel(tab=self)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivymd\uix\tab.py", line 328, in __init__
     super().__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\behaviors\togglebutton.py", line 84, in __init__
     super(ToggleButtonBehavior, self).__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\label.py", line 318, in __init__
     super(Label, self).__init__(**kwargs)
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 19:
 ...
      17:        )
      18:    color:
 >>   19:        self.text_color_active if self.state == 'down'         else self.text_color_normal
      20:    on_x: self._trigger_update_tab_indicator()
      21:    on_width: self._trigger_update_tab_indicator()
 ...
 ValueError: MDTabsLabel.color has an invalid format (got [])
   File "C:\Users\613186\Anaconda3\envs\android_app\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 527, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 2025, in kivy.properties.ColorProperty.convert
```

### Versions

* OS: Windows 10
* Python: 3.8.12
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@buckeye17 We do not support old versions of the KivyMD library. Use master branch or version 0.104.2
