### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__imaging)

### ISSUE THREAD

**Issue by mpeguese** [kivymd/KivyMD#1094]
Error: ImportError: dynamic module does not define module export function (PyInit__imaging)

Python : 3.9
MacOS version : Big Sur
XCode Version : 13.0
Cython version : 0.29.24
KivyMD version: 0.104.2

ISSUE/BACKGROUND:
I am fairly new to python and attempting to create my first mobile app using KivyMD for iOS. I am able to get the application onto my iPhone but it crashes with the below error. It also fails on a Simulator as well with the exact same error. I have followed all the steps outlined in kivy-ios ReadMe. For reference I have placed my terminal commands below.

I found this same error in the following post but it wasn't clearly answered as to what causes this error. I also read several StackOverFlow posts and it appears to be a python2 vs python3 related error (Init being updated to PyInit with deprecation of PIL....or I could be wrong. Please correct me as I am still new to all this) but I am using a virtual environment and made sure only python 3 is installed. Can someone please help in advising what is causing this issue and how to go about fixing it?

ERROR:
Error: ImportError: dynamic module does not define module export function (PyInit__imaging)

TERMINAL COMMANDS:
brew install autoconf automake libtool pkg-config
brew link libtool
cd into local app directory ()
git clone https://github.com/kivy/kivy-ios.git
cd kivy-ios/
python3 -m venv venv
. venv/bin/activate
pip install -e .
pip install cython
python3 toolchain.py build kivy python3
python3 toolchain.py create
open projectname.xcodeproj

Xcode Build Logs
2021-09-26 18:52:40.097319-0400 bebo[77985:4400838] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2021-09-26 18:52:40.097557-0400 bebo[77985:4400838] Initializing python
2021-09-26 18:52:40.530238-0400 bebo[77985:4400838] Running main.py: /Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/YourApp/main.pyc
[INFO ] [Kivy ] v2.1.0.dev0
[INFO ] [Kivy ] Installed at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivy/init.py"
[INFO ] [Python ] v3.9.2 (default, Sep 24 2021, 20:14:03)
[Clang 13.0.0 (clang-1300.0.29.3)]
[INFO ] [Python ] Interpreter at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/bebo"
[INFO ] [Factory ] 186 symbols loaded
[INFO ] [Image ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO ] [KivyMD ] 1.0.0.dev0 (installed at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/init.py")
[INFO ] [Text ] Provider: sdl2
[INFO ] [Window ] Provider: sdl2
2021-09-26 18:52:43.620702-0400 bebo[77985:4400838] Writing analzed variants.
[INFO ] [GL ] Using the "OpenGL ES 2" graphics system
[INFO ] [GL ] Backend used
[INFO ] [GL ] OpenGL version <b'OpenGL ES 2.0 APPLE-19.0.17'>
[INFO ] [GL ] OpenGL vendor <b'Apple Inc.'>
[INFO ] [GL ] OpenGL renderer <b'Apple Software Renderer'>
[INFO ] [GL ] OpenGL parsed version: 2, 0
[INFO ] [GL ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO ] [GL ] Texture max size <4096>
[INFO ] [GL ] Texture max units <8>
[INFO ] [Window ] auto add sdl2 input provider
[INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/C/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
Traceback (most recent call last):
File "", line 44, in load_module
File "/Users/MikesMac/ios-test/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
File "", line 711, in _load
File "", line 666, in _load_unlocked
File "", line 565, in module_from_spec
File "", line 1108, in create_module
File "", line 228, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/MikesMac/ios-test/kivy-ios/bebo-ios/YourApp/main.py", line 10, in
File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/init.py", line 8, in
from kivymd.uix.behaviors import SpecificBackgroundColorBehavior
File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/init.py", line 10, in
from .backgroundcolor_behavior import (
File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 25, in
from .elevation import CommonElevationBehavior
File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/elevation.py", line 364, in
from PIL import Image, ImageDraw, ImageFilter
File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/PIL/Image.py", line 114, in
from . import _imaging as core
File "", line 48, in load_module
File "/Users/MikesMac/ios-test/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
ImportError: dynamic module does not define module export function (PyInit__imaging)
2021-09-26 18:52:44.733397-0400 bebo[77985:4400838] Application quit abnormally!
2021-09-26 18:52:44.797039-0400 bebo[77985:4400838] Leaving

<img width="755" alt="screenshot_14" src="https://user-images.githubusercontent.com/91438833/135777796-8da8955a-d05e-4da5-a395-59c77b34b651.png">

I have also posted this on kivy-ios github but I think this is related to KivyMD as I can get a kivy only app installed and working on an iPhone.

**Comment by podraco** [comment]
that seems to be a 3.9 error, try using 3.8.x, maybe buildozer is doing something wrong in 3.9

**Comment by mpeguese** [comment]
I have switched to another programming language due to this roadblock.  We can make this as closed.
