### ISSUE TITLE
Error while adding kivymd to requirements

### ISSUE THREAD

**Issue by quitegreensky** [kivymd/KivyMD#110]
Hello. I get below error while trying adding kivymd to requirements : 

```
requirements = python3,kivy==master,pillow,requests,git+https://github.com/HeaTTheatR/KivyMD.git
```

Error:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
```

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/issues/102

**Comment by quitegreensky** [comment]
Actually i'm using python 3.6

**Comment by HeaTTheatR** [comment]
Full log...

**Comment by quitegreensky** [comment]
```
  Traceback (most recent call last):
    File "/home/python/aa_app/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/python/aa_app/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/python/aa_app/.buildozer/android/platform/build/build/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-h11pij6_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-h11pij6_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-h11pij6_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-h11pij6_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 5, in <module>
      ver_file_data = open(VERSION_FILE, "rt").read()
    File "/home/python/aa_app/.buildozer/android/platform/build/build/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
  Getting requirements to build wheel ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-een94z7p
Removed git+https://github.com/heattheatr/kivymd.git (from -r requirements.txt (line 1)) from build tracker '/tmp/pip-req-tracker-wed3l72p'
Removed build tracker '/tmp/pip-req-tracker-wed3l72p'
```

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/commit/abbc0b4ac40764be3545f8d27d0f1eec7ca73fbc
