### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by rezagholam** [kivymd/KivyMD#112]
I'm using the `MDTextFieldRound` somewhere in my app as an input for user password. When i press the text field i immediately get `ReferenceError: weakly-referenced object no longer exists` error. 
I tried replacing `MDTextFieldRound` with the `TextInput`  and i didn't get that error again. I couldn't figure out the problem. here is the log from logcat:

```
09-27 18:17:41.777  2757  2829 I python  : [INFO   ] [Base        ] Leaving application in progress...
09-27 18:17:41.778  2757  2829 I python  :  Traceback (most recent call last):
09-27 18:17:41.779  2757  2829 I python  :    File "/home/python/.buildozer/android/app/main.py", line 450, in <module>
09-27 18:17:41.780  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/app.py", line 950, in run
09-27 18:17:41.782  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/base.py", line 560, in runTouchApp
09-27 18:17:41.785  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/base.py", line 334, in mainloop
09-27 18:17:41.786  2757  2757 W InputMethodManager: startInputReason = 4
09-27 18:17:41.787  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/base.py", line 378, in idle
09-27 18:17:41.789  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/base.py", line 329, in dispatch_input
09-27 18:17:41.789   642  1966 D HwInputMethodManagerService: ------------startInput--------------
09-27 18:17:41.791  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/base.py", line 235, in post_dispatch_input
09-27 18:17:41.791  2757  2757 I HwSecImmHelper: mSecurityInputMethodService is null
09-27 18:17:41.792 10452 10452 W ResourceType: For resource 0x7f0b001d, entry index(29) is beyond type entryCount(23)
09-27 18:17:41.794  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.796  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/core/window/__init__.py", line 1407, in on_motion
09-27 18:17:41.798  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.800  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/core/window/__init__.py", line 1423, in on_touch_down
09-27 18:17:41.804  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.806  1642  1866 I AppManager: dependence has been existed:642 -> 10452
09-27 18:17:41.807  2757  2829 I python  :    File "/home/sina76n/python/aa_app/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/screenmanager.py", line 1193, in on_touch_down
09-27 18:17:41.808  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.811  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.814  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/relativelayout.py", line 297, in on_touch_down
09-27 18:17:41.815  2757  2829 I python  :    File "/home/sina76n/python/aa_app/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.817  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.819  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.821  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.823  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.824  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.825  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.825   663   663 I GRALLOC :       shrFd=10,fmt=0x1,intFmt=0x200000001,btStrd=4352,size=8486912,pid=663
09-27 18:17:41.825   663   663 I GRALLOC :       yuv=2,w=1080,h=1920,Stride u=0 v=0,offset u=0 v=0
09-27 18:17:41.825   663   663 I GRALLOC :       iova_size=8486912,conUsg=0xb00,proUsg=0xb00,    strd=1088,[afbc]HdrStrd=1088 PyldStrd=69632 Scrmbl=0,ionhnd = 1
09-27 18:17:41.826  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.827   642  1308 D libfingersense_wrapper: Calling fingersense_touch_up()
09-27 18:17:41.827   642  1308 D libfingersense_wrapper: fingersense_touch_up() finished
09-27 18:17:41.828  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/widget.py", line 545, in on_touch_down
09-27 18:17:41.829  2757  2829 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
09-27 18:17:41.831  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/textinput.py", line 1369, in on_touch_down
09-27 18:17:41.834  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/uix/behaviors/focus.py", line 441, in on_touch_down
09-27 18:17:41.836  2757  2829 I python  :    File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
09-27 18:17:41.839  2757  2829 I python  :    File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
09-27 18:17:41.841  2757  2829 I python  :    File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
09-27 18:17:41.842  2757  2829 I python  :    File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
09-27 18:17:41.843  2757  2829 I python  :    File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
09-27 18:17:41.845  2757  2829 I python  :    File "/home/python/.buildozer/android/platform/build/build/python-installs/AA/kivy/lang/builder.py", line 57, in custom_callback
09-27 18:17:41.846  2757  2829 I python  :    File "<string>", line 169, in <module>
09-27 18:17:41.847  2757  2829 I python  :    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
09-27 18:17:41.848  2757  2829 I python  :    File "kivy/weakproxy.pyx", line 28, in kivy.weakproxy.WeakProxy.__ref__
09-27 18:17:41.849  2757  2829 I python  :  ReferenceError: weakly-referenced object no longer exists
09-27 18:17:41.849  2757  2829 I python  : Python for android ended.
```

**Comment by HeaTTheatR** [comment]
Fixed in version 0.101.0
![Снимок экрана 2019-09-27 в 20 19 01](https://user-images.githubusercontent.com/16930280/65788645-35606600-e164-11e9-92c4-73a2a2fa3707.png)
