### ISSUE TITLE
I can't add MDTextFieldRound to MDRelativeLayout

### ISSUE THREAD

**Issue by johnasce** [kivymd/KivyMD#1138]
### Description of the Feature

When i need to add a MDTextFieldRound to MDRelativeLayout a error apears like next

### Code and Logs

```python
class ScreenLogin(MDScreen):
    def __init__(self,name_win:str="", **kwargs):
        super(ScreenLogin, self).__init__(**kwargs)

        self.txt_use = Text(hint_text="Enter your User")
    
        self.relative = MDRelativeLayout()
        self.relative.size_hint_y = None
        self.relative.height = self.txt_use.height
        self.relative.size_hint_x = None
        self.relative.width = "300dp"
        self.relative.pos_hint = {"center_x": .5, "center_y": .5}


        self.relative.add_widget(self.txt_use)
       

        self.add_widget(self.relative)

class Text(MDTextFieldRound):
    def __init__(self,hint_text:str="", **kwargs):

        super(Text, self).__init__(**kwargs)
        self.hint_text = hint_text
        self.normal_color = [1, 0, 0, 1]
        self.color_active = self.theme_cls.primary_light

class MainApp(MDApp):



    def build(self):
        self.theme_cls.theme_style = "Dark"
        return ScreenLogin()


if __name__ == '__main__':
    app = MainApp()
    app.run()
```

from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.button import MDRectangleFlatButton
from kivymd.uix.label import MDLabel
from kivymd.uix.textfield import MDTextFieldRound
from kivymd.uix.textfield import MDTextField
from kivymd.uix.boxlayout import MDBoxLayout
# from kivymd.uix.floatlayout import MDAdaptiveWidget
# from kivymd.uix.relativelayout import MDRelativeLayout
from kivymd.uix.relativelayout import MDRelativeLayout
from kivy.metrics import dp

####################################################################################################
LOG

```python
D:\GIRO_37_6\venv\Scripts\python.exe D:/DevelopmentTeam/kmd/view/TestLogin.py
[INFO   ] [Logger      ] Record log in C:\Users\ASUSZD28\.kivy\logs\kivy_21-12-06_87.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "D:\GIRO_37_6\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\GIRO_37_6\venv\Scripts\python.exe"
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "D:\GIRO_37_6\venv\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 27.20.100.8681'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 530'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 27.20.100.8681'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "D:/DevelopmentTeam/kmd/view/TestLogin.py", line 104, in <module>
     app.run()
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "D:/DevelopmentTeam/kmd/view/TestLogin.py", line 99, in build
     return ScreenLogin()
   File "D:/DevelopmentTeam/kmd/view/TestLogin.py", line 27, in __init__
     self.txt_use = Texto(hint_text="Enter your User")
   File "D:/DevelopmentTeam/kmd/view/TestLogin.py", line 73, in __init__
     super(Texto, self).__init__(**kwargs)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivymd\uix\textfield.py", line 1429, in __init__
     super().__init__(**kwargs)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivymd\theming.py", line 1140, in __init__
     super().__init__(**kwargs)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\uix\textinput.py", line 528, in __init__
     super(TextInput, self).__init__(**kwargs)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\uix\behaviors\focus.py", line 367, in __init__
     super(FocusBehavior, self).__init__(**kwargs)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
     rule_children=rule_children)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\uix\widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\lang\builder.py", line 543, in apply
     rule_children=rule_children)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\lang\builder.py", line 597, in _apply_rule
     rule.canvas_before, rootrule)
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\lang\builder.py", line 931, in _build_canvas
     '{}: {}'.format(e.__class__.__name__, e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 147:
 ...
     145:    canvas.before:
     146:        Color:
 >>  147:            rgba: self.normal_color if not self.focus else self._color_active
     148:        Ellipse:
     149:            angle_start: 180
 ...
 TypeError: 'NoneType' object is not iterable
   File "D:\GIRO_37_6\venv\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
```

### Screenshots

Add images to explain us this feature. Paste urls here.

Remove this section if no images here

### Versions

* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
We do not support the version of the KivyMD library from PyPi.

**Comment by samyben2001** [comment]
I have exactly the same issue than Johnasce. Is there a way to resolve that?

**Comment by HeaTTheatR** [comment]
@samyben2001 We do not support the version of the KivyMD library from PyPi.
