### ISSUE TITLE
pickers problem in my app .exe format

### ISSUE THREAD

**Issue by osama-ammar** [kivymd/KivyMD#1147]
after creating the exe format of my app and running it I got this error :

` Traceback (most recent call last):
   File "main.py", line 21, in <module>
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\__init__.py", line 1, in <module>
     '''
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\colorpicker\__init__.py", line 1, in <module>
     '''
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
   File "kivymd\uix\pickers\colorpicker\colorpicker.py", line 115, in <module>
 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\osama\\AppData\\Local\\Temp\\_MEI24402\\kivymd\\uix\\pickers\\colorpicker\\colorpicker.kv'
[2404] Failed to execute script 'main' due to unhandled exception!`

knowing that the missed file in this error (colorpicker.kv) already exists in my virtual env
and when running my code with the virtual env it works normally without errors
in addition I tried to delete the import line in colorpicker.py and rebuild the app , and the same problem occurs with date picker 

* OS: windows 10
* Python: 3.7
* Kivy: 2.0.0
* KivyMD: 0.104.2dev

**Comment by HeaTTheatR** [comment]
@osama-ammar https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/pickers/colorpicker/colorpicker.py#L5

**Comment by osama-ammar** [comment]
I installed the new version kivymd 1.0.0 and got this error :

```python
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [FitImage    ] Note!
In the near future the `FitImage` widget will be moved to the `kivymd.uix.fitimage` package.
Use import of this widget like this:`from kivymd.uix.fitimage import FitImage`.
You are not authorized to use this software
App still in trial period
[INFO   ] [GL          ] NPOT texture support is available
test1
[WARNING] Deprecated property "<OptionProperty name=theme_text_color>" of object "<kivymd.uix.button.button.MDIconButton object at 0x000001D3C7DF9978>" was accessed, it will be removed in a future version
 Traceback (most recent call last):
   File "main.py", line 608, in <module>
     app.run()
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "main.py", line 595, in build
     return DLP_Retriever()
   File "main.py", line 317, in __init__
     (f"{i + 1}", "....", "....", "....", "....","....") for i in range(30)
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivymd\uix\datatables\datatables.py", line 1448, in __init__
     self.table_data.pagination = self.pagination
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivymd\uix\datatables\datatables.py", line 723, in on_pagination
     self.pagination.ids.button_forward.disabled = False
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 1527, in kivy.properties.AliasProperty.set
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivy\uix\widget.py", line 1430, in set_disabled
     self.dec_disabled()
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivy\uix\widget.py", line 1443, in dec_disabled
     self.property('disabled').dispatch(self)
   File "kivy\properties.pyx", line 1536, in kivy.properties.AliasProperty.dispatch
   File "kivy\properties.pyx", line 1538, in kivy.properties.AliasProperty.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
   File "C:\Users\osama\virtual_env\latest_kivymd\lib\site-packages\kivy\lang\builder.py", line 69, in call_fn
     setattr(element, key, e_value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 571, in kivy.properties.Property.check
 ValueError: None is not allowed for MDIcon.text_color
```

**Comment by HeaTTheatR** [comment]
@osama-ammar Attach a minimal code example reproducing this error.

**Comment by osama-ammar** [comment]
...

**Comment by HeaTTheatR** [comment]
@osama-ammar https://discord.com/channels/566880874789076992/618108815774056488/816265169880875018

**Comment by osama-ammar** [comment]
@HeaTTheatR https://discord.com/channels/894324789865480252/894324789865480254

**Comment by HeaTTheatR** [comment]
@osama-ammar Attach here a minimal code example reproducing this error...

**Comment by osama-ammar** [comment]
[New Text Document.txt](https://github.com/kivymd/KivyMD/files/7747452/New.Text.Document.txt)

**Comment by HeaTTheatR** [comment]
@osama-ammar Attach a MINIMAL (50-100 lines) code example reproducing this error...

**Comment by osama-ammar** [comment]
```python
class DLP_Retriever(BoxLayout):

    def __init__(self, *args, **kwargs):
        super(DLP_Retriever,self).__init__(*args, **kwargs)
        
        print ('test1')
        
        self.data_tables = MDDataTable(size_hint=(1, 1),use_pagination=True,rows_num=15,
                                       

            column_data=[
                ("no.", dp(30)),
                ("Patient Name", dp(30)),
                ("Exam Protocol", dp(30)),
                ("Exam Date", dp(30)),
                ("DLP", dp(30)),
                ("Dose (mSv))", dp(30)),                
            ],
            row_data=[
                (f"{i + 1}", "....", "....", "....", "....","....") for i in range(30)
            ],
        )
                
                
#        self.root.ids.data_scr.ids.data.add_widget(self.data_tables)  
        self.ids.data.add_widget(self.data_tables)                         
        print ('test2')  


```

**Comment by osama-ammar** [comment]
sorry to be annoying and thanks for your patience

**Comment by HeaTTheatR** [comment]
@osama-ammar This code cannot be run and it demonstrates nothing.

**Comment by osama-ammar** [comment]
actually to give you a running code I have to paste all code lines because they all connected to each others ..the complete code file is attached in a previous comment ( New text Document.txt)

**Comment by HeaTTheatR** [comment]
@osama-ammar If you cannot localize the location of the error in the code, you absolutely do not need to attach 100 kilobytes of code for others to do it...

**Comment by osama-ammar** [comment]
the error refers to datatables ,and to this line of my main code:
`
   self.data_tables = MDDataTable(size_hint=(1, 1),use_pagination=True,rows_num=15,
`
