### ISSUE TITLE
Error with python 3.10 - undefined symbol: _PyGen_Send

### ISSUE THREAD

**Issue by c4pointer** [kivymd/KivyMD#1166]
### Description of the Bug
Actually its not my script. I use only for test.
And I have got this error when running on python 3.10:
ImportError: /home/neo-arch/.local/lib/python3.10/site-packages/kivy/_event.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

How it can be fixed without install other python version?
Thank`s in advance. 

### Code 

```python
from kivymd.uix.screen import MDScreen
from kivymd.app import MDApp
from kivy.uix.image import Image
from kivymd.uix.button import MDFillRoundFlatIconButton, MDFillRoundFlatButton
from kivymd.uix.textfield import MDTextField
from kivymd.uix.label import MDLabel
from kivymd.uix.toolbar import MDToolbar
from kivymd.uix.datatables import MDDataTable
from kivy.metrics import dp



class ConverterApp(MDApp):
    def flip(self):
        # a function for the "flip" icon
        # changes the state of the app
        if self.state == 0:
            self.state = 1
            self.toolbar.title = "Banker Calc"
            self.input.text = "enter a decimal number"
        else:
            self.state = 0
            self.toolbar.title = "Banker Calc"
            self.input.text = "enter a binary number"
        # hide labels until needed
        self.converted.text = ""
        self.label.text = ""

    def convert(self, args):
        # a function to fint the decimal/binary equivallent
        if self.state == 0:
            # binary to decimal
            val = str(int(self.input.text,2))
            self.label.text = "in decimal is:"
        else:
            # decimal to binary
            val = bin(int(self.input.text))[2:]
            self.label.text = "in binary is:"
        self.converted.text = val

    def build(self):
        self.state = 0 #initial state
        self.theme_cls.primary_palette = "DeepOrange"
        screen = MDScreen()

        # top toolbar
        self.toolbar = MDToolbar(title="Banker Calc")
        self.toolbar.pos_hint = {"top": 1}
        self.toolbar.right_action_items = [
            ["rotate-3d-variant", lambda x: self.flip()]]
        screen.add_widget(self.toolbar)

        # logo
        screen.add_widget(Image(
            source="logo.png",
            pos_hint = {"center_x": 0.5, "center_y":0.7}
            ))

        #collect user input
        self.input = MDTextField(
            text="",
            halign="center",
            size_hint = (2,2),
            pos_hint = {"center_x": 0.5, "center_y":0.5},
            font_size = 22
        )
        screen.add_widget(self.input)
        
        # #secondary + primary labels
        self.label = MDLabel(
            halign="center",
            pos_hint = {"center_x": 0.5, "center_y":0.35},
            theme_text_color = "Secondary"
        )

        self.converted = MDLabel(
            halign="center",
            pos_hint = {"center_x": 0.5, "center_y":0.3},
            theme_text_color = "Primary",
            font_style = "H5"
        )
        screen.add_widget(self.label)
        screen.add_widget(self.converted)

        # "CONVERT" button
        screen.add_widget(MDFillRoundFlatButton(
            text="CONVERT",
            font_size = 17,
            pos_hint = {"center_x": 0.5, "center_y":0.15},
            # on_press = self.convert
        ))

        self.table = MDDataTable(
                # MDDataTable allows the use of size_hint
                size_hint=(0.99, 0.935),
                use_pagination=True,
                rows_num=20,
                check=True,
                column_data=[
                    ("No.", dp(20)),
                    ("Name of Tank", dp(25)),
                    ("Total Vol", dp(20)),
                    ("Sound Val", dp(20)),
                    ("Volume", dp(20)),
                    ("Density", dp(20)),
                    ("Temp", dp(20)),
                    ("MT", dp(20)),
                    ],
                row_data=[
                        (
                            f"{i+1}",
                            "[color=#53351B]Name of tank[/color]",
                            "[color=#55551B]Total Vol[/color]",
                            "[color=#52251B]Sound Val[/color]",
                            "[color=#52251B]Volume[/color]",
                            "[color=#52251B]Density[/color]",
                            "[color=#52251B]Temp[/color]",
                            "[color=#52251B]m3[/color]",
                        )
                        for i in range(12)


                        ],
               )
        
        screen.add_widget(self.table)

        return screen


if __name__ == '__main__':
    ConverterApp().run()

```
###  Logs
``` bash
[INFO   ] [Logger      ] Record log in /home/neo-arch/.kivy/logs/kivy_22-01-13_15.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/neo-arch/.local/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
[INFO   ] [Python      ] Interpreter at "/bin/python"
[INFO   ] [KivyMD      ] 1.0.0.dev0, git-1cb82f7, 2022-01-13 (installed at "/home/neo-arch/.local/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
 Traceback (most recent call last):
   File "/home/neo-arch/Documents/bunker_calc/myapp_kivymd.py", line 1, in <module>
     from kivymd.uix.screen import MDScreen
   File "/home/neo-arch/.local/lib/python3.10/site-packages/kivymd/__init__.py", line 70, in <module>
     import kivymd.font_definitions  # NOQA
   File "/home/neo-arch/.local/lib/python3.10/site-packages/kivymd/font_definitions.py", line 10, in <module>
     from kivy.core.text import LabelBase
   File "/home/neo-arch/.local/lib/python3.10/site-packages/kivy/core/text/__init__.py", line 85, in <module>
     from kivy.graphics.texture import Texture
   File "/home/neo-arch/.local/lib/python3.10/site-packages/kivy/graphics/__init__.py", line 89, in <module>
     from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
   File "kivy/graphics/instructions.pyx", line 1, in init kivy.graphics.instructions
 ImportError: /home/neo-arch/.local/lib/python3.10/site-packages/kivy/_event.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

### Versions

* OS: Arch Linux
* Python: 3.10.1
* Kivy: 2.0
* KivyMD: 1.0.0.dev0

**Comment by HeaTTheatR** [comment]
@c4pointer This problem is not related to the KivyMD library. Ask in the Kivy repository - https://github.com/kivy/kivy/issues

**Comment by rationalrama** [comment]
Hi, Kivy does not yet support Python 3.10, try using 3.9.
You can check out this article to know all supported releases [https://github.com/kivy/kivy/releases](url)
