### ISSUE TITLE
MDDataTable use_pagination crash

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#1215]
setting use_pagination in MDDatatble causes a crash with error

```python
 Traceback (most recent call last):
   File "C:/Users/Akubue Kenechukwu/AppData/Roaming/JetBrains/PyCharmCE2021.3/scratches/scratch_9.py", line 70, in <module>
     Example().run()
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 387, in idle
     Clock.tick()
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Akubue Kenechukwu\AppData\Local\Programs\Python\Python38\lib\site-packages\kivymd\uix\menu\menu.py", line 950, in ajust_radius
     firt_data_item = self.items[0]
 IndexError: list index out of range
 ```
I guess this is coming from the menu in the datatable 

example code

```python
from kivy.metrics import dp

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.button import MDRaisedButton


class Example(MDApp):
    data_tables = None

    def build(self):
        layout = MDFloatLayout()  # root layout

        # Create a table.
        self.data_tables = MDDataTable(
            pos_hint={"center_y": 0.5, "center_x": 0.5},
            size_hint=(0.9, 0.6),
            use_pagination=True,
            column_data=[
                ("No.", dp(30)),
                ("Column 1", dp(40)),
                ("Column 2", dp(40)),
                ("Column 3", dp(40)),
            ],
            row_data=[("1", "1", "2", "3")],
        )
        # Adding a table and buttons to the toot layout.
        layout.add_widget(self.data_tables)

        return layout


Example().run()
```

KivyMD version: master
python version: 3.8
OS: windows

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/issues/1212

**Comment by kengoon** [comment]
@HeaTTheatR this issue is different from #1212 I think you should take a second look

**Comment by haddiebakrie** [comment]
The issue is from [datatables.py](https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/datatables/datatables.py) > create_pagination_menu() (line 1668)
if the rows_num is set to a number greater than the len(row_data) the menu_items returns an empty list because the for loop is checking the range of an higher number to a lower one.

**Comment by haddiebakrie** [comment]
I was able to clear the error by first checking if the rows_num >= len(row_data) // 2 then adding a single menu_item (0) 
```

        if self.rows_num >= len(self.row_data) // 2:
            menu_items =  [{
                "text": "0",
                "viewclass": "OneLineListItem",
                "height": dp(56),
            }]
        else:
            menu_items = [
                {
                    "text": f"{i}",
                    "viewclass": "OneLineListItem",
                    "height": dp(56),
                    "on_release": lambda x=f"{i}": self.table_data.set_number_displayed_lines(
                        x
                    ),
                }
                for i in range(
                    self.rows_num, len(self.row_data) // 2, self.rows_num
                )
            ]


```
