### ISSUE TITLE
Magic Behavior Bug. (IndexError: pop from empty list)

### ISSUE THREAD

**Issue by gogopro-dev** [kivymd/KivyMD#1251]
### Description of the Bug
Magic Behavior example crashes with Exception IndexError

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
<MagicButton@MagicBehavior+MDRectangleFlatButton>


MDFloatLayout:

    MagicButton:
        text: "WOBBLE EFFECT"
        on_release: self.wobble()
        pos_hint: {"center_x": .5, "center_y": .3}

    MagicButton:
        text: "GROW EFFECT"
        on_release: self.grow()
        pos_hint: {"center_x": .5, "center_y": .4}

    MagicButton:
        text: "SHAKE EFFECT"
        on_release: self.shake()
        pos_hint: {"center_x": .5, "center_y": .5}

    MagicButton:
        text: "TWIST EFFECT"
        on_release: self.twist()
        pos_hint: {"center_x": .5, "center_y": .6}

    MagicButton:
        text: "SHRINK EFFECT"
        on_release: self.shrink()
        pos_hint: {"center_x": .5, "center_y": .7}
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()
```

### Log

```
 Exception ignored in: 'kivy.graphics.instructions.InstructionGroup.build'
 Traceback (most recent call last):
   File "kivy\graphics\compiler.pyx", line 100, in kivy.graphics.compiler.GraphicsCompiler.compile
   File "kivy\graphics\instructions.pyx", line 271, in kivy.graphics.instructions.ContextInstruction.apply
   File "kivy\graphics\instructions.pyx", line 863, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy\graphics\instructions.pyx", line 855, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test.py", line 43, in <module>
     Example().run()
   File "C:\Users\gogopro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\gogopro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\gogopro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\gogopro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\kivy\base.py", line 400, in idle
     window.dispatch('on_draw')
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\gogopro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\kivy\core\window\__init__.py", line 1627, in on_draw
     self.render_context.draw()
   File "kivy\graphics\instructions.pyx", line 637, in kivy.graphics.instructions.Canvas.draw
   File "kivy\graphics\instructions.pyx", line 640, in kivy.graphics.instructions.Canvas.draw
   File "kivy\graphics\instructions.pyx", line 910, in kivy.graphics.instructions.RenderContext.apply
   File "kivy\graphics\instructions.pyx", line 863, in kivy.graphics.instructions.RenderContext.pop_states
   File "kivy\graphics\instructions.pyx", line 855, in kivy.graphics.instructions.RenderContext.pop_state
 IndexError: pop from empty list
```

### Versions

* OS: Windows 10 64 bit
* Python: 3.8.10
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@gogopro-dev This is fixed in the master branch of the KivyMD library
