### ISSUE TITLE
MDDataTable: AttributeError when ticking "select all" and not all rows visible

### ISSUE THREAD

**Issue by Mrtjn** [kivymd/KivyMD#1293]
### Description of bug
The error `AttributeError: 'NoneType' object has no attribute 'index'` is raised when ticking the "select all" box of a MDDataTable and not all rows are visible.

Steps to reproduce:
* Execute exactly the example from the [MDDataTable constructor documentation](https://kivymd.readthedocs.io/en/latest/components/datatables/index.html#kivymd.uix.datatables.datatables.MDDataTable).
* Resize the window such that at least one complete row (full height of it) of the table is not visible any more.
* Tick the "select all" box.
* Error is raised, see stack trace below.

### Stack trace
```
 Traceback (most recent call last):
   File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
     exec(code, run_globals)
   File "C:\Users\...\test_app.py", line 138, in <module>
     Example().run()
   File "C:\Users\...\venv\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\...\venv\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\...\venv\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\...\venv\lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\...\venv\lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\...\venv\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\...\venv\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 296, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\...\venv\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\...\venv\lib\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 117, in <module>
   File "C:\Users\...\venv\lib\site-packages\kivymd\uix\datatables.py", line 828, in select_all
     self.on_mouse_select(cell_row_obj)
   File "C:\Users\...\venv\lib\site-packages\kivymd\uix\datatables.py", line 940, in on_mouse_select
     if self.ids.row_controller.selected_row != instance.index:
 AttributeError: 'NoneType' object has no attribute 'index'

Process finished with exit code 1
```

### Versions
* OS: Windows 11 Pro, 21H2
* Python: 3.10
* Kivy: 2.1.0
* KivyMD: 0.104.2

**Comment by HeaTTheatR** [comment]
@Mrtjn We do not support version `0.104.2`. As far as I know, this bug has been fixed in the `master` version of the `KivyMD` library. Therefore, use this version.
