### ISSUE TITLE
MDExpansionPanel in MDRecycleView error

### ISSUE THREAD

**Issue by Ex3n0n** [kivymd/KivyMD#1321]
### Description of the Bug

Use MDExpansionPanel with an MDRecycleView ended up with a crash.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.recycleview import MDRecycleView
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanelOneLine

class Content(MDBoxLayout):
    pass

class ShoppingScreen(MDRecycleView):
    pass

KV = '''
<Content>
    adaptive_height: True

    TwoLineIconListItem:
        text: "(050)-123-45-67"
        secondary_text: "Mobile"

        IconLeftWidget:
            icon: 'phone'

<ShoppingScreen>:
    viewclass: 'MDExpansionPanel'

    MDRecycleGridLayout:
        default_size_hint: 1, None
        id: box
        cols: 1
        adaptive_height: True

ShoppingScreen:
'''

class testApp(MDApp):
    def build(self):
        self.theme_cls.material_style = "M3"
        return Builder.load_string(KV)

    def on_start(self):
        self.root.data = [{'icon':'**', 'content':Content(), 'panel_cls':MDExpansionPanelOneLine(text="Text " + str(i))} for i in range(20)]

testApp().run()

# Note:
# MDExpansionPanel doesn't work with MDRecycleView !
# => MDRecycleView.__init__ need 'panel_cls' to process.
# => In view.py view.__init__ is called without argument and then setattr is called to set attributes of view
```

```log
[INFO   ] Logger: Record log in [...].kivy\logs\kivy_22-08-26_13.txt
[INFO   ] deps: Successfully imported "kivy_deps.gstreamer" 0.3.3
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] Kivy: v2.1.0
[INFO   ] Kivy: Installed at "[...]\00.venv_kivy\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "[...]\00.venv_kivy\Scripts\python.exe"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] KivyMD: 1.0.2, git-38fe356, 2022-08-11 (installed at "[...]\00.venv_kivy\lib\site-packages\kivymd\__init__.py")
[INFO   ] Factory: 189 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.3.0 - Build 20.19.15.5171'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO   ] GL: OpenGL parsed version: 4, 3
[INFO   ] GL: Shading version <b'4.30 - Build 20.19.15.5171'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "[...]\shoppingScreen.py", line 44, in <module>
[WARNING] stderr:     testApp().run()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\app.py", line 955, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\base.py", line 574, in runTouchApp
[WARNING] stderr:     EventLoop.mainloop()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\base.py", line 339, in mainloop
[WARNING] stderr:     self.idle()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\base.py", line 379, in idle
[WARNING] stderr:     Clock.tick()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\clock.py", line 733, in tick
[WARNING] stderr:     self.post_idle(ts, self.idle())
[WARNING] stderr:   File [...]\00.venv_kivy\lib\site-packages\kivy\clock.py", line 776, in post_idle
[WARNING] stderr:     self._process_events()
[WARNING] stderr:   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\uix\recycleview\__init__.py", line 352, in refresh_views
[WARNING] stderr:     lm.set_visible_views(indices, data, viewport)
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\uix\recyclelayout.py", line 370, in set_visible_views
[WARNING] stderr:     new, remaining, old = self.recycleview.view_adapter.set_visible_views(
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\uix\recycleview\views.py", line 406, in set_visible_views
[WARNING] stderr:     view = get_view(index, data[index],
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\uix\recycleview\views.py", line 262, in get_view
[WARNING] stderr:     view = self.create_view(index, data_item, viewclass)
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivy\uix\recycleview\views.py", line 225, in create_view
[WARNING] stderr:     view = viewclass()
[WARNING] stderr:   File "[...]\00.venv_kivy\lib\site-packages\kivymd\uix\expansionpanel\expansionpanel.py", line 339, in __init__
[WARNING] stderr:     raise ValueError(
[WARNING] stderr: ValueError: KivyMD: `panel_cls` object must be must be one of the objects from the list
[WARNING] stderr: [MDExpansionPanelOneLine, MDExpansionPanelTwoLine, MDExpansionPanelThreeLine]
```

### Versions

* OS: Windows 10
* Python: 3.9.1
* Kivy: 2.1.0
* KivyMD: 1.0.2

**Comment by HeaTTheatR** [comment]
@Ex3n0n You cannot use elements with variable height in RecycleView.

**Comment by HeaTTheatR** [comment]
The height of the elements for RecycleView must be a constant.

**Comment by HeaTTheatR** [comment]
Secondly, please read the RecycleView layout documentation.

**Comment by Ex3n0n** [comment]
@HeaTTheatR Ok thanks but I find this information nowhere sorry.
Checked in :
- https://kivy.org/doc/stable/api-kivy.uix.recycleview.html
- https://kivy.org/doc/stable/api-kivy.uix.recycleview.layout.html

Can you point me where i can find this affirmation please ?

**Comment by HeaTTheatR** [comment]
@Ex3n0n Here is the link - https://kivy.org/doc/stable/api-kivy.uix.recycleview.html

**Comment by Ex3n0n** [comment]
@HeaTTheatR Checked, may be i'm blind but I don't find any reference of "cannot use variable height in recycleview".
Could you explain what you mean by 'variable height' please ?

Anyway, I tested something with kivy from the basic_data.py example, I added this line on item (just for toggling height):
```python
on_touch_down: self.height = dp(50) - (self.height - dp(50)) + dp(50) if self.collide_point(*args[-1].pos) else self.height
```

Here full code:
```python
from random import sample, randint
from string import ascii_lowercase

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout


kv = """
<Row@RecycleKVIDsDataViewBehavior+BoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    on_touch_down: self.height = dp(50) - (self.height - dp(50)) + dp(50) if self.collide_point(*args[-1].pos) else self.height
    Label:
        id: name
    Label:
        text: root.value

<Test>:
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            size: self.size
            pos: self.pos
    rv: rv
    orientation: 'vertical'
    GridLayout:
        cols: 3
        rows: 2
        size_hint_y: None
        height: dp(108)
        padding: dp(8)
        spacing: dp(16)
        Button:
            text: 'Populate list'
            on_press: root.populate()
        Button:
            text: 'Sort list'
            on_press: root.sort()
        Button:
            text: 'Clear list'
            on_press: root.clear()
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'Insert new item'
                on_press: root.insert(new_item_input.text)
            TextInput:
                id: new_item_input
                size_hint_x: 0.6
                hint_text: 'value'
                padding: dp(10), dp(10), 0, 0
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'Update first item'
                on_press: root.update(update_item_input.text)
            TextInput:
                id: update_item_input
                size_hint_x: 0.6
                hint_text: 'new value'
                padding: dp(10), dp(10), 0, 0
        Button:
            text: 'Remove first item'
            on_press: root.remove()

    RecycleView:
        id: rv
        scroll_type: ['bars', 'content']
        scroll_wheel_distance: dp(114)
        bar_width: dp(10)
        viewclass: 'Row'
        RecycleBoxLayout:
            default_size: None, dp(50)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(2)
"""

Builder.load_string(kv)


class Test(BoxLayout):

    def populate(self):
        self.rv.data = [
            {'name.text': ''.join(sample(ascii_lowercase, 6)),
             'value': str(randint(0, 2000))}
            for x in range(50)]

    def sort(self):
        self.rv.data = sorted(self.rv.data, key=lambda x: x['name.text'])

    def clear(self):
        self.rv.data = []

    def insert(self, value):
        self.rv.data.insert(0, {
            'name.text': value or 'default value', 'value': 'unknown'})

    def update(self, value):
        if self.rv.data:
            self.rv.data[0]['name.text'] = value or 'default new value'
            self.rv.refresh_from_data()

    def remove(self):
        if self.rv.data:
            self.rv.data.pop(0)


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()
```

Then result.
Before clicking:
![image](https://user-images.githubusercontent.com/54578969/186949206-e3e40802-e13a-4515-9fdc-0d70692858d2.png)
After clicking on first element:
![image](https://user-images.githubusercontent.com/54578969/186949310-3a5101b9-aa18-47e9-a80c-24104a6ff598.png)

And this seems to work like usual.

**Comment by HeaTTheatR** [comment]
@Ex3n0n You cannot use elements of different heights for a RecycleView list
