### ISSUE TITLE
Issue with Hero 

### ISSUE THREAD

**Issue by Kak0ytachel** [kivymd/KivyMD#1412]
### Description of the Bug

I have tried to add Hero to my app and faced such errors. Here is the minimal executable code based on example from the docs that shows the problem. I was really confused when I found out that if you simply remove line 26 - `    Start: ` - the code works brilliantly, but with that line and using Start MDScreen it doesn't work at all. It seems it's a bug or I (and docs) need some more explanation how do Hero works and what I have done wrong 

### Code 

```python
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.screenmanager import MDScreenManager
from kivymd.uix.screen import MDScreen


class Start(MDScreen):
    pass

class WindowManager(MDScreenManager):
    pass


class ScreenA(MDScreen):
    pass


class ScreenB(MDScreen):
    pass


kv = '''
WindowManager:
    id: screen_manager

    Start: 

    ScreenA:
    ScreenB:

<Start>
    name: 'Start'

    MDRaisedButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        text: 'go to ScreenA'
        on_release:
            app.root.current_hero = ''
            app.root.current = "ScreenA"




<ScreenA>:
    name: "ScreenA"

    MDHeroFrom:
        id: hero_from
        tag: "hero"
        size_hint: None, None
        size: "120dp", "120dp"
        pos_hint: {"top": .98}
        x: 24

        FitImage:
            source: "https://github.com/kivymd/internal/raw/main/logo/kivymd_logo_blue.png"
            size_hint: None, None
            size: hero_from.size

    MDRaisedButton:
        text: "Move Hero To Screen B"
        pos_hint: {"center_x": .5}
        y: "36dp"
        on_release:
            app.root.current_hero = "hero"
            app.root.current = "ScreenB"

<ScreenB>:
    name: "ScreenB"
    hero_to: hero_to

    MDHeroTo:
        id: hero_to
        pos_hint: {"center_x": .5, "center_y": .5}


    MDRaisedButton:
        text: "Move Hero To Screen A"
        pos_hint: {"center_x": .5}
        y: "8dp"
        on_release:
            app.root.current_hero = "hero"
            app.root.current = "ScreenA"

'''


class MyApp(MDApp):

    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.theme_cls.primary_palette = "Indigo"
        self.theme_cls.primary_dark_hue = '900'
        screen = Builder.load_string(kv)
        self.screen_manager = screen
        global sm
        sm = self.screen_manager
        return screen


if __name__ == '__main__':
    app = MyApp()
    app.run()


```

### Logs
```
[INFO   ] [Logger      ] Record log in C:\Users\Admin\.kivy\logs\kivy_22-11-11_13.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [KivyMD      ] 1.0.2, git-38fe356, 2022-08-11 (installed at "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 391.35'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 610/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\bugreport.py", line 103, in <module>
     app.run()
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\uix\button\button.py", line 994, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\uix\button\button.py", line 931, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 404, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 45, in <module>
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivy\uix\screenmanager.py", line 1063, in on_current
     self.transition.start(self)
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\uix\transition\transition.py", line 57, in start
     {"in": self.animated_hero_in, "out": self.animated_hero_out}[
   File "C:\Users\Admin\PycharmProjects\SimpleRoulette\venv\lib\site-packages\kivymd\uix\transition\transition.py", line 85, in animated_hero_out
     self.screen_out.hero_to.remove_widget(self.hero_widget)
 AttributeError: 'NoneType' object has no attribute 'remove_widget'
```

### Versions

* OS:  Win 10
* Python: 3.9
* Kivy: 2.1.0
* KivyMD:  1.0.2

**Comment by HeaTTheatR** [comment]
@Kak0ytachel Please read the basic documentation of the Kivy framework for creating and using classes and rules and also carefully read the documentation on the heroes in KivyMD..

**Comment by HeaTTheatR** [comment]
@Kak0ytachel 
Transitions in the KivyMD library screen manager have two states - `in` and `out`. The hero moves from one screen to another when the transition is in the `in` state. The hero's reverse back to the starting position occurs in the `out` transition state. But when you use the first screen without heroes and go to the screen with the initial position of the hero, the transition state is set to `out`. And when you move the hero to the next screen, the `animated_hero_out` method is called, and the `animated_hero_in` method should be called. Therefore, you can manually control the state of transitions.

### For example:

```python
<ScreenWithHeroFrom>
    [...]

    MDHeroFrom:
        [...]

        FitImage:
            [...]

    MDRaisedButton:
        [...]
        on_release:
            app.root.transition._direction = "in"
            app.root.current_heroes = ["hero"]
            app.root.current = "Screen With Hero To"
```

### Full code:

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen


class ScreenWithoutHero(MDScreen):
    pass


class ScreenWithHeroFrom(MDScreen):
    pass


class ScreenWithHeroTo(MDScreen):
    pass


KV = """
<ScreenWithoutHero>

    MDRaisedButton:
        pos_hint: {"center_x": .5, "center_y": .5}
        text: "Go to screen with hero from"
        on_release: app.root.current = "Screen With Hero From"


<ScreenWithHeroFrom>
    name: "Screen With Hero From"

    MDHeroFrom:
        id: hero_from
        tag: "hero"
        size_hint: None, None
        size: "120dp", "120dp"
        pos_hint: {"top": .98}
        x: 24

        FitImage:
            source: "https://github.com/kivymd/internal/raw/main/logo/kivymd_logo_blue.png"
            size_hint: None, None
            size: hero_from.size

    MDRaisedButton:
        text: "Move hero to next screen"
        pos_hint: {"center_x": .5}
        y: "36dp"
        on_release:
            app.root.transition._direction = "in"
            app.root.current_heroes = ["hero"]
            app.root.current = "Screen With Hero To"

<ScreenWithHeroTo>
    name: "Screen With Hero To"
    heroes_to: [hero_to]

    MDHeroTo:
        id: hero_to
        tag: "hero"
        size_hint: None, None
        size: "220dp", "220dp"
        pos_hint: {"center_x": .5, "center_y": .5}


    MDRaisedButton:
        text: "Move hero to previous screen"
        pos_hint: {"center_x": .5}
        y: "8dp"
        on_release:
            app.root.current_heroes = ["hero"]
            app.root.current = "Screen With Hero From"


MDScreenManager:

    ScreenWithoutHero:

    ScreenWithHeroFrom:

    ScreenWithHeroTo:
"""


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```


https://user-images.githubusercontent.com/16930280/202273973-de12c992-c294-442c-ac20-6088a0de40fc.mov

**Comment by Kak0ytachel** [comment]
Thanks! It really works greatly. It should definitely be added to Hero docs
