### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'

### ISSUE THREAD

**Issue by aleksanderzagora** [kivymd/KivyMD#1447]
ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'

* OS: Windows 10
* Python: 3.11
* Kivy: v2.2.0.dev0
* KivyMD: 1.2.0.dev0

Run example:
```
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
#:import KivyLexer kivy.extras.highlight.KivyLexer
#:import HotReloadViewer kivymd.utils.hot_reload_viewer.HotReloadViewer


BoxLayout:

    CodeInput:
        lexer: KivyLexer()
        style_name: "native"
        on_text: app.update_kv_file(self.text)
        size_hint_x: .7

    HotReloadViewer:
        size_hint_x: .3
        path: app.path_to_kv_file
        errors: True
        errors_text_color: 0, 0, 0, 1
        errors_background_color: app.theme_cls.bg_dark
'''


class Example(MDApp):
    path_to_kv_file = "kv_file.kv"

    def build(self):
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)

    def update_kv_file(self, text):
        with open(self.path_to_kv_file, "w") as kv_file:
            kv_file.write(text)


Example().run()
```

Result:
```
D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Scripts\python.exe D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\main.py 
[INFO   ] [Logger      ] Record log in C:\Users\BuZZZard\.kivy\logs\kivy_23-01-07_44.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.5.1
[INFO   ] [Kivy        ] v2.2.0.dev0, git-e932a4e, 20230107
[INFO   ] [Kivy        ] Installed at "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [KivyMD      ] 1.2.0.dev0, git-Unknown, 2023-01-07 (installed at "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivymd\__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 Compatibility Profile Context 22.20.27.07.221020'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Radeon (TM) RX 470 Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ERROR  ] 
Traceback (most recent call last):
  File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 553, in execute_directives
    mod = importlib.__import__(package)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1285, in __import__
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 556, in execute_directives
    mod = importlib.__import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1285, in __import__
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'
 Traceback (most recent call last):
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 553, in execute_directives
     mod = importlib.__import__(package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1285, in __import__
   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 556, in execute_directives
     mod = importlib.__import__(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1285, in __import__
   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.utils.hot_reload_viewer'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\main.py", line 39, in <module>
     Example().run()
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\main.py", line 32, in build
     return Builder.load_string(KV)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 483, in __init__
     self.parse(content)
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 590, in parse
     self.execute_directives()
   File "D:\YandexDisk\DEV\PycharmProjects\KivyMD-HotReload-20230107\venv\Lib\site-packages\kivy\lang\parser.py", line 565, in execute_directives
     raise ParserException(self, ln,
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 3:
 ...
       1:
       2:#:import KivyLexer kivy.extras.highlight.KivyLexer
 >>    3:#:import HotReloadViewer kivymd.utils.hot_reload_viewer.HotReloadViewer
       4:
       5:
 ...
 Unable to import package 'kivymd.utils.hot_reload_viewer.HotReloadViewer'

Process finished with exit code 1

```

**Comment by HeaTTheatR** [comment]
This module has been removed from the KivyMD library.

**Comment by aleksanderzagora** [comment]
Thank you. Why was it removed? Any plans to return?

**Comment by HeaTTheatR** [comment]
@aleksanderzagora https://kivymd.readthedocs.io/en/latest/api/kivymd/tools/hotreload/app/
