### ISSUE TITLE
MDDropDownItem not displaying items correctly after changing said items

### ISSUE THREAD

**Issue by witcher346** [kivymd/KivyMD#146]
#### Description of the Bug

When you add new items to MDDropDownItem or try changing them in any way at runtime, items displayed prior to change will remain, and those newly added/modified items will be displayed as well

### Code and Logs

```python
from kivy.app import App
from kivymd.theming import ThemeManager
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.properties import ObjectProperty


class StartScreen(Screen):

    ddi = ObjectProperty(None)

    def change_item(self):
        self.ids.ddi.items = ["3", "2", "1"]


class Manager(ScreenManager):
    pass


class Test(App):

    theme_cls = ThemeManager()
    title = 'Test'

    def build(self):
        self.theme_cls.primary_palette = 'Blue'
        self.theme_cls.accent_palette = 'Brown'
        self.theme_cls.theme_style = 'Light'
        kv = Builder.load_string("""
Manager:
    StartScreen:

<StartScreen>
    name: 'start'

    ddi: ddi

    MDDropDownItem:
        id: ddi
        items: ['1', '2', '3']
        pos_hint: {'center_x': .5, 'center_y': .625}


    MDRaisedButton:
        text: 'change'
        on_press: root.change_item()
        pos_hint: {'center_x': .5, 'center_y': .5}


        """)

        return kv


if __name__ == '__main__':
    Test().run()
```

### Versions

* OS: Windows 10 Enterprise 1703
* Python: 3.6.1
* Kivy: 1.11.1
* KivyMD: 0.102.0

**Comment by ArtemSBulgakov** [comment]
@witcher346 Issue already fixed in master. Install master KivyMD (`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`) and reopen issue if the bug remains

**Comment by witcher346** [comment]
@Mountaino Now that I've reinstalled kivymd I get this error: 
```
Traceback (most recent call last):
   File "C:/Users/Kojimba/PycharmProjects/DeepEval_kyvi/testing_methods.py", line 109, in <module>
     Test().run()
   File "C:\Users\Kojimba\PycharmProjects\DeepEval_kyvi\venv\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "C:/Users/Kojimba/PycharmProjects/DeepEval_kyvi/testing_methods.py", line 103, in build
     """)
   File "C:\Users\Kojimba\PycharmProjects\DeepEval_kyvi\venv\lib\site-packages\kivy\lang\builder.py", line 405, in load_string
     rule_children=rule_children)
   File "C:\Users\Kojimba\PycharmProjects\DeepEval_kyvi\venv\lib\site-packages\kivy\lang\builder.py", line 654, in _apply_rule
     child = cls(__no_builder=True)
   File "C:\Users\Kojimba\PycharmProjects\DeepEval_kyvi\venv\lib\site-packages\kivymd\uix\dropdownitem.py", line 151, in __init__
     super().__init__(**kwargs)
   File "C:\Users\Kojimba\PycharmProjects\DeepEval_kyvi\venv\lib\site-packages\kivymd\theming.py", line 373, in __init__
     "KivyMD: App object should be inherited from "
ValueError: KivyMD: App object should be inherited from `kivymd.app.MDApp`. See https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#api-breaking-changes
```
Yes, I already changed the inheritance the error says. 
```
from kivymd.app import MDApp
from kivymd.theming import ThemeManager
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.properties import ObjectProperty, ObservableList


class StartScreen(Screen):

    ddi = ObjectProperty(None)

    def change_item(self):
        self.ddi.items = ["1", "2", "2"]


class Manager(ScreenManager):
    pass


class Test(MDApp):

    theme_cls = ThemeManager()
    title = 'Test'

    def build(self):
        self.theme_cls.primary_palette = 'Blue'
        self.theme_cls.accent_palette = 'Brown'
        self.theme_cls.theme_style = 'Light'
        kv = Builder.load_string("""

BoxLayout:
    orientation: 'vertical'
    ddi: ddi

    MDDropDownItem:
        id: ddi
        items: ['1', '2', '3']
        pos_hint: {'center_x': .5, 'center_y': .625}


    MDRaisedButton:
        text: 'change'
        on_press: root.change_item()
        pos_hint: {'center_x': .5, 'center_y': .5}


        """)

        return kv


if __name__ == '__main__':
    Test().run()
```
Help, please?

**Comment by ArtemSBulgakov** [comment]
@witcher346 Did you read the last line of the error? 
You need to change your code according to [API Breaking Changes](https://github.com/HeaTTheatR/KivyMD/blob/master/README.md#api-breaking-changes)

**Comment by ArtemSBulgakov** [comment]
@witcher346 Sorry, I didn't see your code. Remove `theme_cls = ...` from app class

**Comment by witcher346** [comment]
@Mountaino Thanks sooooo much!
