### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.icon_definitions' after Packaging a app using PyInstaller

### ISSUE THREAD

**Issue by santhoshakashs24** [kivymd/KivyMD#1463]
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2022-11-14 (installed at "C:\Users\a643580\Desktop\Test\chatBot\chatBot\dist\ChatBot\kivymd\__init__.pyc")
 --- Logging error ---
 Traceback (most recent call last):
   File "kivy\lang\parser.py", line 553, in execute_directives
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "kivy\lang\parser.py", line 556, in execute_directives
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "logging\__init__.py", line 1081, in emit
   File "logging\__init__.py", line 925, in format
   File "kivy\logger.py", line 291, in format
   File "copy.py", line 172, in deepcopy
   File "copy.py", line 270, in _reconstruct
   File "copy.py", line 146, in deepcopy
   File "copy.py", line 230, in _deepcopy_dict
   File "copy.py", line 146, in deepcopy
   File "copy.py", line 210, in _deepcopy_tuple
   File "copy.py", line 210, in <listcomp>
   File "copy.py", line 161, in deepcopy
 TypeError: cannot pickle 'traceback' object
 Call stack:
   File "chatBot.py", line 11, in <module>
     from kivymd.uix.label import MDLabel
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
   File "kivymd\uix\label\__init__.py", line 1, in <module>
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
   File "kivymd\uix\label\label.py", line 264, in <module>
   File "kivy\lang\builder.py", line 372, in load_string
   File "kivy\lang\parser.py", line 483, in __init__
   File "kivy\lang\parser.py", line 590, in parse
   File "kivy\lang\parser.py", line 564, in execute_directives
   File "logging\__init__.py", line 1469, in exception
   File "logging\__init__.py", line 1463, in error
   File "logging\__init__.py", line 1577, in _log
   File "logging\__init__.py", line 1587, in handle
   File "logging\__init__.py", line 1649, in callHandlers
   File "logging\__init__.py", line 950, in handle
   File "logging\__init__.py", line 1089, in emit
 Message: ''
 Arguments: ()
 Traceback (most recent call last):
   File "kivy\lang\parser.py", line 553, in execute_directives
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "kivy\lang\parser.py", line 556, in execute_directives
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "chatBot.py", line 11, in <module>
     from kivymd.uix.label import MDLabel
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
   File "kivymd\uix\label\__init__.py", line 1, in <module>
     '''
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
   File "kivymd\uix\label\label.py", line 264, in <module>
   File "kivy\lang\builder.py", line 372, in load_string
   File "kivy\lang\parser.py", line 483, in __init__
   File "kivy\lang\parser.py", line 590, in parse
   File "kivy\lang\parser.py", line 565, in execute_directives
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 1:
 ...
 >>    1:#:import md_icons kivymd.icon_definitions.md_icons
       2:
       3:
 ...
 Unable to import package 'kivymd.icon_definitions.md_icons'
[7740] Failed to execute script 'chatBot' due to unhandled exception!

The App is working fine with usual execution, but after packaging the Application to .exe using the documentation https://kivy.org/doc/stable/guide/packaging-windows.html - "Packaging a simple app". Getting the above error

**Comment by HeaTTheatR** [comment]
```
# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.building.build_main import *
import sys
import os

# os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'

path = os.path.abspath(".")
sys.path.insert(0, os.path.join(path, "libs"))

from kivy_deps import sdl2, glew
from kivymd import hooks_path as kivymd_hooks_path

block_cipher = None

a = Analysis(
    ["launcher.py"],
    pathex=[path],
    binaries=[],
    datas=[
        ("data\\", "data\\"),
        ("data\\images\\", "data\\images\\"),
        ("data\\font\\", "data\\font\\"),
    ],
    hiddenimports=[],
    hookspath=[kivymd_hooks_path],
    runtime_hooks=[],
    excludes=["main"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="kazaqstanallergoproba",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=os.path.join(path, "data", "images", "logo-small.ico"),
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
    # *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + angle.dep_bins)],
    strip=False,
    upx=True,
    upx_exclude=[],
    name="kazaqstanallergoproba"
)
```
