### ISSUE TITLE
MDDataTable error =  AttributeError: 'super' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by bobwatcherx** [kivymd/KivyMD#1464]
i have a problem when i want to use mddatatable in kivymd .  when i use table and get error
```
   File "kivy/properties.pyx", line 961, in kivy.properties.ObservableDict.__getattr__
 KeyError: 'container'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/minx/belajar/kivyApppro/kivydatatable/main.py", line 19, in <module>
     TestApp().run()
   File "/usr/local/lib/python3.10/dist-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/local/lib/python3.10/dist-packages/kivy/app.py", line 924, in _run_prepare
     root = self.build()
   File "/home/minx/belajar/kivyApppro/kivydatatable/main.py", line 15, in build
     return MainScreen()
   File "/usr/local/lib/python3.10/dist-packages/kivymd/uix/behaviors/declarative_behavior.py", line 311, in __init__
     super().__init__(**kwargs)
   File "/usr/local/lib/python3.10/dist-packages/kivy/uix/relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "/usr/local/lib/python3.10/dist-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.10/dist-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.10/dist-packages/kivy/uix/widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "/usr/local/lib/python3.10/dist-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/usr/local/lib/python3.10/dist-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/usr/local/lib/python3.10/dist-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/usr/local/lib/python3.10/dist-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/usr/local/lib/python3.10/dist-packages/kivy/lang/builder.py", line 658, in _apply_rule
     child = cls(__no_builder=True)
   File "/usr/local/lib/python3.10/dist-packages/kivymd/uix/datatables/datatables.py", line 1509, in __init__
     self.ids.container.add_widget(self.header)
   File "kivy/properties.pyx", line 964, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'
```

kode saya
main.py
```
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivymd.uix.datatables import MDDataTable
from kivy.lang import Builder

Builder.load_file("mainscreen.kv")


class MainScreen(MDScreen):
    pass


class TestApp(MDApp):
    def build(self):
        return MainScreen()


if __name__ == "__main__":
    TestApp().run()

```

mainscreen.kv
```
<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDLabel:
            text: "Example DataTable"
            font_style: "H5"
            size_hint_y: None
            height: self.texture_size[1]

        MDSeparator:
            height: "1dp"

        MDScrollView:
            MDDataTable:
                id: table
                use_pagination: True
                check: True
                rows_num: 20
                column_data:
                    [("Name", dp(30)), ("Age", dp(30)), ("Gender", dp(30))]
                row_data:
                    [("Alice", "21", "Female"),
                    ("Alice", "21", "Female")]
                    
                        
                   
```

**Comment by HeaTTheatR** [comment]
Tables are created only in Python code.
