### ISSUE TITLE
kivy fails to load MDTopAppBar in master

### ISSUE THREAD

**Issue by PothpothBR** [kivymd/KivyMD#1465]
### Description of the Bug
After a marathon to create an APK due to problems you may already know (https://github.com/kivymd/KivyMD/issues/1352) I can't run an application using the MDTopAppBar component in the master build, I haven't tested with other components.

In KivyMD 1.1.1 release version the error did not reproduce.

### Code to reproduce
```python
from kivymd.app import MDApp
from kivymd.uix.toolbar import MDTopAppBar

class MyApp(MDApp):
    def build(self): return MDTopAppBar()

if __name__=="__main__": MyApp().run()
```

### Stacktrace
```traceback
[INFO   ] [Logger      ] Record log in /home/bruno/.kivy/logs/kivy_23-02-22_56.txt
[INFO   ] [Kivy        ] v2.2.0.dev0
[INFO   ] [Kivy        ] Installed at "/home/bruno/.local/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
[INFO   ] [Python      ] Interpreter at "/bin/python3.11"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.2.0.dev0, git-Unknown, 2023-02-22 (installed at "/home/bruno/.local/lib/python3.11/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 470.161.03'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 3060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/lang/builder.py", line 925, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.__set__
   File "kivy/graphics/boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter
 TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/bruno/github/feneco/teste.py", line 7, in <module>
     if __name__=="__main__": MyApp().run()
                              ^^^^^^^^^^^^^
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "/home/bruno/github/feneco/teste.py", line 5, in build
     def build(self): return MDTopAppBar()
                             ^^^^^^^^^^^^^
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/toolbar/toolbar.py", line 1348, in __init__
     self.action_button = MDFabBottomAppBarButton()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/button/button.py", line 1535, in __init__
     super().__init__(*args, **kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/button/button.py", line 955, in __init__
     super().__init__(*args, **kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/behaviors/declarative_behavior.py", line 311, in __init__
     super().__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/tooltip/tooltip.py", line 195, in __init__
     super().__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/theming.py", line 1670, in __init__
     super().__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivymd/uix/button/button.py", line 1172, in __init__
     super().__init__(**kwargs)
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/uix/widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/lang/builder.py", line 595, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/lang/builder.py", line 928, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 11:
 ...
       9:            size: self.size
      10:            offset: root.shadow_offset
 >>   11:            spread_radius: -(root.shadow_softness)
      12:            blur_radius: root.elevation * 10
      13:            border_radius:
 ...
 TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>
   File "/home/bruno/.local/lib/python3.11/site-packages/kivy/lang/builder.py", line 925, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.__set__
   File "kivy/graphics/boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter
```

This seems like a minimal description of the problem, and I am not sure if this is the project that should handle it, please, if I should open a card in kivy let me know.

### Versions
* OS: Ubuntu 22.04.01 LTS
* Python: 3.11.0.rc1
* Kivy: 2.2.0.dev0
* KivyMD: 1.2.0.dev0

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/pull/1467

**Comment by PothpothBR** [comment]
> #1467

OK, Thanks!
