### ISSUE TITLE
iOS, imort module kivymd.uix.list * error

### ISSUE THREAD

**Issue by dvjdjvu** [kivymd/KivyMD#1479]
### Description of the Bug

I have found bug that i wrote [here](https://github.com/kivymd/KivyMD/issues/1478).
I use in my project **TwoLineAvatarIconListItem** and I include it:
```python
from kivymd.uix.list import *
```
and this results in an error (see log below).
But if use
```python
from kivymd.uix.list import TwoLineAvatarIconListItem
```
that will be ok.

But the first option works on **Linux** and **Android**, only in **iOS** a problem.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
#from kivymd.uix.list import *
from kivymd.uix.list import TwoLineAvatarIconListItem

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"icon": "git", "text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button, items=menu_items, width_mult=4
        )

    def build(self):
        return self.screen


Test().run()
```
Log:
```bash
2023-03-31 17:05:52.381433+0300 test[2376:1357542] [DYMTLInitPlatform] platform initialization successful
2023-03-31 17:05:52.619214+0300 test[2376:1357402] [framework] CUIThemeStore: No theme registered with id=0
2023-03-31 17:05:52.699211+0300 test[2376:1357402] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2023-03-31 17:05:52.699783+0300 test[2376:1357402] Initializing python
2023-03-31 17:05:53.105867+0300 test[2376:1357402] Running main.py: /var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/YourApp/main.pyc
[INFO   ] [Logger      ] Record log in /private/var/mobile/Containers/Data/Application/14A05C9D-14D5-463A-AAC3-63999617E256/Documents/.kivy/logs/kivy_23-03-31_6.txt
[INFO   ] [Kivy        ] v2.2.0.dev0
[INFO   ] [Kivy        ] Installed at "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.9 (main, Mar 29 2023, 14:05:41) 
[Clang 14.0.0 (clang-1400.0.29.202)]
[INFO   ] [Python      ] Interpreter at "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/test"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-03-29 (installed at "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_imageio, img_tex, img_sdl2 (img_dds, img_ffpyplayer, img_pil ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 Apple A7 GPU - 133.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple A7 GPU'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
 Traceback (most recent call last):
   File "<frozen importlib._bootstrap>", line 919, in _find_spec
 AttributeError: 'CustomBuiltinImporter' object has no attribute 'find_spec'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/jessyjames/workspace/kivymd-ios/ios-build/test-ios/YourApp/main.py", line 32, in <module>
   File "/Users/jessyjames/workspace/kivymd-ios/ios-build/test-ios/YourApp/main.py", line 24, in __init__
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivymd/uix/menu/menu.py", line 809, in __init__
     super().__init__(**kwargs)
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivymd/theming.py", line 1668, in __init__
     super().__init__(**kwargs)
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs
File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/uix/widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/lang/builder.py", line 620, in _apply_rule
     cls = Factory_get(cname)
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/factory.py", line 169, in __getattr__
     rootwidgets.append(Factory.get(basecls))
   File "/var/containers/Bundle/Application/E2CB3C98-E629-4F5E-B593-0931D17D2BBE/test.app/lib/python3.9/site-packages/kivy/factory.py", line 155, in __getattr__
     module = importlib.__import__(
   File "<frozen importlib._bootstrap>", line 1109, in __import__
   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 921, in _find_spec
   File "<frozen importlib._bootstrap>", line 895, in _find_spec_legacy
   File "<string>", line 33, in find_module
 TypeError: 'module' object is not callable
2023-03-31 17:05:56.508162+0300 test[2376:1357402] Application quit abnormally!
2023-03-31 17:05:56.646305+0300 test[2376:1357402] Leaving
```

### Versions

* OS: iOS 12.5.7
* Python: 3.9.9
* Kivy: 2.2.0.dev0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
Deprecated. The version of the `KivyMD` library that you are using is not supported. Use version `2.0.0`
