### ISSUE TITLE
Documentation error: NavigationDrawer declarative python style

### ISSUE THREAD

**Issue by acgc99** [kivymd/KivyMD#1491]
### Description of the Bug

I found an error in the [documentation for NavigationDrawer](https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/) regarding the declarative python style in the ["A simple example](https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/#a-simple-example)" code:

### Code and Logs

```from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.navigationdrawer import MDNavigationLayout, MDNavigationDrawer
from kivymd.uix.screen import MDScreen
from kivymd.uix.screenmanager import MDScreenManager
from kivymd.uix.toolbar import MDTopAppBar


class ContentNavigationDrawer(MDBoxLayout):
    pass


class Example(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        return(
            MDScreen(
                MDNavigationLayout(
                    MDScreenManager(
                        MDScreen(
                            MDTopAppBar(
                                title="Navigation Drawer",
                                elevation=4,
                                pos_hint={"top": 1},
                                md_bg_color="#e7e4c0",
                                specific_text_color="#4a4939",
                                left_action_items=[
                                    ['menu', lambda x: self.nav_drawer_open()]
                                ],
                            )

                        )
                    ),
                    MDNavigationDrawer(
                        ContentNavigationDrawer(),
                        id="nav_drawer",
                        radius=(0, 16, 16, 0),
                    ),
                ),
            ),
        )

    def nav_drawer_open(self, *args):
        nav_drawer = self.root.children[0].ids.nav_drawer
        nav_drawer.set_state("open")


Example().run()
```
I get the error:

```[CRITICAL] App.root must be an _instance_ of Widget
 Traceback (most recent call last):
   File "C:\Users\acgc9\Desktop\test.py", line 48, in <module>
     Example().run()
   File "C:\Users\acgc9\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "C:\Users\acgc9\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\app.py", line 931, in _run_prepare
     raise Exception('Invalid instance in App.root')
 Exception: Invalid instance in App.root

```

The problem is in the `build` function, it is returning a `tuple` with one element. I suggest to remove the extra parenthesis and the comma:

```        return\ # use this to avoid an indentation error
            MDScreen(
                MDNavigationLayout(
                    MDScreenManager(
                        MDScreen(
                            MDTopAppBar(
                                title="Navigation Drawer",
                                elevation=4,
                                pos_hint={"top": 1},
                                md_bg_color="#e7e4c0",
                                specific_text_color="#4a4939",
                                left_action_items=[
                                    ['menu', lambda x: self.nav_drawer_open()]
                                ],
                            )

                        )
                    ),
                    MDNavigationDrawer(
                        ContentNavigationDrawer(),
                        id="nav_drawer",
                        radius=(0, 16, 16, 0),
                    ),
                ),
            )
```

I may also suggest to review the rest of the documentation.

### Versions

* OS: Windows 11
* Python:  3.11.2
* Kivy: 2.2.0.dev0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
I don't see any errors in the master version of the documentation
