### ISSUE TITLE
MDDropDownItem throws error when using declarative approach and text element

### ISSUE THREAD

**Issue by NightFurySL2001** [kivymd/KivyMD#1501]
When running the code below, the program throws an error and close the application.

Both the pip latest 1.1.1 and master branch 1.2.0.dev0 shows the same behaviour.

Deleting the line `text="hi",` will make the code work in both 1.1.1 and 1.2.0.dev0.

```py
from kivymd.app import MDApp
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.dropdownitem import MDDropDownItem

class Example(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        return MDFloatLayout(
            MDDropDownItem(
                text="hi",
                on_release=lambda _: self.init_menu()
            )
        )
    
    def init_menu(self):
        print("hi")


Example().run()
```

Error:
```
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 961, in kivy.properties.ObservableDict.__getattr__
 KeyError: 'label_item'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "D:\Desktop\coding\cjk-character-count-kivy\min.py", line 23, in <module>
     Example().run()
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\app.py", line 925, in _run_prepare
     root = self.build()
   File "D:\Desktop\coding\cjk-character-count-kivy\min.py", line 13, in build
     MDDropDownItem(
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivymd\uix\behaviors\declarative_behavior.py", line 311, in __init__
     super().__init__(**kwargs)
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivymd\theming.py", line 1670, in __init__
     super().__init__(**kwargs)
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\uix\boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivy\uix\widget.py", line 357, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 262, in kivy._event.EventDispatcher.__init__
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "D:\Desktop\coding\cjk-character-count-kivy\kivy_venv\lib\site-packages\kivymd\uix\dropdownitem\dropdownitem.py", line 107, in on_text
     self.ids.label_item.text = text_item
   File "kivy\properties.pyx", line 964, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by mateusamorim96** [comment]
My guess is that by not using kv language, which kinda of instanciate the widgets first, prevents the text property to be used. Not sure why, but if you try to use current_item does not raise an exception.

Anyway, you can get it working by doing this:
```
def build(self):
        self.theme_cls.theme_style = "Dark"
        self.theme_cls.primary_palette = "Orange"
        self.dropdown = MDFloatLayout(
            MDDropDownItem(
                id="dropdown_test",
                on_release=lambda _: self.init_menu()
            )
        )
        
        self.dropdown.ids.dropdown_test.set_item("hi")
        
        return self.dropdown```

**Comment by HeaTTheatR** [comment]
The issue is deprecated due to the new API of the KivyMD library 2.0.0 version
