### ISSUE TITLE
Box shadow error

### ISSUE THREAD

**Issue by Ahd999** [kivymd/KivyMD#1503]
Software Versions

Python:3.10

OS:win11

Kivy: Kivy-2.2.0rc1

Kivy installation method: precompiled,prerelease wheels

Describe the bug
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 925, in _build_canvas
setattr(instr, key, value)
File "kivy\graphics\boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.set
File "kivy\graphics\boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter
TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\app\appdirectory\base app\main.py", line 241, in
App().run()
File "D:\py310\lib\site-packages\kivy\app.py", line 955, in run
self._run_prepare()
File "D:\py310\lib\site-packages\kivy\app.py", line 925, in _run_prepare
root = self.build()
File "D:\app\appdirectory\base app\main.py", line 233, in build
return Builder.load_file("main.kv")
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 305, in load_file
return self.load_string(data, **kwargs)
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 407, in load_string
self._apply_rule(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
self._apply_rule(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 660, in _apply_rule
child.apply_class_lang_rules(
File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
Builder.apply(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
self._apply_rule(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
self._apply_rule(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 658, in _apply_rule
child = cls(__no_builder=True)
File "D:\py310\lib\site-packages\kivymd\uix\toolbar\toolbar.py", line 1348, in init
self.action_button = MDFabBottomAppBarButton()
File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 1535, in init
super().init(*args, **kwargs)
File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 955, in init
super().init(*args, **kwargs)
File "D:\py310\lib\site-packages\kivymd\uix\behaviors\declarative_behavior.py", line 311, in init
super().init(**kwargs)
File "D:\py310\lib\site-packages\kivymd\uix\tooltip\tooltip.py", line 195, in init
super().init(**kwargs)
File "D:\py310\lib\site-packages\kivymd\theming.py", line 1670, in init
super().init(**kwargs)
File "D:\py310\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in init
super(ButtonBehavior, self).init(**kwargs)
File "D:\py310\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in init
super(AnchorLayout, self).init(**kwargs)
File "D:\py310\lib\site-packages\kivy\uix\layout.py", line 76, in init
super(Layout, self).init(**kwargs)
File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 1172, in init
super().init(**kwargs)
File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 366, in init
self.apply_class_lang_rules(
File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
Builder.apply(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
self._apply_rule(
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 595, in _apply_rule
self._build_canvas(widget.canvas.before, widget,
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 928, in _build_canvas
raise BuilderException(
kivy.lang.builder.BuilderException: Parser: File "", line 11:
...
9: size: self.size
10: offset: root.shadow_offset
11: spread_radius: -(root.shadow_softness)
12: blur_radius: root.elevation * 10
13: border_radius:
...
TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 925, in _build_canvas
setattr(instr, key, value)
File "kivy\graphics\boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.set
File "kivy\graphics\boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter

* OS: win 11
* Python: 3.10
* Kivy: 2.2.0.rc1
* KivyMD: latest master.zip

**Comment by kmester** [comment]
I have a very similar error like yours, using the Kivy: 2.2.0.rc1 and KivyMD latest master:

2023-05-18 20:31:26.479 11892-11929 python                 ***                I  [INFO   ] [GL          ] NPOT texture support is available
2023-05-18 20:31:26.575 11892-11929 python                  ***                I   Traceback (most recent call last):
2023-05-18 20:31:26.578 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 925, in _build_canvas
2023-05-18 20:31:26.582 11892-11929 python                  ***                I     File "kivy/graphics/boxshadow.pyx", line 406, in kivy.graphics.boxshadow.BoxShadow.border_radius.__set__
2023-05-18 20:31:26.587 11892-11929 python                  ***                I     File "kivy/graphics/boxshadow.pyx", line 316, in kivy.graphics.boxshadow.BoxShadow._check_iter
2023-05-18 20:31:26.593 11892-11929 python                  ***                I   ValueError: 'border_radius' must have 4, got 0
2023-05-18 20:31:26.596 11892-11929 python                  ***                I   
2023-05-18 20:31:26.601 11892-11929 python                  ***                I   During handling of the above exception, another exception occurred:
2023-05-18 20:31:26.604 11892-11929 python                  ***                I   
2023-05-18 20:31:26.611 11892-11929 python                  ***                I   Traceback (most recent call last):
2023-05-18 20:31:26.616 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/app/main.py", line 18685, in <module>
2023-05-18 20:31:26.620 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/app.py", line 955, in run
2023-05-18 20:31:26.630 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/app.py", line 925, in _run_prepare
2023-05-18 20:31:26.635 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/app/main.py", line 18673, in build
2023-05-18 20:31:26.642 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 305, in load_file
2023-05-18 20:31:26.647 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 407, in load_string
2023-05-18 20:31:26.651 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 660, in _apply_rule
2023-05-18 20:31:26.654 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/uix/widget.py", line 470, in apply_class_lang_rules
2023-05-18 20:31:26.663 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 540, in apply
2023-05-18 20:31:26.668 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 662, in _apply_rule
2023-05-18 20:31:26.676 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 660, in _apply_rule
2023-05-18 20:31:26.680 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/uix/widget.py", line 470, in apply_class_lang_rules
2023-05-18 20:31:26.685 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 540, in apply
2023-05-18 20:31:26.693 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 595, in _apply_rule
2023-05-18 20:31:26.698 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 928, in _build_canvas
2023-05-18 20:31:26.703 11892-11929 python                  ***                I   kivy.lang.builder.BuilderException: Parser: File "<inline>", line 25:
2023-05-18 20:31:26.709 11892-11929 python                  ***                I   ...
2023-05-18 20:31:26.713 11892-11929 python                  ***                I        23:            blur_radius: root.elevation * 10
2023-05-18 20:31:26.719 11892-11929 python                  ***                I        24:            border_radius:
2023-05-18 20:31:26.729 11892-11929 python                  ***                I   >>   25:                (root.radius if hasattr(self, "radius") else [0, 0, 0, 0])                 if root.shadow_radius == [0.0, 0.0, 0.0, 0.0] else                 root.shadow_radius
2023-05-18 20:31:26.731 11892-11929 python                  ***                I        26:    canvas.after:
2023-05-18 20:31:26.738 11892-11929 python                  ***                I        27:        PopMatrix
2023-05-18 20:31:26.745 11892-11929 python                  ***                I   ...
2023-05-18 20:31:26.753 11892-11929 python                  ***                I   ValueError: 'border_radius' must have 4, got 0
2023-05-18 20:31:26.761 11892-11929 python                  ***                I     File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 925, in _build_canvas
2023-05-18 20:31:26.765 11892-11929 python                  ***                I     File "kivy/graphics/boxshadow.pyx", line 406, in kivy.graphics.boxshadow.BoxShadow.border_radius.__set__
2023-05-18 20:31:26.767 11892-11929 python                  ***                I     File "kivy/graphics/boxshadow.pyx", line 316, in kivy.graphics.boxshadow.BoxShadow._check_iter
2023-05-18 20:31:26.772 11892-11929 python                  ***                I   
2023-05-18 20:31:26.781 11892-11929 python                 ***                I  Python for android ended.

**Comment by HeaTTheatR** [comment]
Fix in master branch

**Comment by kmester** [comment]
I tried it and still has this issue with the kivymd master

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch

**Comment by kmester** [comment]
requirements = python3, android, kivy==2.2.0, https://github.com/kivymd/KivyMD/archive/master.zip, pillow, kvdroid, pyjnius

from buildozer.spec

**Comment by HeaTTheatR** [comment]
It doesn't make any difference! Bulldozer uses cache

**Comment by kmester** [comment]
should i use _sudo buildozer android clean_ before debugging?

**Comment by HeaTTheatR** [comment]
When you have changed something in requirements, you should run the command `bulldozer android clean`

**Comment by kmester** [comment]
i started a completely new project, and if i use the master branch of kivymd, i got the same error. i tested on macos with a new project, and the bug still occurs. for ios, the problem is solved if i use the kivymd==1.1.0 version, but its not a solution for Android, because of the Adreno GPU issue. Any idea how to fix it?

**Comment by HeaTTheatR** [comment]
Use KivyMD from master branch

**Comment by kmester** [comment]
@HeaTTheatR: 

- completely new projects, both on Windows and Mac, i have the same error, if i use radius in MDCard or MDRaisedButton
- kivy = 2.2.0
- kivymd = https://github.com/kivymd/KivyMD/archive/master.zip

Traceback (most recent call last):
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 925, in _build_canvas
File "kivy/graphics/boxshadow.pyx", line 406, in kivy.graphics.boxshadow.BoxShadow.border_radius.__set__
File "kivy/graphics/boxshadow.pyx", line 316, in kivy.graphics.boxshadow.BoxShadow._check_iter
ValueError: 'border_radius' must have 4, got 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/app/main.py", line 18846, in <module>
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/app.py", line 955, in run
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/app.py", line 925, in _run_prepare
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/app/main.py", line 18832, in build
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 305, in load_file
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 407, in load_string
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 660, in _apply_rule
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/uix/widget.py", line 470, in apply_class_lang_rules
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 540, in apply
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 662, in _apply_rule
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 660, in _apply_rule
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/uix/widget.py", line 470, in apply_class_lang_rules
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 540, in apply
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 595, in _apply_rule
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 928, in _build_canvas
kivy.lang.builder.BuilderException: Parser: File "<inline>", line 25:
23:            blur_radius: root.elevation * 10
Loaded native library version number "91.0.4472.114"
Flushed 1 samples from 1 histograms.
24:            border_radius:
>>   25:                (root.radius if hasattr(self, "radius") else [0, 0, 0, 0])                 if root.shadow_radius == [0.0, 0.0, 0.0, 0.0] else                 root.shadow_radius
26:    canvas.after:
27:        PopMatrix
...
ValueError: 'border_radius' must have 4, got 0
File "/mnt/c/Users/Admin/Desktop/***/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/***/arm64-v8a/kivy/lang/builder.py", line 925, in _build_canvas
File "kivy/graphics/boxshadow.pyx", line 406, in kivy.graphics.boxshadow.BoxShadow.border_radius.__set__
File "kivy/graphics/boxshadow.pyx", line 316, in kivy.graphics.boxshadow.BoxShadow._check_iter
