### ISSUE TITLE
ValueError: None is not allowed for TestIconButton._round_rad

### ISSUE THREAD

**Issue by Thimphu123** [kivymd/KivyMD#1504]
### Description of the Bug

Full log:
**[INFO   ] [Logger      ] Record log in C:\Users\Server\.kivy\logs\kivy_23-05-24_51.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Server\Desktop\SolarCeller\venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-03-15 (installed at "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 20.19.15.5171'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4400'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30 - Build 20.19.15.5171'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Server\Desktop\SolarCeller\test.py", line 31, in <module>
     TestApp().run()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\base.py", line 263, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\core\window\__init__.py", line 1691, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\core\window\__init__.py", line 1708, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\uix\relativelayout.py", line 306, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\uix\widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivy\uix\widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivymd\uix\button\button.py", line 1173, in on_touch_down
     return super().on_touch_down(touch)
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 358, in on_touch_down
     self.call_ripple_animation_methods(touch)
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 391, in call_ripple_animation_methods
     self.lay_canvas_instructions()
   File "C:\Users\Server\Desktop\SolarCeller\venv\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 436, in lay_canvas_instructions
     self._round_rad = self.radius
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 939, in kivy.properties.ListProperty.set
   File "kivy\properties.pyx", line 564, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 555, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 929, in kivy.properties.ListProperty.check
   File "kivy\properties.pyx", line 593, in kivy.properties.Property.check
 ValueError: None is not allowed for TestIconButton._round_rad**

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp

kv = '''
<TestIconButton@MDIconButton+CommonElevationBehavior>:
    size_hint: None, None
    size: "100dp", "100dp"
    md_bg_color: "red"
    
MDScreen:
    MDBoxLayout:
        TestIconButton:
            icon: "web"
            elevation: 3
        
        TestIconButton:
            icon: "eye"
            radius: self.size[0] / 2
            shadow_radius: self.radius
            shadow_softness: 18
            shadow_radius: self.radius
            elevation: 3
'''


class TestApp(MDApp):
    def build(self):
        return Builder.load_string(kv)


TestApp().run()

```

### Versions

* OS: Version 1803 OS Build 17134.286 (Window 10)
* Python: 3.10.10
* Kivy: 2.2.0
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
```
<TestIconButton@MDIconButton>:
    ...
    radius: [self.size[0] / 2, ]
```
