### ISSUE TITLE
I got this error while testing my paint App the color picker is not working in Android
But it's working in windows 

### ISSUE THREAD

**Issue by Ayush2006128** [kivymd/KivyMD#1544]
Here's my paint App code

```python
from typing import Union

from kivy.graphics import Color, Line
from kivymd.app import MDApp
from kivymd.toast import toast
from kivymd.uix.button import MDIconButton
from kivymd.uix.widget import MDWidget
from kivymd.uix.pickers import MDColorPicker



class MyPaintWidget(MDWidget):

    def __init__(self, color=(0,0,0)):
        super().__init__()
        self.color = color

    def on_touch_down(self, touch):
        with self.canvas:
            Color(*self.color)
            # d = 30.
            # Ellipse(pos=(touch.x - d / 2, touch.y - d / 2), size=(d, d))
            touch.ud['line'] = Line(points=(touch.x, touch.y))

    def on_touch_move(self, touch):
        touch.ud['line'].points += [touch.x, touch.y]


class MyPaintMDApp(MDApp):

    def __init__(self, **kwargs):
        super().__init__()

    def build(self):
        #self.icon = "paint-palette.ico"
        #self.title = "My Fantastic Paint MDApp"
        self.theme_cls.primary_palette= "Purple"
        self.theme_cls.accent_palette= "DeepPurple"

        parent = MDWidget()
        self.painter = MyPaintWidget()
        btn = MDIconButton(icon="delete")
        btn.bind(on_release=self.clearc)
        parent.add_widget(btn)

        parent.add_widget(self.painter)

        change_color = MDIconButton(icon="palette", y=150)
        change_color.bind(on_release=self.open_color_picker)
        parent.add_widget(change_color)

        save_btn = MDIconButton(icon="image-check", y=300)
        save_btn.bind(on_release=self.save_func)
        parent.add_widget(save_btn)


        return parent

    def clearc(self, obj):
        self.painter.canvas.clear()

    def open_color_picker(self,obj):
            color_picker = MDColorPicker(size_hint=(0.45, 0.85))
            color_picker.open()
            color_picker.bind(
                on_select_color=self.on_select_color,
                on_release=self.get_selected_color,
            )

    def update_color(self, color: list) -> None:
        self.painter.color=color

    def get_selected_color(
        self,
        instance_color_picker: MDColorPicker,
        type_color: str,
        selected_color: Union[list, str],
    ):
        '''Return selected color.'''

        #print(f"Selected color is {selected_color}")
        self.update_color(selected_color[:-1] + [1])

    def on_select_color(self, instance_gradient_tab, color: list) -> None:
        """Called when a gradient image is clicked."""

    def save_func(self,obj):
        self.root_window.screenshot(name='screenshot{:04d}.png')
        toast("save complete!")



if __name__ == '__main__':
    MyPaintMDApp().run()
```

And here's the error

```
[INFO   ] [Logger      ] Record log in /storage/emulated/0/Android/data/ru.iiec.pydroid3/files/.kivy/logs/kivy_23-08-19_2.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.7 (default, Oct  6 2021, 01:34:26) 
[GCC 11.1.0]
[INFO   ] [Python      ] Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-08-19 (installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@0530.0 (GIT@c263890aed, Ifb496a9c37, 1656315076) (Date:06/27/22)'>
[INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
[INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 619'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 2
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [Base        ] Unknown <android> provider
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 94, in <module>
     MyPaintMDApp().run()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/button/button.py", line 1187, in on_touch_up
     return super().on_touch_up(touch)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 404, in on_touch_up
     return super().on_touch_up(touch)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 63, in open_color_picker
     color_picker = MDColorPicker(size_hint=(0.45, 0.85))
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/pickers/colorpicker/colorpicker.py", line 468, in __init__
     super().__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/theming.py", line 1668, in __init__
     super().__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/modalview.py", line 187, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/behaviors/elevation.py", line 675, in __init__
     super().__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/button/button.py", line 1347, in __init__
     super().__init__(*args, **kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivymd/uix/button/button.py", line 1002, in __init__
     self.bind(
   File "kivy/_event.pyx", line 429, in kivy._event.EventDispatcher.bind
 KeyError: 'theme_text_color'
```

**Comment by HeaTTheatR** [comment]
Try using KivyMD from the main branch.

**Comment by Ayush2006128** [comment]
> Try using KivyMD from the main branch.

How to do that

**Comment by HeaTTheatR** [comment]
`requirements = https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by Ayush2006128** [comment]
thank you error fixd
