### ISSUE TITLE
MDToggleButton returns an attribute error 'ThemeManger' object has no attribute 'primary_dark'

### ISSUE THREAD

**Issue by MNwake** [kivymd/KivyMD#1605]
```
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.behaviors.toggle_behavior import MDToggleButton
from kivymd.uix.button import MDButton

KV = '''

BoxLayout:
    orientation: "vertical"
    md_bg_color: 'white'

    MyToggleButton:
        style: 'elevated'

        MDButtonIcon:
            id: power_icon
            icon: 'power-off'

        MDButtonText:
            text: 'button'
 
'''

class MyToggleButton(MDButton, MDToggleButton):
    pass

class MyApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

MyApp().run()
```

returns error:

```
 Traceback (most recent call last):
   File "/Users/Library/Application Support/JetBrains/PyCharmCE2023.3/scratches/scratch.py", line 34, in <module>
     MyApp().run()
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "/Users/Library/Application Support/JetBrains/PyCharmCE2023.3/scratches/scratch.py", line 32, in build
     return Builder.load_string(KV)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivy/lang/builder.py", line 412, in load_string
     self._apply_rule(
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     child = cls(__no_builder=True)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivymd/uix/button/button.py", line 949, in __init__
     super().__init__(*args, **kwargs)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivymd/uix/behaviors/declarative_behavior.py", line 312, in __init__
     super().__init__(**kwargs)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 164, in __init__
     super().__init__(**kwarg)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivymd/uix/behaviors/toggle_behavior.py", line 248, in __init__
     super().__init__(**kwargs)
   File "/Users/dev/projects/.myvenv/lib/python3.10/site-packages/kivymd/uix/behaviors/toggle_behavior.py", line 205, in __init__
     self.theme_cls.primary_dark
 AttributeError: 'ThemeManager' object has no attribute 'primary_dark'
666 None
111

Process finished with exit code 1
```

**Comment by HeaTTheatR** [comment]
Duplicate - https://github.com/kivymd/KivyMD/issues/1605
