### ISSUE TITLE
Problem with compilation kivymd 2.0.1

### ISSUE THREAD

**Issue by Allamaris0** [kivymd/KivyMD#1656]
Hello, I decided to move to kivymd 2.0.1 and I tried to compile an example code with ExpansionPanel.

```
import asynckivy
from kivy.animation import Animation
from kivy.lang import Builder
from kivy.metrics import dp
from kivy.uix.behaviors import ButtonBehavior

from kivymd.app import MDApp
from kivymd.uix.behaviors import RotateBehavior
from kivymd.uix.expansionpanel import MDExpansionPanel
from kivymd.uix.list import MDListItemTrailingIcon

KV = '''
<ExpansionPanelItem>

    MDExpansionPanelHeader:

        MDListItem:
            theme_bg_color: "Custom"
            md_bg_color: self.theme_cls.surfaceContainerLowColor
            ripple_effect: False

            MDListItemSupportingText:
                text: "Supporting text"

            TrailingPressedIconButton:
                id: chevron
                icon: "chevron-right"
                on_release: app.tap_expansion_chevron(root, chevron)

    MDExpansionPanelContent:
        orientation: "vertical"
        padding: "12dp", 0, "12dp", "12dp"
        md_bg_color: self.theme_cls.surfaceContainerLowestColor

        MDLabel:
            text: "Channel information"
            adaptive_height: True
            padding_x: "16dp"
            padding_y: "12dp"

        MDListItem:
            theme_bg_color: "Custom"
            md_bg_color: self.theme_cls.surfaceContainerLowestColor

            MDListItemLeadingIcon:
                icon: "email"

            MDListItemHeadlineText:
                text: "Email"

            MDListItemSupportingText:
                text: "kivydevelopment@gmail.com"

        MDListItem:
            theme_bg_color: "Custom"
            md_bg_color: self.theme_cls.surfaceContainerLowestColor

            MDListItemLeadingIcon:
                icon: "instagram"

            MDListItemHeadlineText:
                text: "Instagram"

            MDListItemSupportingText:
                text: "Account"

            MDListItemTertiaryText:
                text: "www.instagram.com/KivyMD"


MDScreen:
    md_bg_color: self.theme_cls.backgroundColor

    ScrollView:
        size_hint_x: .5
        pos_hint: {"center_x": .5, "center_y": .5}

        MDList:
            id: container
'''


class ExpansionPanelItem(MDExpansionPanel):
    ...


class TrailingPressedIconButton(
    ButtonBehavior, RotateBehavior, MDListItemTrailingIcon
):
    ...


class Example(MDApp):
    def on_start(self):
        async def set_panel_list():
            for i in range(12):
                await asynckivy.sleep(0)
                self.root.ids.container.add_widget(ExpansionPanelItem())

        super().on_start()
        asynckivy.start(set_panel_list())

    def build(self):
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)

    def tap_expansion_chevron(
        self, panel: MDExpansionPanel, chevron: TrailingPressedIconButton
    ):
        Animation(
            padding=[0, dp(12), 0, dp(12)]
            if not panel.is_open
            else [0, 0, 0, 0],
            d=0.2,
        ).start(panel)
        panel.open() if not panel.is_open else panel.close()
        panel.set_chevron_down(
            chevron
        ) if not panel.is_open else panel.set_chevron_up(chevron)


Example().run()
```

I debugged with adb locat and I got that error:
```
03-19 21:36:55.650 25394 25511 I python  :  Traceback (most recent call last):
03-19 21:36:55.650 25394 25511 I python  :    File "/content/.buildozer/android/app/main.py", line 7, in <module>
03-19 21:36:55.650 25394 25511 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/kivymd/app.py", line 67, in <module>
03-19 21:36:55.650 25394 25511 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/kivymd/theming.py", line 53, in <module>
03-19 21:36:55.651 25394 25511 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/materialyoucolor/utils/platform_utils.py", line 23, in <module>
03-19 21:36:55.651 25394 25511 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/materialyoucolor/quantize/__init__.py", line 1, in <module>
03-19 21:36:55.651 25394 25511 I python  :  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

```

Did I forget about something in buildozer.spec?
```
requirements = android, hostpython3==3.10.11, python3==3.10.11, kivy, materialyoucolor, kivymd, https://github.com/kivymd/KivyMD/archive/master.zip, plyer, camera4kivy, gestures4kivy,exceptiongroup,asyncgui,asynckivy,fuzzywuzzy,python-Levenshtein,PIL,packaging

```

**Comment by T-Dynamos** [comment]
Please set `p4a.branch` to `develop` and clean build.

**Comment by manns** [comment]
@T-Dynamos Thank you for the quick reply. I have stumbled upon the same issue, and I would appreciate if this information could be put into the `README.md` file of the project.

**Comment by Allamaris0** [comment]
Why did you close the issue if I didn't write that the bug was fixed?

Still the same error:

```
03-21 01:50:43.086  1599  1660 I python  :  Traceback (most recent call last):
03-21 01:50:43.086  1599  1660 I python  :    File "/content/.buildozer/android/app/main.py", line 7, in <module>
03-21 01:50:43.087  1599  1660 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/kivymd/app.py", line 67, in <module>
03-21 01:50:43.087  1599  1660 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/kivymd/theming.py", line 53, in <module>
03-21 01:50:43.087  1599  1660 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/materialyoucolor/utils/platform_utils.py", line 23, in <module>
03-21 01:50:43.087  1599  1660 I python  :    File "/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/materialyoucolor/quantize/__init__.py", line 1, in <module>
03-21 01:50:43.087  1599  1660 I python  :  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
03-21 01:50:43.087  1599  1660 I python  : Python for android ended.
```

**Comment by Allamaris0** [comment]
> @T-Dynamos Thank you for the quick reply. I have stumbled upon the same issue, and I would appreciate if this information could be put into the `README.md` file of the project.

it is in the readme of [materialyoucolor](https://github.com/T-Dynamos/materialyoucolor-python)

**Comment by manns** [comment]
@Allamaris  Thank you for pointing out the relevant readme entry. 

I am suggesting to the dev team to add a note with the link to the [kivymd Documentation](https://kivymd.readthedocs.io/en/latest/getting-started/) Web page.
