### ISSUE TITLE
Error importing kivymd.color_definitions when using kivymd_extensions.akivymd

### ISSUE THREAD

**Issue by BathyMapsAustralia** [kivymd/KivyMD#1683]
### Description of the Bug

The kivymd.color_definitions module cannot be found in the latest version of kivymd and throws an error when color and palette color are called from the color_definitions module. Upon perusal of the latest kivymd vs v1.1.1, the color_definitions module is not included in the latest version unlike v1.1.1. It appears kivymd_extensions.akivymd still relies on the color_definitions module. 

Code example attached
[my.zip](https://github.com/kivymd/KivyMD/files/15019615/my.zip)

Reproducible
------------
My steps were:
- import kivymd_extensions.akivymd
- created an AKBarChart using this example code https://github.com/subhranil2699/akivymd_codes/blob/main/02_barchart.py 
- ran main.py 

### Console Logs

 Traceback (most recent call last):
   File "C:\Users\CobbanT\Documents\kivy\main.py", line 285, in <module>
     MyApp().run()
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "C:\Anaconda\envs\kivy\lib\site-packages\kivymd\app.py", line 142, in _run_prepare
     super()._run_prepare()
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\app.py", line 925, in _run_prepare
     root = self.build()
   File "C:\Users\CobbanT\Documents\kivy\main.py", line 147, in build
     self.sm.add_widget(Site1Screen(name='site_1'))
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\uix\relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\uix\widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\lang\builder.py", line 545, in apply
     self._apply_rule(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\lang\builder.py", line 667, in _apply_rule
     self._apply_rule(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\lang\builder.py", line 667, in _apply_rule
     self._apply_rule(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\lang\builder.py", line 667, in _apply_rule
     self._apply_rule(
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\lang\builder.py", line 625, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\CobbanT\AppData\Roaming\Python\Python39\site-packages\kivy\factory.py", line 155, in __getattr__
     module = importlib.__import__(
   File "<frozen importlib._bootstrap>", line 1109, in __import__
   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "C:\Anaconda\envs\kivy\lib\site-packages\kivymd_extensions\akivymd\uix\charts.py", line 17, in <module>
     from kivymd.color_definitions import colors, palette
 ModuleNotFoundError: No module named 'kivymd.color_definitions'

### Versions

* OS: Microsoft Windows 10 Enterprise Version10.0.19045 Build 19045
* Python: 3.9
* Kivy: 2.3.0
* KivyMD: 2.0.1.dev0

**Comment by HeaTTheatR** [comment]
kivymd_extensions.akivymd is not supported with the latest version of the KivyMD library

**Comment by BathyMapsAustralia** [comment]
Hi @HeaTTheatR do you know if there are plans to support features available in kivymd_extensions.akivymd in latest versions of kivymd?

**Comment by tsrift** [comment]
```
from kivymd.color_definitions import colors
Error: No module named 'kivymd.color_definitions'
```

What is the replacement of color_definitions in the new version od KivyMD? How to upgrade?

**Comment by Novfensec** [comment]
> ```
> from kivymd.color_definitions import colors
> Error: No module named 'kivymd.color_definitions'
> ```
> 
> What is the replacement of color_definitions in the new version od KivyMD? How to upgrade?

```python
self.theme_cls.dynamic_color_names
```
