### ISSUE TITLE
Trying to run the sample code from kivymd website and I get a type error

### ISSUE THREAD

**Issue by Femi1984** [kivymd/KivyMD#1713]
### Description of the Bug

Traceback (most recent call last):
   File "test_run.py", line 1, in <module>
     from kivymd.app import MDApp
   File "/home/femi/.local/lib/python3.8/site-packages/kivymd/app.py", line 65, in <module>
     from kivymd.theming import ThemeManager
   File "/home/femi/.local/lib/python3.8/site-packages/kivymd/theming.py", line 49, in <module>
     from materialyoucolor.utils.color_utils import argb_from_rgba_01
   File "/home/femi/.local/lib/python3.8/site-packages/materialyoucolor/utils/color_utils.py", line 1, in <module>
     from materialyoucolor.utils.math_utils import matrix_multiply, clamp_int
   File "/home/femi/.local/lib/python3.8/site-packages/materialyoucolor/utils/math_utils.py", line 53, in <module>
     def matrix_multiply(row: list[float], matrix: list[list[float]]) -> list[float]:
 TypeError: 'type' object is not subscriptable

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel


class MainApp(MDApp):
    def build(self):
        return MDLabel(text="Hello, World", halign="center")


MainApp().run()




### Versions

* OS: ubuntu 20.04
* Python: 3.8
* Kivy: v2.3.0
* KivyMD:  2.0.1.dev0

**Comment by T-Dynamos** [comment]
This is a known issue: https://github.com/T-Dynamos/materialyoucolor-python/issues/4

**Comment by Femi1984** [comment]
> This is a known issue: [T-Dynamos/materialyoucolor-python#4](https://github.com/T-Dynamos/materialyoucolor-python/issues/4)

Is there a fix?

**Comment by T-Dynamos** [comment]
@Femi1984 Till now: use latest python version.

**Comment by iamrobusto** [comment]
How about fixing maths_utils.py in materialyoucolor so it runs on Python 3.7 and 3.8? I'm sure this is trivial. 
https://github.com/OpenBMB/ProAgent/issues/17 suggests how it can be done.
It is very annoying for those wanting to use KivyMD to have to go through the hassle of upgrading Python yet again just to get a 4 line matrix multiplication function to work.

The doc on https://github.com/kivymd/KivyMD seems unaware of this issue for versions of Python <3.9.

**Comment by iamrobusto** [comment]
I got this to work by replacing all instances of:

`list[<type>]`
 with 
`List[<type>]`

 similarly replace 
`dict[>type>] `
with 
`Dict[<type>]`

in all the materialyoucolor code.

In /materialyoucolor/temperature/temperature_cache.py you need to change line 166 from

`def temps_by_hct(self) -> dict[Hct:float]: `

to 

`def temps_by_hct(self) -> Dict[Hct,float]` 

(i.e. use class Dict and put a comma instead of a colon.)

Import List and Dict from the typing module where needed. 

`from typing import List, Dict`

You'll need to run the example a number of times to pick up all the instances of these errors.

**Comment by Novfensec** [comment]
Hey @iamrobusto , I also tried to customize materialyoucolor for python 3.8 and hopefully got it working. 

But,

You'll have to do a lot of rework for the type hints and to replace the walrus operator `:=` which is available in python versions >= 3.8 to support other lower version like 3.7 etc.

I mean introducing if else blocks in place of the simple `:=` is a huge headache and time consuming. I still regret the decision as python 3.8 also reaching end of support. Its actually of no use.

Also on older systems you'll need visual cpp build tools 2022 ( 2.5gbs approx.) to be installed from Microsoft visual studio website.

You should upgrade to get the best of it.
If you need 32 bit distributions of newer python versions Contact me on Discord: https://discord.gg/uYHQUCNT

I use win7 32 bit currently running python 3.11.10.

**Comment by iamrobusto** [comment]
Thanks for your comment and advice. I was not aware of the walrus operator issue . I take your point though, they must be everywhere and a pain to replace. 
Upgrading Python for me always means a lot of work.. The safest way is to instal the new version in a virtual environment. Then though you typically have to reinstal a lot of packages. In my case that means ROS, OpenCV, Kivy, the list goes on.
I guess I'll just have to get on with it.
I run Linux Ubuntu 64-bit. 
Are you really still using Windows 7?

**Comment by Novfensec** [comment]
> Thanks for your comment and advice. I was not aware of the walrus operator issue . I take your point though, they must be everywhere and a pain to replace. 
> Upgrading Python for me always means a lot of work.. The safest way is to instal the new version in a virtual environment. Then though you typically have to reinstal a lot of packages. In my case that means ROS, OpenCV, Kivy, the list goes on.
> I guess I'll just have to get on with it.
> I run Linux Ubuntu 64-bit. 
> Are you really still using Windows 7?

Yup
