### ISSUE TITLE
kivy.factory.FactoryException: Unknown class <NavigationDrawerIconButton>

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivymd/KivyMD#176]
main.py
```

from kivymd.app import MDApp
from kivy.clock import Clock
from kivy.base import EventLoop
from kivymd.uix.navigationdrawer import NavigationLayout
#from kivy.loader import Loader

#Loader.loading_image = 'loading_2.gif'

class MainNavigationLayout(NavigationLayout):
    _panel_disable = True
    token = None

    def to_page(self, page):
        self.ids.screen_manager.current = page

    def enable_drawer(self):
        self.ids.toolbar.left_action_items.append(['menu', lambda x: self.toggle_nav_drawer()])

class Main(MDApp):
    def __init__(self):
        MDApp.__init__(self)
        self.theme_cls.primary_palette = 'Red'

    def on_start(self):
        EventLoop.window.bind(on_keyboard=self.hook_key)

    def hook_key(self, window, key, *args):
        if key == 27:
            self.root.ids.screen_manager.current = "screen_login"
            prev = self.root.ids["screen_manager"].current_screen
            print(prev)
            return True

Main().run()
```

main.kv

```
#:include pages/login/login.kv
#:include pages/inicio/inicio.kv

MainNavigationLayout:
    _panel_disable: True

    MDNavigationDrawer:
        drawer_logo: "menu.png"
        NavigationDrawerIconButton:
            icon: "home"
            text: "Inicio"

        NavigationDrawerIconButton:
            icon: "lock"
            text: "Pagina 2"

    BoxLayout:
        orientation: "vertical"
        MDToolbar:
            id: toolbar
            title: "Real Murcia"
            md_bg_color: app.theme_cls.primary_color
            left_action_items: []
        ScreenManager:
            id: screen_manager
            PageLogin:
            PageInicio:
```

python version: 3.7
kivy version: 1.11.1
kivymd version: v0.103.0 beta

Error
```
INFO   ] [Logger      ] Record log in /home/francisco/.kivy/logs/kivy_20-02-02_25.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/francisco/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.6 (default, Dec 19 2019, 23:49:42) 
[GCC 5.4.0 20160609]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3.7"
[INFO   ] [KivyMD      ] v0.103.0
[INFO   ] [Factory     ] 184 symbols loaded
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/francisco/.local/lib/python3.7/site-packages/kivy/core/window/window_pygame.py line 42.Called from /home/francisco/.local/lib/python3.7/site-packages/kivy/core/__init__.py line 71 by core_select_lib().
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'llvmpipe (LLVM 6.0, 256 bits)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/francisco/.local/lib/python3.7/site-packages/kivy/core/image/img_pygame.py line 27.Called from /home/francisco/.local/lib/python3.7/site-packages/kivy/core/image/__init__.py line 460 by load().
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "main.py", line 34, in <module>
     Main().run()
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/app.py", line 828, in run
     self.load_kv(filename=self.kv_file)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/app.py", line 599, in load_kv
     root = Builder.load_file(rfilename)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 405, in load_string
     rule_children=rule_children)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 616, in _apply_rule
     cls = Factory_get(cname)
   File "/home/francisco/.local/lib/python3.7/site-packages/kivy/factory.py", line 131, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <NavigationDrawerIconButton>
```

this worked for me before, now for some reason it doesn't work for me, has there been any change?

**Comment by HeaTTheatR** [comment]
There is no class in the `KivyMD` library named `NavigationDrawerIconButton`.
https://github.com/HeaTTheatR/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed

**Comment by robertkeir** [comment]
Hello. Has this been resolved?

**Comment by ArtemSBulgakov** [comment]
@robertkeir Usage of navigation drawer has changed. See [wiki](https://github.com/kivymd/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed) and [docs](https://kivymd.readthedocs.io/en/latest/components/navigation-drawer/index.html) for new examples

**Comment by robertkeir** [comment]
> @robertkeir Usage of navigation drawer has changed. See [wiki](https://github.com/kivymd/KivyMD/wiki/Components-Navigation-Drawer#using-mdnavigationdrawer-has-changed) and [docs](https://kivymd.readthedocs.io/en/latest/components/navigation-drawer/index.html) for new examples

Thank you. Can the code be updated?
