### ISSUE TITLE
Trouble installing in Kivy3.app (OS X)

### ISSUE THREAD

**Issue by Niehztog** [kivymd/KivyMD#178]
#### Description of the Bug

Hello. I've made a kivymd application and am currently trying to build an app package for OS X (.dmg file). I've set up a virtual machine in virtualbox with macOS High Sierra and downloaded and installed the Kivy3 app from kivy.org. (I am following this guide for building the app package, since build-methods with pyinstaller and buildozer have failed for other reasons: https://kivy.org/doc/stable/guide/packaging-osx.html#using-the-kivy-sdk)
In order to run my kivymd application using the Kivy3.App I have to install kivymd first.

```kivy3 -m pip install kivymd``` fails with the error message
> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
> Could not fetch URL https://pypi.python.org/simple/kivymd/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/kivymd/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping

so obviously the python3 interpreter shipped inside the kivy app on osx is missing ssl, so I tried without:
```kivy3 -m pip install git+http://github.com/HeaTTheatR/KivyMD.git```

This fails with the error message:
> kivy3 -m pip install git+http://github.com/HeaTTheatR/KivyMD.git
> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
> Collecting git+http://github.com/HeaTTheatR/KivyMD.git
>   Cloning http://github.com/HeaTTheatR/KivyMD.git to /private/var/folders/nn/s3chw7qn0_v3qcdc783nqfrh0000gn/T/pip-dijd_u20-build
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/nn/s3chw7qn0_v3qcdc783nqfrh0000gn/T/pip-dijd_u20-build/setup.py", line 54, in <module>
>         python_requires=">=3.6",
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
>         _install_setup_requires(attrs)
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
>         dist.parse_config_files(ignore_option_errors=True)
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/setuptools/dist.py", line 491, in parse_config_files
>         _Distribution.parse_config_files(self, filenames=filenames)
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/distutils/dist.py", line 395, in parse_config_files
>         parser.read(filename)
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/configparser.py", line 697, in read
>         self._read(fp, filename)
>       File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/configparser.py", line 1015, in _read
>         for lineno, line in enumerate(fp, start=1):
>       File "/Applications/Kivy3.app/Contents/Resources/./venv/bin/../../../Frameworks/python/3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 113: ordinal not in range(128)
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nn/s3chw7qn0_v3qcdc783nqfrh0000gn/T/pip-dijd_u20-build/

Whats the preferred method of installing kivymd for the Kivy3 app on os x? Whats the preferred method for building an application package for os x?

### Versions

* OS: macOS High Sierra 10.13.6
* Python: Python 3.6.5 (packaed into Kivy3.app)
* Kivy: 1.11.0
* KivyMD: latest

**Comment by Niehztog** [comment]
I managed to fix the initial problem of missing ssl library by using the following command:
```
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```
actually it didn't have anything to do with kivymd. This bugreport can be closed
