### ISSUE TITLE
Can't start demo app kitchen_sink

### ISSUE THREAD

**Issue by halitkalayci** [kivymd/KivyMD#181]
#### Description of the Bug

When I try to open the demo app which is kitchen_sink it throws an error.

### Code and Logs

```python
 Traceback (most recent call last):
   File "main.py", line 8, in <module>
     from libs.baseclass.dialog_change_theme import KitchenSinkDialogChangeTheme
   File "D:\PythonOdevler\KivyMD\demos\kitchen_sink\libs\baseclass\dialog_change_theme.py", line 6, in <module>
     from kivymd.color_definitions import palette, colors
 ImportError: cannot import name 'palette' from 'kivymd.color_definitions' (D:\Python\lib\site-packages\kivymd\color_definitions.py)
"""



### Screenshots


![image](https://user-images.githubusercontent.com/59770497/74604408-c2359d00-50ce-11ea-91b0-4d3bdc8bd262.png)[image/]

**Comment by HeaTTheatR** [comment]
You are using an old version of the library. Current Version - 0.103.1

**Comment by halitkalayci** [comment]
I get link from here and cloned it, how can i find the latest version?

**Comment by HeaTTheatR** [comment]
@Sanchklyc ```python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git```
