### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.uix.boxlayout'

### ISSUE THREAD

**Issue by gargsaar** [kivymd/KivyMD#225]
### Description of the Bug

I'm new to kivymd. Getting the below error  when running the kitchen_sink main.py.

**ModuleNotFoundError: No module named 'kivymd.uix.boxlayout'**

boxlayout.py exists in kivymd>uix folder

### Screenshots

refer screenshot
<img width="957" alt="kivymd_error" src="https://user-images.githubusercontent.com/8476424/77515777-2c481b80-6e9f-11ea-8dc0-b160980a3c7f.png">

**Comment by HeaTTheatR** [comment]
`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by romybompart** [comment]
Hi I got a problem that might be related. I am using window + conda + python 3.7. 
Once I clicked on dialog I got this error: 
    Traceback (most recent call last):
   File "main.py", line 171, in <module>
     KitchenSinkApp().run()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd-0.104.1-py3.7.egg\kivymd\uix\list.py", line 819, in on_touch_up
     super().on_touch_up(touch)
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd-0.104.1-py3.7.egg\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "main.py", line 73, in <lambda>
     x
   File "main.py", line 88, in set_example_screen
     exec(self.data_screens[name_screen]["Import"])
   File "<string>", line 1, in <module>
   File "C:\Users\Romy1\Documents\Documentos Romy\Books\UANL MASTER\Tercer Tetra\SE_PDI\Activity 2\Kivy_project\demos\KivyMD-master\KivyMD-master\demos\kitchen_sink\libs\baseclass\dialogs.py", line 7, in <module>
     from demos.kitchen_sink.libs.baseclass.list_items import (
 **ModuleNotFoundError: No module named 'demos.kitchen_sink'**

**Comment by erivaldobraga** [comment]
help!!
?    
from kivymd.uix.pickers import MDDatePicker
 ModuleNotFoundError: No module named 'kivymd.uix.pickers

**Comment by HeaTTheatR** [comment]
@erivaldobraga Use `KivyMD` library from master branch.
