### ISSUE TITLE
M

### ISSUE THREAD

**Issue by HamitKURT** [kivymd/KivyMD#233]
### Description of the Bug

When click on MDchips, gets an error "TypeError: callback() takes 2 positional arguments but 3 were given"

### 31/03/2020 04:00 UTC

C:\Users\User\PycharmProjects\KivyMD-Test\venv\Scripts\python.exe C:/Users/User/PycharmProjects/KivyMD-Test/main.py
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_20-03-31_25.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\User\PycharmProjects\KivyMD-Test\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [KivyMD      ] v0.104.0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.13399 Compatibility Profile Context 15.201.1151.1008'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon HD 6800 Series'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:/Users/User/PycharmProjects/KivyMD-Test/main.py", line 150, in <module>
     MainApp().run()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\core\window\__init__.py", line 1406, in on_motion
     self.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\core\window\__init__.py", line 1442, in on_touch_up
     if w.dispatch('on_touch_up', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\widget.py", line 571, in on_touch_up
     if child.dispatch('on_touch_up', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\scrollview.py", line 895, in on_touch_up
     if self.dispatch('on_scroll_stop', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\scrollview.py", line 934, in on_scroll_stop
     self.simulate_touch_down(touch)
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\scrollview.py", line 642, in simulate_touch_down
     ret = super(ScrollView, self).on_touch_down(touch)
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\User\PycharmProjects\KivyMD-Test\venv\lib\site-packages\kivymd\uix\chip.py", line 263, in on_touch_down
     self.callback(self, self.label)
 TypeError: callback() takes 2 positional arguments but 3 were given

Process finished with exit code 1

### Versions

* OS: Windows 10
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.104.0

**Comment by HeaTTheatR** [comment]
@HamitKURT Fix
