### ISSUE TITLE
MDDialog Usage Example Crashes

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#245]
### Description of the Bug
Crash
No crash if  the buttons parameter is removed

### Code and Logs
https://kivymd.readthedocs.io/en/latest/components/dialog/index.html
The Usage example

```
 Traceback (most recent call last):
   File "C:\Users\bobf\Documents\md2.py", line 39, in <module>
     Example().run()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 7, in <module>
   File "C:\Users\bobf\Documents\md2.py", line 32, in show_alert_dialog
     text="DISCARD", text_color=self.theme_cls.primary_color
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivymd\uix\dialog.py", line 320, in __init__
     super().__init__(**kwargs)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivymd\theming.py", line 907, in __init__
     super().__init__(**kwargs)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\modalview.py", line 161, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\bobf\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes no parameters
```

### Versions

* OS:  Windows 10
* Python:  3.6.1
* Kivy:   1.11.1
* KivyMD:  https://github.com/HeaTTheatR/KivyMD.git   (today)

**Comment by HeaTTheatR** [comment]
I was unable to reproduce this error.
