### ISSUE TITLE
kitchen_sink Dialogs--> Confirmation ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by nooninm** [kivymd/KivyMD#268]
### Description of the Bug
Following Sandberg Kivy/KivyMD first video on Windows 10, Python 3.8.   Fresh install of KivyMD.   In the Windows 10 command prompt box I did cd and ran C:\.....\KivyMD-master\demos\kitchen_sink\main.py per the video.

To recreate bug, when the screen pops up, go immediately to Dialogs-->Confirmation.
Check Callisto, then clicked OK
Nothing happens so click "Dialogs" to go back to the main screen.
Click Custom
Enter abcdefghijklmnop for both City and Street.
Click OK to get back to the main Dialogs screen.
Click Confirmation again.
It crashes.  I did this several times.
The entire 67 lines of content from my Windows 10 command prompt box is pasted below.
PS: Thanks for doing the KivyMD thing.

### Code and Logs
Downloaded Zip from https://github.com/HeaTTheatR/KivyMD
Then copied the code to a safe directory and ran "python setup.py install"
C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink>main.py
[INFO   ] [Logger      ] Record log in C:\Users\Malcolm\.kivy\logs\kivy_20-04-24_9.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v2.0.0rc1, git-ae0fa0c, 20191229
[INFO   ] [Kivy        ] Installed at "C:\Python38\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Python38\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 436.30'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 710/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] v0.104.0
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink\main.py", line 171, in <module>
     KitchenSinkApp().run()
   File "C:\Python38\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 560, in runTouchApp
     EventLoop.mainloop()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 334, in mainloop
     self.idle()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 375, in idle
     Clock.tick()
   File "C:\Python38\lib\site-packages\kivy\clock.py", line 646, in tick
     self.post_idle(ts, self.idle())
   File "C:\Python38\lib\site-packages\kivy\clock.py", line 689, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "C:\Python38\lib\site-packages\kivy\animation.py", line 352, in _update
     self.stop(widget)
   File "C:\Python38\lib\site-packages\kivy\animation.py", line 217, in stop
     self.dispatch('on_complete', widget)
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "C:\Python38\lib\site-packages\kivy\uix\modalview.py", line 230, in <lambda>
     a.bind(on_complete=lambda *x: self.dispatch('on_open'))
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\uix\dialog.py", line 534, in on_open
     if self.ids.text.texture_size[1] > Window.height:
   File "kivy\properties.pyx", line 860, in kivy.properties.ObservableDict.__getattr__
   File "kivy\properties.pyx", line 854, in kivy.properties.ObservableDict._weak_return
   File "kivy\weakproxy.pyx", line 42, in kivy.weakproxy.WeakProxy.__class__.__get__
   File "kivy\weakproxy.pyx", line 28, in kivy.weakproxy.WeakProxy.__ref__
 ReferenceError: weakly-referenced object no longer exists

### Versions

* OS:  Windows 10
* Python:  3.8
* Kivy: 2.0.0rc1
* KivyMD: v0.104.0

**Comment by nooninm** [comment]
PS:  While running " python setup.py install"  I saw this warning:
build\bdist.win32\egg\kivymd\uix\picker.py:625: SyntaxWarning: "is" with a literal. Did you mean "=="?
  op = 1 if operation is "next" else -1

**Comment by nooninm** [comment]
I can repeat this bug over and over

**Comment by RobertFlatt** [comment]
FYI I have seen this elsewhere, it is related to changes in Python 3.8 garbage collection that are finding hidden issues. And understandably may be difficult to replicate.

One example that is fixed is https://github.com/kivy/kivy/commits/master/kivy/weakmethod.py

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/issues/248
