### ISSUE TITLE
kitchen_sink Files Manager "Open files manager" crashes with TypeError

### ISSUE THREAD

**Issue by nooninm** [kivymd/KivyMD#269]
### Description of the Bug

Windows 10, Python 3.8. Fresh install of KivyMD : v0.104.0.

To recreate the bug, run  C:\....\demos\kitchen_sink\main.py

Go immediately to Files Manager
Click on "Open files manager".
The window crashes right away.
I did this several times.

PS: Great job, guys.

### Code and Logs
The entire 70+ lines of content from my Windows 10 command prompt box is pasted below.

C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink>main.py
[INFO   ] [Logger      ] Record log in C:\Users\Malcolm\.kivy\logs\kivy_20-04-24_12.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v2.0.0rc1, git-ae0fa0c, 20191229
[INFO   ] [Kivy        ] Installed at "C:\Python38\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Python38\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 436.30'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 710/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] v0.104.0
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink\main.py", line 171, in <module>
     KitchenSinkApp().run()
   File "C:\Python38\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 560, in runTouchApp
     EventLoop.mainloop()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 334, in mainloop
     self.idle()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 378, in idle
     self.dispatch_input()
   File "C:\Python38\lib\site-packages\kivy\base.py", line 329, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Python38\lib\site-packages\kivy\base.py", line 295, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\uix\button.py", line 1083, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Python38\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\Python38\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink\libs\kv\file_manager.kv", line 14, in <module>
     on_release: root.file_manager_open()
   File "C:\Bks_Arts\Python\kivy\KivyMD\KivyMD-master\demos\kitchen_sink\libs\baseclass\filemanager.py", line 27, in file_manager_open
     MDDialog(
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\uix\dialog.py", line 500, in __init__
     super().__init__(**kwargs)
   File "C:\Python38\lib\site-packages\kivymd-0.104.0-py3.8.egg\kivymd\theming.py", line 907, in __init__
     super().__init__(**kwargs)
   File "C:\Python38\lib\site-packages\kivy\uix\modalview.py", line 186, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "C:\Python38\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "C:\Python38\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Python38\lib\site-packages\kivy\uix\widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### Versions

* OS: Windows 10
* Python:  3.8
* Kivy:  2.0.0rc1
* KivyMD: v0.104.0

**Comment by HeaTTheatR** [comment]
There is no guarantee that this will work with `Python: 3.8` and with
`Kivy: 2.0.0rc1`
