### ISSUE TITLE
0.104.1 Dialog error

### ISSUE THREAD

**Issue by pj-mathematician** [kivymd/KivyMD#283]
I recently installed the 0.104.1 version, now my dialog box are not opening and are giving TypeError: object.__init__() takes no arguments
It was working perfectly fine before.
Code snippet:
```
    def show_dialog(self, *args):
        if not self.dialog:
            self.dialog = MDDialog(title='Confirmation',
                                   text='You have been registered.',
                                   size_hint=(0.4, 0.3),
                                   text_button_ok='OK',
                                   events_callback=self.on_signup)

        self.dialog.open()
```
Error:
```
Traceback (most recent call last):
   File "/storage/emulated/0/Documents/12project/Update/new/Scheduler-master/main.py", line 81, in <module>
     Test().run()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 724, in mainloop
     self._mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 459, in _mainloop
     EventLoop.idle()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/base.py", line 340, in idle
     self.dispatch_input()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/base.py", line 291, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivymd/uix/behaviors/ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivymd/uix/button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/storage/emulated/0/Documents/12project/Update/new/Scheduler-master/signupwindow.kv", line 67, in <module>
     on_release: app.show_dialog()
   File "/storage/emulated/0/Documents/12project/Update/new/Scheduler-master/main.py", line 74, in show_dialog
     events_callback=self.on_signup)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivymd/uix/dialog.py", line 500, in __init__
     super().__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivymd/theming.py", line 907, in __init__
     super().__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/uix/modalview.py", line 161, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/kivy/uix/widget.py", line 340, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes no arguments
```

**Comment by HeaTTheatR** [comment]
@pj-mathematician 
https://github.com/HeaTTheatR/KivyMD#api-breaking-changes
https://kivymd.readthedocs.io/en/latest/components/dialog/index.html

**Comment by mkc2019** [comment]
A note to anyone who is directed here: The PyPI version (0.104.1) of kivymd seems to be bugged. Using the master branch of this repository can solve quite a few problems, including this one. You can identify it if you compare the dialog.py in this repository to that installed using PyPI.
Hence, fork this repository, uninstall kivymd, install the forked repository, and the problem should be resolved.
