### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by Charanpreet-Singh-AI** [kivymd/KivyMD#288]
### Description of the Bug

I'm using the MDToolBar . When i use left_action_item , i immediately get ReferenceError: weakly-referenced object no longer exists error. In android app .
But when i remove left_action_item then i didn't get that error again. I couldn't figure out the problem. here is the log from logcat:

### Code and Logs

``` 
05-05 16:40:33.661 23302 23332 I python : Traceback (most recent call last):
05-05 16:40:33.661 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/app/main.py", line 1316, in 
05-05 16:40:33.661 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
05-05 16:40:33.661 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
05-05 16:40:33.662 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
05-05 16:40:33.662 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
05-05 16:40:33.662 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 339, in idle
05-05 16:40:33.663 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/clock.py", line 591, in tick
05-05 16:40:33.663 23302 23332 I python : File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.663 23302 23332 I python : File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.663 23302 23332 I python : File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
05-05 16:40:33.664 23302 23332 I python : File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
05-05 16:40:33.664 23302 23332 I python : File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
05-05 16:40:33.664 23302 23332 I python : File "/home/charanpreet/Desktop/test1/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/weakmethod.py", line 56, in is_dead
05-05 16:40:33.664 23302 23332 I python : ReferenceError: weakly-referenced object no longer exists
05-05 16:40:33.664 23302 23332 I python : Python for android ended.

```

### Versions

* OS: Ubuntu
* Python: 3.7.6 in windows , 3.8 in buildozer 
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Charanpreet123 Attach the minimum code that reproduces this error.

**Comment by HeaTTheatR** [comment]
@Charanpreet123 
```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "MDToolbar"
        left_action_items: [["menu", lambda x: x]]
        right_action_items: [["arrow-left", lambda x: x]]

    MDLabel:
        text: "Content"
        halign: "center"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

The error `ReferenceError: object with weak reference no longer exists`  is not related to the `KivyMD` library.
