### ISSUE TITLE
Im trying to install kivymd in my kivy-ios project but im getting an error

### ISSUE THREAD

**Issue by temitayoadefemimatthew** [kivymd/KivyMD#311]
Everytime i try to run ```python3 toolchain.py pip3 install kivymd```

I get the error below. ill appreciate your assistance 

```
temitayoadefemi@Temitayos-MacBook-Air kivy-ios % python3 toolchain.py pip3 install kivymd
toolchain.py:93: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Global: hostpython located at /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[ERROR   ] Executing pip with: ['/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pip3', 'install', '--isolated', '--ignore-installed', '--prefix', '/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3', 'kivymd']
Collecting kivymd
  Using cached https://files.pythonhosted.org/packages/c4/4e/f33085dab6420009fefc214cb3f8fc88ecd9d9e766976aa14f93b033a53a/kivymd-0.104.1-py3-none-any.whl
Collecting kivy (from kivymd)
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-qrcjgqqg/kivy/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-qrcjgqqg/kivy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: /private/tmp/pip-install-qrcjgqqg/kivy/
    Complete output (86 lines):
    fatal: not a git repository (or any of the parent directories): .git
        ERROR: Command errored out with exit status 1:
         command: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-wheel-4dt55l8u/cython/setup.py'"'"'; __file__='"'"'/private/tmp/pip-wheel-4dt55l8u/cython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
             cwd: /private/tmp/pip-wheel-4dt55l8u/cython/
        Complete output (9 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/tmp/pip-wheel-4dt55l8u/cython/setup.py", line 193, in <module>
            compile_cython_modules(cython_profile, cython_compile_more, cython_with_refnanny)
          File "/private/tmp/pip-wheel-4dt55l8u/cython/setup.py", line 113, in compile_cython_modules
            'pgen', os.pathsep.join([os.environ['PATH'], os.path.join(get_python_inc(), '..', 'Parser')]))
          File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/os.py", line 675, in __getitem__
            raise KeyError(key) from None
        KeyError: 'PATH'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
     WARNING: The wheel package is not available.
     Traceback (most recent call last):
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
         subprocess.check_call(cmd)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/subprocess.py", line 364, in check_call
         raise CalledProcessError(retcode, cmd)
     subprocess.CalledProcessError: Command '['/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphc3gx8cc', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    
     During handling of the above exception, another exception occurred:
    
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/private/tmp/pip-install-qrcjgqqg/kivy/setup.py", line 1073, in <module>
         setup(
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
         _install_setup_requires(attrs)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
         dist = best[req.key] = env.best_match(
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
         return self.obtain(req, installer)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
         return installer(requirement)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
         return fetch_build_egg(self, req)
       File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
         raise DistutilsError(str(e))
     distutils.errors.DistutilsError: Command '['/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphc3gx8cc', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    Using setuptools
    User distribution detected, avoid portable command.
    Using this graphics system: OpenGL ES 2
    OSX framework used, force to x86_64 only
    OSX ARCHFLAGS are: -arch x86_64
    GStreamer framework not found, fallback on pkg-config
    GStreamer found via pkg-config
    Missing framework /Library/Frameworks/SDL2.framework
    Missing framework /Library/Frameworks/SDL2_ttf.framework
    Missing framework /Library/Frameworks/SDL2_image.framework
    Missing framework /Library/Frameworks/SDL2_mixer.framework
    SDL2 frameworks not found, fallback on pkg-config
    SDL2 found via pkg-config
    Xcode detected at b'/Applications/Xcode.app/Contents/Developer', and using OS X10.15 sdk
    WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 1)
    
    b"Package pangoft2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `pangoft2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'pangoft2' found\n"
    
    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
temitayoadefemi@Temitayos-MacBook-Air kivy-ios % 
```

**Comment by HeaTTheatR** [comment]
This error is not related to `KivyMD`.

**Comment by SanguineL** [comment]
Mind explaining what the error is related to? Because I can install other modules, just not KivyMD.
