### ISSUE TITLE
Customized MDropDownMenu crashed when disabling left icon

### ISSUE THREAD

**Issue by quitegreensky** [kivymd/KivyMD#322]
### Description of the Bug

When i want to customize MDropDownMenu with `RightContent` and at the same time disable icon with `use_icon_item=False` the app crashes on start.

### Code and Logs
```
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu, RightContent

KV = '''
<RightContentCls>
    disabled: True

    MDIconButton:
        icon: root.icon
        user_font_size: "16sp"
        pos_hint: {"center_y": .5}

    MDLabel:
        text: root.text
        font_style: "Caption"
        size_hint_x: None
        width: self.texture_size[0]
        text_size: None, None


Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class RightContentCls(RightContent):
    pass


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [
            {
                "right_content_cls": RightContentCls(text=f"R+{i}", icon="apple-keyboard-command",),"icon": "git","text": f"Item {i}",
            }
            for i in range(5)
        ]
        self.menu = MDDropdownMenu(use_icon_item=False,
            caller=self.screen.ids.button, items=menu_items, width_mult=4
        )

    def build(self):
        return self.screen
Test().run()
```

Log:
```
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 
860, in kivy.properties.ObservableDict.__getattr__
 KeyError: '_right_container'

 During handling of the above exception, another exception occurred:    

 Traceback (most recent call last): 
   File "test.py", line 55, in <module>
     Test().run()
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 560, in 
runTouchApp
     EventLoop.mainloop()
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 334, in 
mainloop
     self.idle()
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 375, in 
idle
     Clock.tick()
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\clock.py", line 648, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\quite\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\clock.py", line 691, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick     
   File "E:\python\reminder\kivymd\uix\menu.py", line 655, in set_menu_properties
     self.create_menu_items()       
   File "E:\python\reminder\kivymd\uix\menu.py", line 642, in create_menu_items
     20
   File "kivy\properties.pyx", line 
863, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has 
no attribute '__getattr__'
```

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@quitegreensky Thanks for identifying the bug. I will fix this later.

**Comment by mp-007** [comment]
I don't know if it is a mistake but there's a IconLeftWidget in MDMenuItem.

![image](https://user-images.githubusercontent.com/19823482/82964918-b2aed580-9f94-11ea-8c98-e1523e47f3e1.png)

when you use "use_icon_item=False", you still have a blank Icon over the text.

**Comment by sanderland** [comment]
Also had this issue, along with the icon seemingly doing the opposite of the setting.
