### ISSUE TITLE
Permission denied on .kivy file while running on android

### ISSUE THREAD

**Issue by maciektr** [kivymd/KivyMD#356]
### Description of the Bug

I am getting  "[Errno 13] Permission denied: '/data/.kivy'" error while starting my app on android. 
Buildozer does not throw any errors. 

### Code and Logs
I am compiling my app with this spec file.
Buildozer.spec: https://gist.github.com/maciektr/30d083bb7c8c777f5accc65de3c566f4

After deployment to android phone I am getting this error. 
```python
2020-06-16 19:15:15.486 15290-15389/org.test.wiet_sourcing_app I/python: Run user program, change dir and execute entrypoint
2020-06-16 19:15:16.287 15290-15389/org.test.wiet_sourcing_app I/python:  Traceback (most recent call last):
2020-06-16 19:15:16.287 15290-15389/org.test.wiet_sourcing_app I/python:    File "/home/maciektr/Programowanie/package/WIET_sourcing_app/.buildozer/android/app/main.py", line 3, in <module>
2020-06-16 19:15:16.287 15290-15389/org.test.wiet_sourcing_app I/python:    File "/home/maciektr/Programowanie/package/WIET_sourcing_app/.buildozer/android/app/WIET_sourcing_app/app.py", line 6, in <module>
2020-06-16 19:15:16.288 15290-15389/org.test.wiet_sourcing_app I/python:    File "/home/maciektr/Programowanie/package/WIET_sourcing_app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/WIET_sourcing_app/kivy/__init__.py", line 351, in <module>
2020-06-16 19:15:16.288 15290-15389/org.test.wiet_sourcing_app I/python:  PermissionError: [Errno 13] Permission denied: '/data/.kivy'
2020-06-16 19:15:16.288 15290-15389/org.test.wiet_sourcing_app I/python: Python for android ended.
```

### Versions

* OS: Fedora 
* Python: 3.7.6
* Kivy: 2.0.0rc
* KivyMD: 0.104.1

**Comment by RobertFlatt** [comment]
This is a characteristic of Kivy 2.0.0rc2 unrelated to KivyMD

**Comment by maciektr** [comment]
Ok, thanks for info
