### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd'

### ISSUE THREAD

**Issue by gargsaar** [kivymd/KivyMD#367]
Hi, 

I'm new to kivy. Getting ModuleNotFoundError: No module named 'kivymd'.

```
sarthakgarg@gargsaar AgeTest % ls
bell.wav	kv		main.kv		main.py
sarthakgarg@gargsaar AgeTest % python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from kivymd.app import MDApp
ModuleNotFoundError: No module named 'kivymd'
```

Also, when I the build the app for ios using toochain and open it in a simulator in Xcode, it doesn't open and crashes in Xcode. 

Xcode Error:
```
2020-06-24 15:59:01.106168+0530 agetest[16245:646884] Running main.py: /Users/sarthakgarg/Library/Developer/CoreSimulator/Devices/.../agetest.app/YourApp/main.pyc
Traceback (most recent call last):
  File "/Users/sarthakgarg/Desktop/Repo/PYTHON/Kivy_Projects/BUILD/agetest-ios/YourApp/main.py", line 1, in <module>
ModuleNotFoundError: No module named 'kivymd'
2020-06-24 15:59:01.107667+0530 agetest[16245:646884] Application quit abnormally!
2020-06-24 15:59:01.111630+0530 agetest[16245:646884] Leaving
```

**Comment by HeaTTheatR** [comment]
@gargsaar The error text answers your question.

**Comment by ArtemSBulgakov** [comment]
@gargsaar You installed KivyMD as root using command `sudo pip install kivymd` and you try to run as user using `python main.py`. It is incorrect. You should always install packages as user `pip install kivymd`.

**Comment by gargsaar** [comment]
@ArtemSBulgakov thanks for your comment. Re-installed without sudo, still getting the same error.

For Ios Simulator crashing issue, i tried the workaround suggest at https://github.com/kivy/kivy-ios/issues/320 and followed the post https://github.com/HeaTTheatR/KivyMD/issues/276, still the same issue. 

Followed all the steps diligently, but not getting any headway. Pls suggest what else can i do.
