### ISSUE TITLE
Text field helper text on error

### ISSUE THREAD

**Issue by mathe1s** [kivymd/KivyMD#41]
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip': 'xclip'
  File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
  File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

[WARNING] [MDBottomNavigation] 50.0dp is less than the minimum size of 80dp for a MDBottomNavigationItem. We must now expand to 168dp.
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 838, in kivy.properties.ObservableDict.__getattr__ (/tmp/pip-install-lbzi7uqi/kivy/kivy/properties.c:12019)
 KeyError: 'text_field_error'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/matheus/PycharmProjects/KivyMD/demos/kitchen_sink/main.py", line 1059, in <module>
     KitchenSink().run()
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 662, in _mainloop
     self.modifiers):
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:7682)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13525)
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13051)
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 162, in _on_window_key_down
     return self.dispatch('on_key_down', keycode, text, modifiers)
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:7682)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13525)
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13051)
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/uix/textinput.py", line 2468, in keyboard_on_key_down
     self._key_down(key)
   File "/home/matheus/.virtualenvs/k37/lib/python3.6/site-packages/kivy/uix/textinput.py", line 2332, in _key_down
     self.dispatch('on_text_validate')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:7682)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13525)
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (/tmp/pip-install-lbzi7uqi/kivy/kivy/_event.c:13051)
   File "/home/matheus/PycharmProjects/KivyMD/demos/kitchen_sink/main.py", line 956, in set_error_message
     if len(self.root.ids.text_field_error.text) == 2:
   File "kivy/properties.pyx", line 841, in kivy.properties.ObservableDict.__getattr__ (/tmp/pip-install-lbzi7uqi/kivy/kivy/properties.c:12125)
 AttributeError: 'super' object has no attribute '__getattr__'

**Comment by HeaTTheatR** [comment]
```python
    def set_error_message(self, *args):
        """Checks text of TextField with type "on_error"
        for the screen TextFields."""

        text_field_error = args[0]
        if len(text_field_error.text) == 2:
            text_field_error.error = True
        else:
            text_field_error.error = False
```

I can’t push right now because I have many other changes in my local repository. Wait a couple of hours.
