### ISSUE TITLE
MDTabsBar.tab_bar_autoscroll() may reference unassigned local variable.

### ISSUE THREAD

**Issue by blep** [kivymd/KivyMD#420]
### Description of the Bug

I was playing just running the [tabs code example](https://kivymd.readthedocs.io/en/latest/components/tabs/index.html#example-with-tab-icon) from the doc.

It crashed with stack found in logs below after resizing to full screen and changing tabs multiple times.

Looking at the code around the crash, it is clear that `x` is never assigned if none of the condition is matched:
```python
        if scroll_is_late and target.center_x > bound_left:
            x = lsx + dst

        elif not scroll_is_late and target.center_x < bound_right:
            x = lsx - dst

        x = boundary(x, 0.0, 1.0)
```

### Code and Logs

```python
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.icon_definitions import md_icons

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: android_tabs
        on_tab_switch: app.on_tab_switch(*args)


<Tab>:

    MDIconButton:
        id: icon
        icon: app.icons[0]
        user_font_size: "48sp"
        pos_hint: {"center_x": .5, "center_y": .5}
'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    icons = list(md_icons.keys())[15:30]

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for name_tab in self.icons:
            self.root.ids.android_tabs.add_widget(Tab(text=name_tab))

    def on_tab_switch(
        self, instance_tabs, instance_tab, instance_tab_label, tab_text
    ):
        '''Called when switching tabs.

        :type instance_tabs: <kivymd.uix.tab.MDTabs object>;
        :param instance_tab: <__main__.Tab object>;
        :param instance_tab_label: <kivymd.uix.tab.MDTabsLabel object>;
        :param tab_text: text or name icon of tab;
        '''

        count_icon = [k for k, v in md_icons.items() if v == tab_text]
        instance_tab.ids.icon.icon = count_icon[0]


Example().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

**Logs**:
```
[INFO   ] [Logger      ] Record log in C:\Users\MyUser\.kivy\logs\kivy_20-07-24_27.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\wut\dev\anaconda3\envs\kivy-learning\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 442.59'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce RTX 2070 SUPER/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "E:/prj/kivy-learning/main_kivymd_tabs.py", line 59, in <module>
     Example().run()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\base.py", line 339, in idle
     Clock.tick()
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\clock.py", line 591, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\animation.py", line 346, in _update
     setattr(widget, key, value)
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 45, in <module>
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivymd\uix\tab.py", line 549, in android_animation
     self.tab_bar_autoscroll(b, step)
   File "C:\wut\dev\anaconda3\envs\kivy-learning\lib\site-packages\kivymd\uix\tab.py", line 518, in tab_bar_autoscroll
     x = boundary(x, 0.0, 1.0)
 UnboundLocalError: local variable 'x' referenced before assignment
```

## Versions

* OS: Windows 10
* Python: See log
* Kivy: See log
* KivyMD: See log

**Comment by HeaTTheatR** [comment]
@blep Yes, it's a bug.

**Comment by Matan22g** [comment]
> @blep Yes, it's a bug.

Is it going to be fixed? When?

**Comment by HeaTTheatR** [comment]
@Matan22g There are a lot of current tasks, so I can't say anything concrete.

**Comment by Matan22g** [comment]
![unknown-1](https://user-images.githubusercontent.com/64740256/92301091-3e0f0e00-ef69-11ea-9fd8-bfe00f432f6a.png)

Just add in line 858

else:
   x = lst + dst

I dont know if its the perfect solution, but it fixes the crashes. And allow users to build their apps from git without that sure chance for crash untill a better solution will be found

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/pull/768
