### ISSUE TITLE
MDFloatingActionButtonSpeedDial adding icon to main button results in Attribute error.

### ISSUE THREAD

**Issue by B1GHurley** [kivymd/KivyMD#423]
MDFloatingActionButtonSpeedDial adding icon to main button results in Attribute error.
documentation stated you can add icon to main class, when i do so it throws an attribute error.

Line 1653 in button.py ( Kivymd\uix\button.py ) 

self._get_count_widget(MDFloatingRootButton).icon = value 

that normaly returns its children for the generated buttons but this icon is meant for self so i think it should be:

self.icon = value

changing the above seems to work perfectly for me.

### Code and Logs

 Traceback (most recent call last):
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivymd\uix\button.py", line 1653, in on_icon
     self._get_count_widget(MDFloatingRootButton).icon = value
 AttributeError: 'NoneType' object has no attribute 'icon'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:/Data Tim/Applicaties/Dashboard/Dashboard.py", line 281, in <module>
     MainApp().run()
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "C:/Data Tim/Applicaties/Dashboard/Dashboard.py", line 277, in build
     return Builder.load_file("Dashboard.kv")
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 405, in load_string
     rule_children=rule_children)
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 657, in _apply_rule
     root=rctx['ids']['root'], rule_children=rule_children)
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 538, in apply
     rule_children=rule_children)
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "C:\Data Tim\Applicaties\Dashboard\Dashboard.kv", line 316:
 ...
     314:        MDFloatingActionButtonSpeedDial:
     315:            id: fab
 >>  316:            icon: 'menu'
     317:            data: app.data
     318:            rotation_root_button: True
 ...
 AttributeError: 'NoneType' object has no attribute 'icon'
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Data Tim\Applicaties\Dashboard\venv\lib\site-packages\kivymd\uix\button.py", line 1653, in on_icon
     self._get_count_widget(MDFloatingRootButton).icon = value

* OS: Win 10
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by podraco** [comment]
We still need a sample code to reproduce the error.

**Comment by APAutomatedDesign** [comment]
i use this in kv file.

```
MDFloatingActionButtonSpeedDial:
    on_kv_post: self.icon = 'icon/menu.png'
    data: app.lottomenu
    callback: app.floatLottoMenu
```

![Screenshot_20200905-104825.png](https://user-images.githubusercontent.com/60537950/92297069-7e6c8d00-ef65-11ea-9a08-e0a862f4ccad.png)

**Comment by podraco** [comment]
The button lib is currently in a major modification #501 let me check the speed dial for that specific bug

**Comment by HeaTTheatR** [comment]
Fix in the master branch.
