### ISSUE TITLE
[Bug]  TypeError: '<' not supported between instances of 'MDBoxLayout' and 'float'

### ISSUE THREAD

**Issue by lemousehunter** [kivymd/KivyMD#431]
### Description of the Bug

When adding widgets to an MDBoxLayout in .py, the error  `TypeError: '<' not supported between instances of 'MDBoxLayout' and 'float'` is raised.

### Code and Logs

**Code**

```
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.clock import Clock
from kivymd.app import MDApp

class Layout(MDBoxLayout):

    def __init__(self, **kwargs):
        super(Layout, self).__init__(**kwargs)
        self.b = MDBoxLayout(orientation='vertical')


if __name__ == '__main__':

    class App(MDApp):
        def build(self):
            b = MDBoxLayout()
            b.add_widget(Layout())
            return b

    App().run()
```
**Log**
```
 Traceback (most recent call last):
   File "C:/Users/User/PycharmProjects/New MO Inventory System/sigh.py", line 24, in <module>
     App().run()
   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "C:/Users/User/PycharmProjects/New MO Inventory System/sigh.py", line 21, in build
     b.add_widget(Layout())
   File "C:/Users/User/PycharmProjects/New MO Inventory System/sigh.py", line 9, in __init__
     self.b = MDBoxLayout(orientation='vertical')
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1176, in kivy.properties.BoundedNumericProperty.check
 TypeError: '<' not supported between instances of 'MDBoxLayout' and 'float'
```

### Versions

* OS: Windows 10
* Python: 3.8.3
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by lemousehunter** [comment]
A temporary workaround is to add widgets to it directly from .kv

**Comment by lemousehunter** [comment]
May I know why this issue is closed? I accidentally mentioned this issue instead of issue #426 , which I rectified in my edit.

**Comment by lemousehunter** [comment]
I think Github did not update the reference after I edited the PR. Could you please reopen this issue as it is not rectified? @HeaTTheatR

**Comment by HeaTTheatR** [comment]
@lemousehunter I did not close this issue.

**Comment by lemousehunter** [comment]
it says its closed tho... 😂

**Comment by podraco** [comment]
for what i see, the namespace `self.b` is already in use, if you change the name to almost anything else, works
This namespaces are currently in use, dont know there are used `a` and `b`.
```py
in[0]>>>:
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.properties import ObjectProperty
from kivy.clock import Clock
from kivymd.app import MDApp

class Layout(MDBoxLayout):
    # c=ObjectProperty()

    def __init__(self, **kwargs):
        super(Layout, self).__init__(**kwargs)
        for i in self.__dir__():
            print(i)
        # self.c = MDBoxLayout(orientation='vertical')


if __name__ == '__main__':

    class App(MDApp):
        def build(self):
            b = MDBoxLayout()
            b.add_widget(Layout())
            return b

    App().run()
```
```terminal
out[0]>>>:
b
a
radius
md_bg_color
```

**Comment by HeaTTheatR** [comment]
@lemousehunter Yes, you tried to use the declared names - https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/behaviors/backgroundcolorbehavior.py#L39
