### ISSUE TITLE
'kivy.graphics.context_instructions.BindTexture' object has no attribute 'children'

### ISSUE THREAD

**Issue by nitanmarcel** [kivymd/KivyMD#44]
I'm making an app for my phone and I noticed this strange error popping out. I removed almost everything of my code and is the error still comes back somehow unless I delete the GridLayout import.

main.kv

```
#:kivy 1.10.1

#:import MDTextField kivymd.textfields.MDTextFieldRect

GridLayout:
    cols: 1
    MDTextFieldRect:
        id: code_field
        multiline: True

    MDTextFieldRect:
        id: result_field
        multiline: True
        readonly: True
```

main.py:

```from kivy.app import App
from kivy.lang import Builder
import logging
from kivy.uix.gridlayout import GridLayout


logging.basicConfig(level=logging.DEBUG)

class RextesterApp(App):

    def build(self):
        return Builder.load_file("main.kv")
        #return self.root

if __name__ == "__main__":
    RextesterApp().run()
```

**Comment by nitanmarcel** [comment]
And here is the full log I forgot to paste:

```

➜ python main.py
[INFO   ] [Logger      ] Record log in /home/alexandrumarcel/.kivy/logs/kivy_19-04-26_89.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0]
[INFO   ] [Factory     ] 194 symbols loaded
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] KivyMD version: 0.97, 2
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event7
[INFO   ] [MTD         ] Read event from </dev/input/event7>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 16, in <module>
     RextesterApp().run()
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
     self._mainloop()
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/core/window/window_pygame.py", line 370, in _mainloop
     self.modifiers):
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 162, in _on_window_key_down
     return self.dispatch('on_key_down', keycode, text, modifiers)
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/uix/textinput.py", line 2459, in keyboard_on_key_down
     self.focus = False
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/home/alexandrumarcel/.local/lib/python3.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 89, in <module>
   File "/usr/local/lib/python3.7/dist-packages/kivymd/textfields.py", line 330, in anim_rect
     instance_line = root_canvas.children[2]
 AttributeError: 'kivy.graphics.context_instructions.BindTexture' object has no attribute 'children'
```

**Comment by HeaTTheatR** [comment]
@nitanmarcel 
![eee](https://user-images.githubusercontent.com/16930280/56784626-1c8d0680-67fa-11e9-96af-86b82cc790e5.gif)

**Comment by nitanmarcel** [comment]
@HeaTTheatR Strange. I don't understand why it doesn't work my PC or phone. Anything else I could provide to you so you could help me somehow?

**Comment by nitanmarcel** [comment]
@HeaTTheatR type 2 lines then press anywhere on the tab, or press esc

**Comment by nitanmarcel** [comment]
The crash happens when there are multiple lines and the text field goes out of focus

**Comment by nitanmarcel** [comment]
@HeaTTheatR something similar and it the same circumstances happens on my Android phone (the PC version is fine).

```
.
I/python  (28028): [INFO   ] [Logger      ] Record log in /data/user/0/demo.org.rextesterdroid/files/app/.kivy/logs/kivy_19-04-26_2.txt
I/python  (28028): [INFO   ] [Kivy        ] v1.11.0.dev0, git-Unknown, 20190425
I/python  (28028): [INFO   ] [Python      ] v3.7.1 (default, Apr 26 2019, 00:07:19) 
I/python  (28028): [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
I/python  (28028): [INFO   ] [Factory     ] 184 symbols loaded
I/python  (28028): [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
I/python  (28028): [INFO   ] [KivyMD      ] KivyMD version: 0.98.0
I/python  (28028): [INFO   ] [Window      ] Provider: sdl2
I/python  (28028): [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
I/python  (28028): [INFO   ] [GL          ] Backend used <sdl2>
I/python  (28028): [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@331.0 (GIT@2df12b3, I07da2d9908) (Date:10/04/18)'>
I/python  (28028): [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
I/python  (28028): [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 506'>
I/python  (28028): [INFO   ] [GL          ] OpenGL parsed version: 3, 2
I/python  (28028): [INFO   ] [GL          ] Texture max size <16384>
I/python  (28028): [INFO   ] [GL          ] Texture max units <16>
I/python  (28028): [INFO   ] [Window      ] auto add sdl2 input provider
I/python  (28028): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
I/python  (28028): [INFO   ] [Text        ] Provider: sdl2
I/python  (28028): [INFO   ] [GL          ] NPOT texture support is available
I/python  (28028): <kivymd.textfields.MDTextFieldRect object at 0x9ab09688>
I/python  (28028): [WARNING] [Base        ] Unknown <android> provider
I/python  (28028): [INFO   ] [Base        ] Start application main loop
I/python  (28028): [INFO   ] [Base        ] Leaving application in progress...
I/python  (28028):  Traceback (most recent call last):
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/app/main.py", line 157, in <module>
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/app.py", line 855, in run
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/base.py", line 502, in runTouchApp
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/core/window/window_sdl2.py", line 730, in mainloop
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/core/window/window_sdl2.py", line 465, in _mainloop
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/base.py", line 340, in idle
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/base.py", line 325, in dispatch_input
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/base.py", line 231, in post_dispatch_input
I/python  (28028):    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/core/window/__init__.py", line 1385, in on_motion
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/uix/behaviors/focus.py", line 459, in _handle_post_on_touch_up
I/python  (28028):    File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
I/python  (28028):    File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
I/python  (28028):    File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
I/python  (28028):    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
I/python  (28028):    File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivy/lang/builder.py", line 64, in custom_callback
I/python  (28028):    File "<string>", line 89, in <module>
I/python  (28028):    File "/home/alexandrumarcel/projects/kivy-apps/rextester/.buildozer/android/platform/build/build/python-installs/rextesterdroid/kivymd/textfields.py", line 328, in anim_rect
I/python  (28028):  AttributeError: 'kivy.graphics.context_instructions.BindTexture' object has no attribute 'children'
I/python  (28028): Python for android ended.
I/WindowManager( 9903): WIN DEATH: Window{25da5df u0 demo.org.rextesterdroid/org.kivy.android.PythonActivity}
W/ActivityManager( 9903): Force removing ActivityRecord{6ae9516 u0 demo.org.rextesterdroid/org.kivy.android.PythonActivity t1693}: app died, no saved state
```


What's different is that here I'm using a kv file to manage the layout:

```
<HomeScreen>:    
    name: "home"

    GridLayout:
        name: "main_grid"
        id: maingrid
        cols: 1

        MDToolbar:
            title: app.title
            md_bg_color: app.theme_cls.primary_color
            background_palette: "Primary"
            elevation: 10
            right_action_items: [['play', app.execute]]




        MDLabel:
            text: "Code:"
            size_hint: None, pt(.1)


        MDSeparator:

        MDTextFieldRect:
            id: code_field
            multiline: True
            pos_hint: {"center_x": .5}
            hint_text: "Enter your code here!"
            background_color: (0,0,0,0)

        MDLabel:
            text: "Result:"
            size_hint: None, pt(.1)

        MDSeparator:

        MDTextFieldRect:
            id: result_field
            multiline: True
            readonly: True
            pos_hint: {"center_x": .5}
            background_color: (0,0,0,0)
            color: "accent"
```

**Comment by HeaTTheatR** [comment]
@nitanmarcel KivyMD version: 0.98.1

**Comment by HeaTTheatR** [comment]
@nitanmarcel In your build on the phone, the old version 0.98.0

**Comment by nitanmarcel** [comment]
@HeaTTheatR hmm. Strange... Maybe there's something wrong with buildozer when cloning the repo

**Comment by HeaTTheatR** [comment]
@nitanmarcele Before new building your APK remove .buildozer directory.

**Comment by nitanmarcel** [comment]
@HeaTTheatR Thanks for your help :)

Any ideas how I can use the already cloned repo instead of making buildozer download it every time I build the APK?

**Comment by HeaTTheatR** [comment]
@nitanmarcel Add the library kivimd in the directory of your program and add to the path to it in sys.path
