### ISSUE TITLE
App crashes if You try to remove the current tab

### ISSUE THREAD

**Issue by p0lygun** [kivymd/KivyMD#484]
### Description of the Bug

if you have more than one tab and you try to remove the last tab which is also the current active tab 
the program crashes 

### Code and Logs

```from kivy.lang import Builder
from kivy.uix.scrollview import ScrollView

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs


<Tab>:

    MDList:

        MDBoxLayout:
            adaptive_height: True

            MDFlatButton:
                text: "ADD TAB"
                on_release: app.add_tab()

            MDFlatButton:
                text: "REMOVE LAST TAB"
                on_release: app.remove_tab()

            MDFlatButton:
                text: "GET TAB LIST"
                on_release: app.get_tab_list()
'''


class Tab(ScrollView, MDTabsBase):
    '''Class implementing content for a tab.'''


class Example(MDApp):
    index = 0

    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.add_tab()

    def get_tab_list(self):
        '''Prints a list of tab objects.'''

        print(self.root.ids.tabs.get_tab_list())

    def add_tab(self):
        self.index += 1
        self.root.ids.tabs.add_widget(Tab(text=f"{self.index} tab"))

    def remove_tab(self):
        self.index -= 1
        self.root.ids.tabs.remove_widget(
            self.root.ids.tabs.get_tab_list()[0]
        )


Example().run()
```
### Steps to reproduce errors

1. Run the code 
2. Add a few tabs
3. go to the last tab 
4. click in remove tab

Error:-
```
     return self.slides[self.index or 0]
 IndexError: list index out of range
``` 

### Versions

* OS: win 10
* Python: 3.7
* Kivy: 2.0
* KivyMD: master

**Comment by HeaTTheatR** [comment]
@p0lygun You have to control yourself what you remove, because the error does not occur on the library side, but in your code on line 64.

**Comment by podraco** [comment]
So far, the sample code works fine. the exception is spammed since the widget tries to remove a index outside the count of the parent's children widgets. (when there's no child.)

I believe that what @HeaTTheatR  tried to say was:

@p0lygun, you have to control what you remove from the widget, since the error doesn't occur on the kivymd library side, but instead, it does in your code. 
at line 64.

```py
def remove_tab(self):
        self.index -= 1
        self.root.ids.tabs.remove_widget(
            self.root.ids.tabs.get_tab_list()[0]
        )
```

**Comment by p0lygun** [comment]
@podraco 
Run the code 
Add new tab 
Go to last tab 
Try to remove it

**Comment by podraco** [comment]
This is the output after following those steps:
```py
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
 IndexError: list index out of range
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
```

Also, if you delete all the tabs in the container, MDTab works fine. But when you try to add a new tab, the MDTab throws an error.
Somewhere in MDTab a value changes to None instead of 0. And the error doesn't fix after that.
here's the output.
```py
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 143, in _get_index
     return self._index % len(self.slides)
 TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 143, in _get_index
     return self._index % len(self.slides)
 TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

Also, after deleting the last MDTab there shouldn't be any Screen left and yet there is the last one still on the layout...

@p0lygun. Next time you report an issue/bug, remember to add the steps to reproduce the error.

Preferably use the GitHub Markdown style  as a numbered step list
### Update
Tested the example code from the documentation and the same bug appears.
Output after deleting all tabs and then adding a new tab. it repeats for every new tab added.
```py
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 143, in _get_index
     return self._index % len(self.slides)
 TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 143, in _get_index
     return self._index % len(self.slides)
 TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

this is the output after adding new tabs, changing the tab to the latest and then removing it.
```py
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
 IndexError: list index out of range
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Program Files\Python37\lib\site-packages\kivy\uix\carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
 IndexError: list index out of range
```
Ideally the remove_widget must check what element is in screen and if coincides with the element that's going to be removed, change to the first or the next / prior one

**Comment by p0lygun** [comment]
Exactly
So it's a bug rht?

**Comment by podraco** [comment]
It probably is, but my hands are full at the moment to check that.

I would recommend you to take a look at the tab.py and try to check why the values turn to None instead of Zero or a less than zero value, and doesn't change back to a numeric counter after the error.

Whatever you find, please post it in here to discuss a solution. And a proper way to fix it.

Also remember to use a passive voice when writing, this will avoid any misunderstanding between the way people take in different countries and regions. Since some people would think you're attacking them and not discussing an idea or proposing a solution.

**Comment by p0lygun** [comment]
Ok

**Comment by podraco** [comment]
seems that the exception raises before any kind of update on the tab container happens
![image](https://user-images.githubusercontent.com/5509325/91005849-83146700-e59d-11ea-9ed7-aafcd9d2a14e.png)

**Comment by podraco** [comment]
Here's one problem.
```py
    def remove_widget(self, widget):
        # You can remove only subclass of MDTabsLabel.
        if not issubclass(widget.__class__, MDTabsLabel):
            raise MDTabsException(
                "MDTabs can remove only subclass of MDTabsLabel"
            )
        self.tab_bar.layout.remove_widget(widget)
        for tab in self.carousel.slides:
            if tab.text == widget.text:
                self.carousel.slides.remove(tab)
                break
```

This doesn't check if the widget has any child before trying to remove it.
or if the widget exists inside it.

Since it's not a repetitive event, the available resource consumption is moderated, so this verification might be a good addition.

**Comment by HeaTTheatR** [comment]
@p0lygun If you found an error, you had to show the algorithm for reproducing the error. And so we just closed your question because we could not get what you described here.

**Comment by p0lygun** [comment]
sorry I actually forgot to add the steps to reproduce the error
