### ISSUE TITLE
MDDatePicker ValueError

### ISSUE THREAD

**Issue by kschlodder** [kivymd/KivyMD#498]
### Description of the Bug

I keep getting an error trying to select a date in that spans into the next month.
valueerror: day is out of range for month
This specific dates i was trying to select was 2nd april while the default date (that days date) was march 31st.

### Code and Logs

```python
   
# -*- coding: utf-8 -*-

import gettext
import kivy
import kivymd

_ = gettext.gettext

from kivy.lang import Builder
from kivy.factory import Factory
from kivy.properties import ObjectProperty
from kivymd.app import MDApp
from kivymd.uix.picker import MDDatePicker

kv = """

<SimpleIconButtonTooltips@MDIconButton+MDTooltip>

<Pickers@Screen>
    name: "pickers"
    tf_date_1: tf_date_1.__self__
    tf_date_2: tf_date_2.__self__

    BoxLayout:
        orientation: "vertical"
        spacing: dp(20)
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint_y: None
        height: self.minimum_height
        
        MDTextField:
            id: tf_date_1
            hint_text: 'Date 1'
            size_hint: None, None
            size: dp(48)*4, dp(48)
            pos_hint: {'center_x': .5, 'center_y': .5}
            multiline: False

        SimpleIconButtonTooltips:
            icon: 'calendar'
            tooltip_text: 'Open date picker'
            size_hint: None, None
            size: 1* dp(48), dp(48)
            pos_hint: {'center_x': .5, 'center_y': .5}
            #opposite_colors: True
            elevation_normal: 2
            on_release:
                app.show_date_picker_1()
                
        MDTextField:
            id: tf_date_2
            hint_text: 'Date 2'
            size_hint: None, None
            size: dp(48)*4, dp(48)
            pos_hint: {'center_x': .5, 'center_y': .5}
            multiline: False

        SimpleIconButtonTooltips:
            icon: 'calendar'
            tooltip_text: 'Open date picker'
            size_hint: None, None
            size: 1* dp(48), dp(48)
            pos_hint: {'center_x': .5, 'center_y': .5}
            #opposite_colors: True
            elevation_normal: 2
            on_release:
                app.show_date_picker_2()

"""


class MainApp(MDApp):
    tf_date_1 = ObjectProperty(None)
    tf_date_2 = ObjectProperty(None)

    def __init__(self, **kwargs):
        self.title = "KivyMD Examples - Date Picker"
        super().__init__(**kwargs)
        self.date_1 = None
        self.date_2 = None

    def build(self):
        Builder.load_string(kv)
        self.root = Factory.Pickers()

    def set_date_1(self, date_obj):
        """
        Sets the start date / display of the start date in the user interface.

        :type date_obj: <class 'datetime.date'>
        :return:
        """
        self.date_1 = date_obj
        self.root.ids.tf_date_1.text = str(date_obj.strftime("%d.%m.%Y"))

    def show_date_picker_1(self):
        """
        Open date dialog.
        :return: void
        """

        MDDatePicker(self.set_date_1, year=2020, month=8, day=31,).open()

    def set_date_2(self, date_obj):
        """
        Sets the start date / display of the start date in the user interface.

        :type date_obj: <class 'datetime.date'>
        :return:
        """
        self.date_2 = date_obj
        self.root.ids.tf_date_2.text = str(date_obj.strftime("%d.%m.%Y"))

    def show_date_picker_2(self):
        """
        Open date dialog.
        :return: void
        """
        MDDatePicker(self.set_date_2).open()


if __name__ == "__main__":
    MainApp().run()

```
### Logs

Traceback (most recent call last):
   File "../venv/lib/python3.7/site-packages/kivy/base.py", line 573, in runTouchApp
     EventLoop.mainloop()
   File "../venv/lib/python3.7/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "../venv/lib/python3.7/site-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "../venv/lib/python3.7/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "../venv/lib/python3.7/site-packages/kivy/base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "../venv/lib/python3.7/site-packages/kivymd/uix/behaviors/ripplebehavior.py", line 294, in on_touch_up
     return super().on_touch_up(touch)
   File "../venv/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "../venv/lib/python3.7/site-packages/kivymd/uix/picker.py", line 434, in on_release
     self.owner.set_selected_widget(self)
   File "../venv/lib/python3.7/site-packages/kivymd/uix/picker.py", line 539, in set_selected_widget
     self.sel_month = int(self.month)
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
   File "../venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 66, in call_fn
     e_value = eval(value, idmap)
   File "<string>", line 45, in <module>
   File "../venv/lib/python3.7/site-packages/kivymd/uix/picker.py", line 497, in fmt_lbl_date
     d = datetime.date(int(year), int(month), int(day))
 ValueError: day is out of range for month

### Versions

* OS: 
* Python: 3.7
* Kivy: 2.0.0rc2
* KivyMD: master

### Solution
```python
   
def fmt_lbl_date(self, year, month, day, orientation):
        try:
            d = datetime.date(int(year), int(month), int(day))
        except ValueError:
            d = datetime.date(year, month, 1)
        separator = "\n" if orientation == "landscape" else " "
        return (
            d.strftime("%a,").capitalize()
            + separator
            + d.strftime("%b").capitalize()
            + " "
            + str(day).lstrip("0")
        )
```

**Comment by HeaTTheatR** [comment]
@kschlodder Attach a minimal code that can be run without additional manipulation and reproduce the error you are writing about. A chunk of your code is just taken out of context ...

**Comment by kschlodder** [comment]
same issue - https://gitlab.com/kivymd/KivyMD/-/issues/133

but I use 2 datepicker in the screen, I write reduce code example...

**Comment by podraco** [comment]
@kschlodder, we need a minimmum runnable app to know what are you talking about.
Please change the bug desctiption like this

### Code and Logs
description of the procedure to repeat this error.

#### Test App
```py
use pyfor python code
Codeblock
```
```yaml
use yaml for kivy code
Codeblock
```

#### Logs
```
XXX LOG XXXX
```

#### Conclusion / annotations / observations
here you should add the observations you took of the bug
the titles are not required but helps to understand what happened in a ordered way.
if they affect multiple files, add the filename and path to every codeblock you use.

#### Images and other resources (links etc.)

**Comment by kschlodder** [comment]
I add a minimum runable app.

**Comment by HeaTTheatR** [comment]
@kschlodder Everything works fine.

**Comment by kschlodder** [comment]
@HeaTTheatR do you have any idea. how can i fix the error?

**Comment by podraco** [comment]
the test app does not have the fmt_lbl_date
may i ask you where did it went? or where did you got it from?

**Comment by podraco** [comment]
i can say, there's a bug, 

#### step to reproduce:
1. have any month with 31 days in screen 
1. select day 31 of the actual month
1. change to any month with 30 or less days
1. select any other day
1. the app crash
LOG
```
Traceback (most recent call last):
  File "$USER$AppData\Local\Temp\atom_script_tempfiles\3bf0d970-ec6a-11ea-8b1f-df0af66b92c8", line 230, in <module>
    MainApp().run()
  File "C:\Program Files\Python37\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "C:\Program Files\Python37\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\Program Files\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "C:\Program Files\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "C:\Program Files\Python37\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\Program Files\Python37\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\Program Files\Python37\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Program Files\Python37\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 294, in on_touch_up
    return super().on_touch_up(touch)
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Program Files\Python37\lib\site-packages\kivymd\uix\picker.py", line 434, in on_release
    self.owner.set_selected_widget(self)
  File "C:\Program Files\Python37\lib\site-packages\kivymd\uix\picker.py", line 539, in set_selected_widget
    self.sel_month = int(self.month)
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Program Files\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 45, in <module>
  File "C:\Program Files\Python37\lib\site-packages\kivymd\uix\picker.py", line 497, in fmt_lbl_date
    d = datetime.date(int(year), int(month), int(day))
ValueError: day is out of range for month
```
For the behavior I would say it's because it evaluates the max days of the actual month before updating the selected (cursor) number of the date. Therefore, this will happen to any 30 day month to February
![OlEmBU7r6E](https://user-images.githubusercontent.com/5509325/91875790-97153400-ec41-11ea-89dc-d989f4cbe5ab.gif)

**Comment by kschlodder** [comment]
https://github.com/kivymd/KivyMD/commit/d54be8f6b1930887b448d5a40a00477cb4d26412

**Comment by podraco** [comment]
@kschlodder  what happened to your fix? i don't see any pull request nor the commit in the master branch, did something happened?

**Comment by kschlodder** [comment]
Can anybody test/control my solution? Please.

**Comment by kulothunganug** [comment]
I also find a tooltip bug when using the author (@kschlodder)  code
the tooltip shows when the picker is on open

![ttip](https://user-images.githubusercontent.com/63696279/96329044-da4b2b00-1066-11eb-8270-2eb88fdbed1d.gif)

**Comment by HeaTTheatR** [comment]
@kschlodder Create a new issue for this bug.

**Comment by kulothunganug** [comment]
i think that this error is not on the picker
It's due to this the picker icon button

**Comment by kulothunganug** [comment]
> i think that this error is not on the picker
> It's due to this the picker icon button

when i updated kivymd master
i can't reproduce the error

but tooltip shows

**Comment by podraco** [comment]
This bug it's still present.

**Comment by HeaTTheatR** [comment]
I am closing this issue because it does not meet the requirements of the new MDDatePicker API. You can fix the sample code that reproduces this bug and open a new issue if this error persists.

**Comment by podraco** [comment]
already fixed, i'm making another pull request.
