### ISSUE TITLE
kivymd MDDropdownMenu error 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#505]
### Description of the Bug

Your text
1st 
on_release not calling callback method

 
2nd case when we click menu items during the menu opening it crashes ....to see this increase menu opening animation time and click on menu item..

### Code and Logs

```python
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/scrollview.py", line 594, in _update_effect_bounds
     self._update_effect_y_bounds()
   File "/usr/lib/python3/dist-packages/kivy/uix/scrollview.py", line 586, in _update_effect_y_bounds
     self.effect_y.value = self.effect_y.min * self.scroll_y
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/effects/dampedscroll.py", line 104, in on_value
     self.scroll = self.value
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/scrollview.py", line 622, in _update_effect_y
     self.scroll_y = -sy
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy/properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy/properties.pyx", line 1510, in kivy.properties.AliasProperty.trigger_change
   File "kivy/properties.pyx", line 1537, in kivy.properties.AliasProperty.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/lang/builder.py", line 71, in call_fn
     element, key, value, rule.value))
   File "kivy/weakproxy.pyx", line 299, in kivy.weakproxy.WeakProxy.__str__
 RecursionError: maximum recursion depth exceeded while getting the str of an object
```

```python


from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu

KV = '''
Screen:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: app.menu.open()
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.screen.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)

    def build(self):
        return self.screen


Test().run()














```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: kubuntu 18.04
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Sahil-pixel 

1.  Update KivyMD library from master branch (0.104.1-dev0)

2. This may be a bug, but I was unable to click on the menu item while opening.

**Comment by podraco** [comment]
the sample code works fine for me
![1OSIX5YrWj](https://user-images.githubusercontent.com/5509325/92241264-910e9580-ee83-11ea-81dd-990d0909db92.gif)
"1st
on_release not calling callback method"
about the second step, it might be a bug, might be related to the animation or the size of the buttons, i'm not sure

**Comment by Sahil-pixel** [comment]
def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)

when ..i press an item ..it is not calling menu_callback because it not printing anything in console.
how to install kivymd version 0.104.1-dev0 ?

**Comment by Sahil-pixel** [comment]
done...  1st part is okk in master branch but 2nd part shows error put   opening_time=5 and press menu item before openning fully.

**Comment by Sahil-pixel** [comment]
but in developement version there is new problem ...button icon not appearing and app is not responsive .
i have installed via this .
pip install https://github.com/kivymd/KivyMD/archive/master.zip

**Comment by HeaTTheatR** [comment]
> but in developement version there is new problem ...button icon not appearing and app is not responsive .
i have installed via this .

What do you mean?

**Comment by Sahil-pixel** [comment]
i have another app where i have used some icons ..when i used kivymd 0.104.1 icons are appearing ...but when i have used 0.104.2.dev0  there are no icons .....

**Comment by HeaTTheatR** [comment]
@Sahil-pixel The available icon names can be found here - https://github.com/kivymd/KivyMD/blob/master/kivymd/icon_definitions.py

**Comment by mp-007** [comment]
> done... 1st part is okk in master branch but 2nd part shows error put opening_time=5 and press menu item before opening fully.

I had the same problem and I set the opening_time to 0 to avoid the error.

**Comment by Sahil-pixel** [comment]
![Screenshot_20200911_215354](https://user-images.githubusercontent.com/57060638/92950045-b13ce680-f479-11ea-88c5-96579044e108.png)
KivyMD: 0.104.1

**Comment by Sahil-pixel** [comment]
![Screenshot_20200911_215459](https://user-images.githubusercontent.com/57060638/92950202-eba68380-f479-11ea-8090-5500ab6d2c5b.png)
kivymd master version 0.104.2.dev0,  ...see tab icon ...i have run same code ...

**Comment by podraco** [comment]
This bug report has no start nor end, 

I may ask you to reformulate the report to know exactly what are you talking about

### Until then, this thread will be closed.
