### ISSUE TITLE
Crash on creating disabled MDSwitch

### ISSUE THREAD

**Issue by gbm001** [kivymd/KivyMD#51]
Creating an MDSwitch which is initially set ```disabled: True``` (in Kivy language) leads to a crash:

```AttributeError: 'MDSwitch' object has no attribute 'thumb_color_disabled'```

This is because in selectioncontrols.py:

    Thumb:
        id: thumb
        size_hint: None, None
        size: dp(24), dp(24)
        pos: root._thumb_pos
        color:
            root.thumb_color_disabled if root.disabled else\
            (root.thumb_color_down if root.active else root.thumb_color)
        elevation:    4 if root.active else 2
        on_release: setattr(root, 'active', not root.active)

root.thumb_color_disabled is not initialized when the MDSwitch is first created.
I have worked around in my MDSwitch subclasses with:

    from kivy.utils import get_color_from_hex
    from kivymd.color_definitions import colors
    class MyMDSwitch(MDSwitch):
        def __init__(self, **kwargs):
            self.thumb_color_disabled = get_color_from_hex(colors['Gray']['400'])
            super().__init__(**kwargs)

**Comment by HeaTTheatR** [comment]
@gbm001 This error does not play on my computer. Give a minimal example that reproduces this problem.

**Comment by gbm001** [comment]
testapp.py:
(if I don't add the ThemeManager bit it crashes with a different error)

```
import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivymd.theming import ThemeManager

class TestAppBase(BoxLayout):
    pass

class TestApp(App):

    # KivyMD theme
    theme_cls = ThemeManager()

    def build(self):
        self.base = TestAppBase()
        return self.base  # Root widget

TestApp().run()
```

testapp.kv:
```
#:kivy 1.11.0

#:import MDSwitch kivymd.selectioncontrols.MDSwitch

<TestAppBase>:
    MDSwitch:
        disabled: True
```

Crashes with:
```
 Traceback (most recent call last):
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 619, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1468, in kivy.properties.AliasProperty.set
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 1331, in set_disabled
     self.inc_disabled()
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 1339, in inc_disabled
     self.property('disabled').dispatch(self)
   File "kivy/properties.pyx", line 1472, in kivy.properties.AliasProperty.dispatch
   File "kivy/properties.pyx", line 1474, in kivy.properties.AliasProperty.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 73, in call_fn
     e_value = eval(value, idmap)
   File "<string>", line 55, in <module>
   File "kivy/weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__
 AttributeError: 'MDSwitch' object has no attribute 'thumb_color_disabled'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "./testapp.py", line 18, in <module>
     TestApp().run()
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "./testapp.py", line 15, in build
     self.base = TestAppBase()
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/boxlayout.py", line 131, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 348, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 469, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 630, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "/home/amcleod/android/tests/testapp.kv", line 7:
 ...
       5:<TestAppBase>:
       6:    MDSwitch:
 >>    7:        disabled: True
 ...
 AttributeError: 'MDSwitch' object has no attribute 'thumb_color_disabled'
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 619, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1468, in kivy.properties.AliasProperty.set
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 1331, in set_disabled
     self.inc_disabled()
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 1339, in inc_disabled
     self.property('disabled').dispatch(self)
   File "kivy/properties.pyx", line 1472, in kivy.properties.AliasProperty.dispatch
   File "kivy/properties.pyx", line 1474, in kivy.properties.AliasProperty.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/home/amcleod/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 73, in call_fn
     e_value = eval(value, idmap)
   File "<string>", line 55, in <module>
   File "kivy/weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__
```

**Comment by gbm001** [comment]
Fixed for me as well; thanks :)
