### ISSUE TITLE
MDDropdownMenu not working when using in Screen (class)

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#511]
### Description of the Bug

when i use dropdownmenu in a Screen class it showing attribute error
but working nicely when using in MDApp

### Code

main.py
```python
from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.screen import Screen


class BuildApp(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)


class MainApp(MDApp):
    pass


MainApp().run()
```

main.kv
```
<BuildApp>:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.menu.open()

BuildApp:
```

### Logs
```
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_20-09-07_12.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.7/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2020-09-07 (installed at "/usr/local/lib/python3.7/dist-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.3.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 860, in kivy.properties.ObservableDict.__getattr__
 KeyError: 'button'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/root/chat-apps/__pycache__/m.py", line 25, in <module>
     MainApp().run()
   File "/usr/local/lib/python3.7/dist-packages/kivy/app.py", line 828, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/local/lib/python3.7/dist-packages/kivy/app.py", line 599, in load_kv
     root = Builder.load_file(rfilename)
   File "/usr/local/lib/python3.7/dist-packages/kivy/lang/builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/kivy/lang/builder.py", line 399, in load_string
     widget = Factory.get(parser.root.name)(__no_builder=True)
   File "/root/chat-apps/__pycache__/m.py", line 11, in __init__
     caller=self.ids.button,
   File "kivy/properties.pyx", line 863, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'
```

### Versions

* OS: Debian 10
* Python: v3.7.3
* Kivy: v1.11.1
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
@Kulothungan16 
```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivymd.uix.screen import Screen


Builder.load_string(
    """
<BuildApp>:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.menu.open()
""")


class BuildApp(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)

    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)


class MainApp(MDApp):
    def build(self):
        return BuildApp()


MainApp().run()
```

Never use an application architecture where the KV file is automatically searched for in the home directory. This is a very bad practice. I am closing your question because it is not related to the KivyMD library. In the code that I attached above, you can see that your code works fine.

**Comment by kulothunganug** [comment]
if i use more screens what i want to do
pls illustrate with example... 🙏🏽

**Comment by kulothunganug** [comment]
i had fixed my problem 😊
```py
from kivymd.app import MDApp
from kivymd.uix.menu import MDDropdownMenu
from kivy.lang import Builder
from kivy.clock import Clock
from kivymd.uix.screen import Screen


KV = """
<BuildApp>:

    MDRaisedButton:
        id: button
        text: "PRESS ME"
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.menu.open()

BuildApp:
"""

class BuildApp(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Clock.schedule_once(self._late_init)

    def _late_init(self, interval):
        menu_items = [{"text": f"Item {i}"} for i in range(5)]
        self.menu = MDDropdownMenu(
            caller=self.ids.button,
            items=menu_items,
            width_mult=4,
        )
        self.menu.bind(on_release=self.menu_callback)



    def menu_callback(self, instance_menu, instance_menu_item):
        print(instance_menu, instance_menu_item)


class MainApp(MDApp):
    def build(self):
    	self.root = Builder.load_string(KV)


MainApp().run()
```

**Comment by kirthigakalyan** [comment]
@HeaTTheatR But instead of maintaining as load_string I am maintaining its as .kv file seperately. In that case im calling builder method in my new screen .py file.?


MyKv.kv:

<Create@MDBoxLayout>:
    id: crt_odr
    MDLabel:
        text: "Type"
        halign: "left"
    MDDropDownItem:
        id: menu_itms
        pos_hint:{'center_x':0.5, 'center_y':0.5}
        text: 'Select any one'
        on_release: app.menu_list.open()


MyKv.py:
Builder.load_file("MyKv.kv")

class MyKv(Screen):
      
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

      list_items = ["A", "B", "C"]
        menu_list =[{"text": drop_itm,
                     "viewclass": "OneLineListItem",
                     "on_release": lambda x=drop_itm: self.menu_callback(x)
                    } for drop_itm in list_items
                   ]
        self.menu_list = MDDropdownMenu(caller=self.ids.menu_itms,items=menu_list, position='center', width_mult=4)

    def menu_callback(self, itm):
        self.ids.menu_itms.set_item(itm)
        self.ids.menu_itms.dismiss()


Its showing same error : AttributeError: 'super' object has no attribute '__getattr__'

Please help.
