### ISSUE TITLE
kitchen sink crash: No module named 'demo_apps.swipecards'

### ISSUE THREAD

**Issue by gbm001** [kivymd/KivyMD#52]
Running the kitchen sink demo (main.py) crashes:

Traceback (most recent call last):
   File "./main.py", line 30, in <module>
     from screens import Screens
   File "/home/amcleod/android/KivyMD/demos/kitchen_sink/screens.py", line 22, in <module>
     from demo_apps.swipecards import screen_swipe_cards, SwipeCards
 ModuleNotFoundError: No module named 'demo_apps.swipecards'

There is no 'swipecards.py' file in demo_apps.

**Comment by gbm001** [comment]
Thanks :)
