### ISSUE TITLE
navigation rail add to factory_registers

### ISSUE THREAD

**Issue by kulothunganug** [kivymd/KivyMD#600]
### Description of the Bug

when using MDNavigationRail gives this error
```
 Traceback (most recent call last):
   File "main.py", line 66, in <module>
     Test().run()
   File "/usr/local/lib/python3.7/dist-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/usr/local/lib/python3.7/dist-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "main.py", line 57, in build
     return Builder.load_string(KV)
   File "/usr/local/lib/python3.7/dist-packages/kivy/lang/builder.py", line 410, in load_string
     rule_children=rule_children)
   File "/usr/local/lib/python3.7/dist-packages/kivy/lang/builder.py", line 664, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "/usr/local/lib/python3.7/dist-packages/kivy/lang/builder.py", line 621, in _apply_rule
     cls = Factory_get(cname)
   File "/usr/local/lib/python3.7/dist-packages/kivy/factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <MDNavigationRail>
```

### Versions

* OS: Debain 10
* Python: v3.7.3
* Kivy: v2.0.0rc4, git-d74461b, 20201015
* KivyMD: 0.104.2.dev0, git-Unknown, 2020-10-22

**Comment by HeaTTheatR** [comment]
Fix https://github.com/kivymd/KivyMD/commit/b91caaeb813b8d65cf302c0780ce3210a59ca9dc
