### ISSUE TITLE
MDScreen encounters  KeyError  if you define a variable named either 'a' or 'b'

### ISSUE THREAD

**Issue by DaedlyKitten** [kivymd/KivyMD#646]
### Description of the Bug

MDScreen encounters  KeyError  if you defines a property named either 'a' or 'b'
change it to anything else and it runs normally

 Traceback (most recent call last):
   File "D:\1\test.py", line 28, in <module>
     test().run()
   File "D:\2\Python37\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "D:\2\Python37\lib\site-packages\kivy\app.py", line 944, in _run_prepare
     self.dispatch('on_start')
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\1\test.py", line 27, in on_start
     self.root.ids.sm.add_widget(aaa())
   File "kivy\_event.pyx", line 195, in kivy._event.EventDispatcher.__cinit__
   File "kivy\properties.pyx", line 1317, in kivy.properties.ReferenceListProperty.link_deps
   File "kivy\properties.pyx", line 465, in kivy.properties.Property.fbind
 KeyError: 'a'

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder 
from kivymd.uix.screen import MDScreen
kv=''' 
MDScreen:
    ScreenManager: 
        id:sm 
<aaa>:
    MDLabel:
        text:'aaa'
'''

class aaa(MDScreen):
    a='something'
    
class test(MDApp):
    def build(self):
        return Builder.load_string(kv) 

    def on_start(self):
        self.root.ids.sm.add_widget(aaa())
test().run()
```

### Versions

* OS: Win10 
* Python: v3.7.6
* Kivy: v2.0.0rc4
* KivyMD:  v0.104.1

**Comment by kulothunganug** [comment]
it's a default variable on `MDScreen` which is used for changing colors `rgba` example code below
```py
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivy.properties import NumericProperty

kv = """ 
MDScreen:
    ScreenManager: 
        id:sm 
<aaa>:
    MDLabel:
        text:'aaa'
"""


class aaa(MDScreen):
	r = NumericProperty(1) # to produce red color on the screen
	g = NumericProperty(0)
	b = NumericProperty(0)
	a = NumericProperty(1)


class test(MDApp):
    def build(self):
        return Builder.load_string(kv)

    def on_start(self):
        self.root.ids.sm.add_widget(aaa())


test().run()

```
