### ISSUE TITLE
Bug : CircularTimePicker with PyInstaller

### ISSUE THREAD

**Issue by JulienGervai** [kivymd/KivyMD#656]
### Description of the Bug

After using PyInstaller to make a .exe file. If in my .py I have :

from kivymd.uix.picker import MDDatePicker
date_dialog = MDDatePicker(callback=self.get_date)
date_dialog.open()

or in my .kv I got : 
#:import MDDatePicker kivymd.uix.picker

I will got the error : 

 Traceback (most recent call last):
   File "mails_ACTA_GUI.py", line 17, in <module>
     from kivymd.uix.picker import MDDatePicker
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "C:\Users\A486972\Miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
     exec(bytecode, module.__dict__)
   File "site-packages\kivymd\uix\picker.py", line 632, in <module>
   File "site-packages\kivy\lang\builder.py", line 368, in load_string
   File "site-packages\kivy\lang\parser.py", line 401, in __init__
   File "site-packages\kivy\lang\parser.py", line 507, in parse
   File "site-packages\kivy\lang\parser.py", line 482, in execute_directives
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 2:
 ...
       1:
 >>    2:#:import CircularTimePicker kivymd.vendor.circularTimePicker.CircularTimePicker
       3:#:import dp kivy.metrics.dp
       4:
 ...
 Unable to import package 'kivymd.vendor.circularTimePicker.CircularTimePicker'
[4360] Failed to execute script mails_ACTA_GUI

* OS: Windows 10
* Python: 3.8.3
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by Jensen96** [comment]
@JulienGervai 

I had the same issue and fixed it by adding 'kivymd.vendor.circularTimePicker' to my hiddenimports. 

Also ensure that all your paths are wrapped like this: "os.path.abspath('path-as-string-here')"

Edit: The last step of course requires you to add "import os" to your spec file aswell.

**Comment by JulienGervai** [comment]
Thanks I personnaly did manage to solve this problem by editing the file picker.py and by commenting from line 631 to 736 because I didn't have utility of CircularTimePicker, but your solution is way better.
