### ISSUE TITLE
Не работает код из вики

### ISSUE THREAD

**Issue by breitburg** [kivymd/KivyMD#67]
Запустил код [отсюда](https://github.com/HeaTTheatR/KivyMD/wiki/Bottom-Navigation) и возникла следующая ошибка:

```
Traceback (most recent call last):
   File "/Users/User/PycharmProjects/mobileapp/main.py", line 71, in <module>
     Example().run()
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/app.py", line 829, in run
     root = self.build()
   File "/Users/User/PycharmProjects/mobileapp/main.py", line 68, in build
     return Builder.load_string(KV)
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/lang/builder.py", line 368, in load_string
     parser = Parser(content=string, filename=fn)
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/lang/parser.py", line 401, in __init__
     self.parse(content)
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/lang/parser.py", line 507, in parse
     self.execute_directives()
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kivy/lang/parser.py", line 476, in execute_directives
     mod = getattr(mod, part)
 AttributeError: module 'kivymd.tabs' has no attribute 'MDBottomNavigation'
```

**Comment by HeaTTheatR** [comment]
@ketsu8
```python
#:import MDBottomNavigation kivymd.bottomnavigation.MDBottomNavigation

```
