### ISSUE TITLE
Kivy inspector crash: Window is None

### ISSUE THREAD

**Issue by PositivPy** [kivymd/KivyMD#719]
The kivy inspector crashes when using an MDApp; 
This is the official example from the [module's documentation;](https://kivy.org/doc/stable/api-kivy.modules.inspector.html)

#### Code
```
# inspector_test.py

from kivymd.app import MDApp as App
from kivy.lang import Builder

from kivy.core.window import Window
from kivy.uix.button import Button
from kivy.modules import inspector

class Demo(App):
    def build(self):
        button = Button(text="Test")
        inspector.create_inspector(Window, button)
        return button

Demo().run()
```
#### Command 
``` 
python3 inspector_test.py -m inspector
```
#### Error 
```
 Traceback (most recent call last):
   File "inspector_test.py", line 14, in <module>
     Demo().run()
   File "./../.local/lib/python3.7/site-packages/kivymd/app.py", line 91, in __init__
     self.theme_cls = ThemeManager()
   File "/.../.local/lib/python3.7/site-packages/kivymd/theming.py", line 865, in __init__
     self._determine_device_orientation(None, Window.size)
 AttributeError: 'NoneType' object has no attribute 'size'

```

**Comment by runette** [comment]
If you are using kivy 2.0 - the you probably have this problem that is related to kivy and not kivyMD

https://github.com/kivy/kivy/issues/7214

Until the fix is rolled out - you have to start the inspector in python rather than from the command line

**Comment by door3010** [comment]
Has anyone solved this problem?
