### ISSUE TITLE
TypeError when creating MDTextField outside of .kv file

### ISSUE THREAD

**Issue by allerter** [kivymd/KivyMD#752]
### Description of the Bug

Whenever I create an `MDTextField` outside of the .kv file, it results in `TypeError: 'NoneType' object is not iterable`.  This didn't happen with the pip version (0.104.1).

### Example Code

```python

from kivymd.app import MDApp
from kivymd.uix.gridlayout import GridLayout
from kivymd.uix.textfield import MDTextField


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.grid = GridLayout()
        self.grid.add_widget(MDTextField())

    def build(self):
        return self.grid


app = Test()
app.run()

```

### Logs
<details><summary>CLICK ME</summary>
<p>

```
[INFO   ] [Logger      ] Record log in C:\Users\Allerter\.kivy\logs\kivy_21-01-05_209.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Allerter\Desktop\Python\mrs_env\Scripts\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-01-05 (installed at "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Image       ] Providers: img_sdl2 (img_tex, img_dds, img_ffpyplayer, img_pil ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 391.35'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 440/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 2 images
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_shadow-1.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_shadow-1.png>
[INFO   ] [GL          ] NPOT texture support is available
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_shadow-0.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_shadow-0.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-0.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-0.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-1.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-1.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-2.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\rec_st_shadow-2.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-1.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-1.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-0.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-0.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-2.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\quad_shadow-2.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-1.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-1.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-0.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-0.png>
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-2.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\images\round_shadow-2.png>
[DEBUG  ] [Resource    ] add <C:\Windows\Fonts> in path list
[DEBUG  ] [Resource    ] add <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\data\fonts> in path list
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\data\images\defaulttheme.atlas>
[DEBUG  ] [Atlas       ] Need to load 1 images
[DEBUG  ] [Atlas       ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\data\images\defaulttheme-0.png>
[DEBUG  ] [ImageSDL2   ] Load <C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\data\images\defaulttheme-0.png>
 Traceback (most recent call last):
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:\Users\Allerter\Desktop\Python\app\info\playground.py", line 24, in <module>
     app = Test()
   File "C:\Users\Allerter\Desktop\Python\app\info\playground.py", line 18, in __init__
     self.screen.add_widget(MDTextField())
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\uix\textfield.py", line 865, in __init__
     super().__init__(**kwargs)
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivymd\theming.py", line 903, in __init__
     super().__init__(**kwargs)
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\uix\textinput.py", line 528, in __init__
     super(TextInput, self).__init__(**kwargs)
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\uix\behaviors\focus.py", line 367, in __init__
     super(FocusBehavior, self).__init__(**kwargs)
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\lang\builder.py", line 596, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\lang\builder.py", line 929, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 12:
 ...
      10:        # Disabled line.
      11:        Color:
 >>   12:            rgba: self.line_color_normal if root.mode == "line" else (0, 0, 0, 0)
      13:        Line:
      14:            points: self.x, self.y + dp(16), self.x + self.width, self.y + dp(16)
 ...
 TypeError: 'NoneType' object is not iterable
   File "C:\Users\Allerter\Desktop\Python\mrs_env\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
```

</p>
</details>

### Versions

* OS: Windows 7 64-bit
* Python: 3.8.6
* Kivy: 2.0.0
* KivyMD: Master branch (commit a9da44b8714cd794c782ed5027c7db295c3a57cf)

**Comment by oluwajomilojufamadewa** [comment]
Good day
Please I am getting exactly the same error too but I used 'pip install kivymd' to install kivymd.
Can you please help me.
Thank you in advance.
