### ISSUE TITLE
MDTabsLabel.color has an invalid format (got [])

### ISSUE THREAD

**Issue by Christofon** [kivymd/KivyMD#753]
### Description of the Bug

Trying to implement tabs, getting this error even with the example code.

### Code

```python
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.font_definitions import fonts
from kivymd.icon_definitions import md_icons

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
'''


class Tab(FloatLayout, MDTabsBase):
    pass


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        for name_tab in list(md_icons.keys())[15:30]:
            self.root.ids.tabs.add_widget(
                Tab(
                    text=f"[size=20][font={fonts[-1]['fn_regular']}]{md_icons[name_tab]}[/size][/font] {name_tab}"
                )
            )


Example().run()
```

### Logs

```
Traceback (most recent call last):
   File "/Users/christopherkremsner/Documents/Coding/test.py", line 38, in <module>
     Example().run()
   File "/usr/local/lib/python3.9/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/usr/local/lib/python3.9/site-packages/kivy/app.py", line 944, in _run_prepare
     self.dispatch('on_start')
   File "_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/christopherkremsner/Documents/Coding/test.py", line 32, in on_start
     Tab(
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivymd/uix/tab.py", line 374, in __init__
     self.tab_label = MDTabsLabel(tab=self)
   File "/usr/local/lib/python3.9/site-packages/kivymd/uix/tab.py", line 328, in __init__
     super().__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/behaviors/togglebutton.py", line 84, in __init__
     super(ToggleButtonBehavior, self).__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/label.py", line 318, in __init__
     super(Label, self).__init__(**kwargs)
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/usr/local/lib/python3.9/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/usr/local/lib/python3.9/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/usr/local/lib/python3.9/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 19:
 ...
      17:        )
      18:    color:
 >>   19:        self.text_color_active if self.state == 'down'         else self.text_color_normal
      20:    on_x: self._trigger_update_tab_indicator()
      21:    on_width: self._trigger_update_tab_indicator()
 ...
 ValueError: MDTabsLabel.color has an invalid format (got [])
   File "/usr/local/lib/python3.9/site-packages/kivy/lang/builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "properties.pyx", line 498, in kivy.properties.Property.__set__
   File "properties.pyx", line 527, in kivy.properties.Property.set
   File "properties.pyx", line 2025, in kivy.properties.ColorProperty.convert
```

### Versions

* OS: macOS 10.15.7
* Python: 3.9.0
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Christofon Use KivyMD library from master branch.

**Comment by KR0SIV** [comment]
I'm very much confused here, I'm also using KivyMD: 0.104.1
How am I not using the Master branch?

I have the exact same issue.

**Comment by HeaTTheatR** [comment]
@KR0SIV A master branch is a branch that is located on `GitHub`, not in `PyPi`.

**Comment by KR0SIV** [comment]
@HeaTTheatR Thank you, sorry for my ignorance.

If anyone else runs into this problem and doesn't know what do you, here you go:

    pip install git+https://github.com/kivymd/KivyMD@master

**Comment by nidia95** [comment]
I've got this Error when I wanted to set a property as ListProperty to change my UI color. when I sat a default variable for it, the error disappeared. for examle:

`color = ListProperty([0, 0, 0, 1])`
