### ISSUE TITLE
selectioncontrol TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sysnux** [kivymd/KivyMD#758]
### Description of the Bug

When running kitchen_sink demo, clicking on "Selection controls"  yields to a crash.

### Code and Logs

[INFO   ] [KivyMD      ] 0.104.2.dev0 (installed at "/home/jdg/Téléchargements/KivyMD/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "demos/kitchen_sink/main.py", line 124, in <module>
     KitchenSinkApp().run()
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/home/jdg/Téléchargements/KivyMD/kivymd/uix/list.py", line 854, in on_touch_up
     super().on_touch_up(touch)
   File "/home/jdg/Téléchargements/KivyMD/kivymd/uix/behaviors/ripple_behavior.py", line 296, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "demos/kitchen_sink/main.py", line 76, in <lambda>
     "on_release": lambda x=name_item_example: self.set_example_screen(
   File "demos/kitchen_sink/main.py", line 93, in set_example_screen
     screen_object = eval(self.data_screens[name_screen]["Factory"])
   File "<string>", line 1, in <module>
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/jdg/Téléchargements/KivyMD/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 139, in __init__
     super().__init__(**kwargs)
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 596, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 929, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 32:
 ...
      30:        Color:
      31:            rgba:
 >>   32:                self._track_color_disabled if self.disabled else                (self._track_color_active if self.active                else self._track_color_normal)
      33:        RoundedRectangle:
      34:            size: self.width - dp(8), dp(16)
 ...
 TypeError: 'NoneType' object is not iterable
   File "/home/jdg/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__

### Versions

* OS: Fedora-32 x86_64
* Python: Python 3.8.6
* Kivy: v2.0.0rc4
* KivyMD: git a9da44b8714cd794c782ed5027c7db295c3a57cf

Following patch does solve the issue:
```
[jdg@tiare KivyMD]$ git diff
diff --git a/kivymd/uix/selectioncontrol.py b/kivymd/uix/selectioncontrol.py
index 543e2a8..bc394a0 100755
--- a/kivymd/uix/selectioncontrol.py
+++ b/kivymd/uix/selectioncontrol.py
@@ -513,9 +513,9 @@ class MDSwitch(ThemableBehavior, ButtonBehavior, FloatLayout):
     and defaults to `Primary`.
     """
 
-    _track_color_active = ColorProperty(None)
-    _track_color_normal = ColorProperty(None)
-    _track_color_disabled = ColorProperty(None)
+    _track_color_active = ColorProperty()
+    _track_color_normal = ColorProperty()
+    _track_color_disabled = ColorProperty()
     _thumb_pos = ListProperty([0, 0])
 
     def __init__(self, **kwargs):
```

Not sure this is the right thing to do...

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD/commit/15e21769c32ed00df96570d45c90e0d7971e7f49
