### ISSUE TITLE
MDSwitch TypeError: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by nvollstedt** [kivymd/KivyMD#771]
### Description of the Bug

MDSwitch leads to the application crashing. Same error happens when executing the demo KitchenSink and going to Selection controls.

### Code and Logs
Taken from https://kivymd.readthedocs.io/en/latest/components/selection-controls/

```
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
FloatLayout:

    MDSwitch:
        pos_hint: {'center_x': .5, 'center_y': .5}
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

```
~$ python /home/App/main.py
[INFO   ] [Logger      ] Record log in /home/.kivy/logs/kivy_21-01-13_43.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/home/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-01-04 (installed at "/home/lib/python3.8/site-packages/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 20.2.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics (ILK)'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/App/sample/main.py", line 25, in <module>
     Test().run()
   File "/home/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/App/sample/main.py", line 22, in build
     return Builder.load_string(KV)
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 408, in load_string
     self._apply_rule(
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 596, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 929, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 32:
 ...
      30:        Color:
      31:            rgba:
 >>   32:                self._track_color_disabled if self.disabled else
                (self._track_color_active if self.active                else self._track_color_normal)
      33:        RoundedRectangle:
      34:            size: self.width - dp(8), dp(16)
 ...
 TypeError: 'NoneType' object is not iterable
   File "/home/lib/python3.8/site-packages/kivy/lang/builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy/graphics/context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 


```

### Versions

* OS: Ubuntu 20.04 64 Bit
* Python: 3.8.5
* Kivy: 2.0.0
* KivyMD: master 0.104.2.dev0

PS: Thanks for the great work, I am loving KivyMD.

**Comment by HeaTTheatR** [comment]
Use KivyMD library from master branch.
