### ISSUE TITLE
MDDataTable doesn't work

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivymd/KivyMD#795]
### Description of the Bug

Code is from documentation.

It can't work with pip install https://github.com/kivymd/KivyMD/archive/3274d62.zip
NOT with pip install kivymd==0.104.1

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""

from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("No.", dp(30)),
                ("Status", dp(30)),
                ("Signal Name", dp(60), self.sort_on_signal),
                ("Severity", dp(30)),
                ("Stage", dp(30)),
                ("Schedule", dp(30), self.sort_on_schedule),
                ("Team Lead", dp(30), self.sort_on_team)
            ],
            row_data=[
                ("1", ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                 "Astrid: NE shared managed", "Medium", "Triaged", "0:33",
                 "Chase Nguyen"),
                ("2", ("alert-circle", [1, 0, 0, 1], "Offline"),
                 "Cosmo: prod shared ares", "Huge", "Triaged", "0:39",
                 "Brie Furman"),
                ("3", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Phoenix: prod shared lyra-lists", "Minor",
                 "Not Triaged", "3:12", "Jeremy lake"),
                ("4", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: NW prod shared locations",
                 "Negligible",
                 "Triaged", "13:18", "Angelica Howards"),
                ("5", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: prod independent account",
                 "Negligible",
                 "Triaged", "22:06", "Diane Okuma"),

            ],
            sorted_on="Schedule",
            sorted_order="ASC",
            elevation=2
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        layout.add_widget(self.data_tables)
        return layout

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    def sort_on_signal(self, data):
        return sorted(data, key=lambda l: l[2])

    def sort_on_schedule(self, data):
        return sorted(data, key=lambda l: sum([int(l[-2].split(":")[0])*60, int(l[-2].split(":")[1])]))

    def sort_on_team(self, data):
        return sorted(data, key=lambda l: l[-1])

Example().run()

```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
@shpaginoleg7755 
Please describe your question in one message, attach a minimal code that may be run without additional manipulations, so developers can look at the working script and fix it. Also write what you expect from the script and what happened wrong. If needed, attach links or screenshots to explain us what you want to do.

**Comment by JWCook** [comment]
I stumbled across this because I had the same issue. The example above is [the one from the docs](https://kivymd.readthedocs.io/en/latest/components/datatables/). I just tested this with the current master branch, and it appears that this has been fixed already.

As of the latest stable release (kivymd `0.104.1`), however, the example fails with the following traceback:
```python
Traceback (most recent call last):
  File "data_table_example.py", line 82, in <module>
    Example().run()
  File "site-packages\kivy\app.py", line 949, in run
    self._run_prepare()
  File "site-packages\kivy\app.py", line 919, in _run_prepare
    root = self.build()
  File "data_table_example.py", line 15, in build
    self.data_tables = MDDataTable(
  File "site-packages\kivymd\uix\datatables.py", line 923, in __init__
    super().__init__(**kwargs)
  File "site-packages\kivymd\theming.py", line 907, in __init__
    super().__init__(**kwargs)
  File "site-packages\kivy\uix\modalview.py", line 187, in __init__
    super(ModalView, self).__init__(**kwargs)
  File "site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
    super(AnchorLayout, self).__init__(**kwargs)
  File "site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "site-packages\kivy\uix\widget.py", line 350, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy\_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

So for anyone else who encounters this, either install the development version, or wait for `0.104.2`.
