### ISSUE TITLE
MDtataTables - get_visible_view bug?

### ISSUE THREAD

**Issue by podraco** [kivymd/KivyMD#801]
### Description of the Bug
There is a problem when sorting data on the screen, as far i tested the source code, this is derived from the fragment:
```py
def select_all(self, state):
....
else:
                cell_row_obj = (
                    cell_row_obj
                ) = self.view_adapter.get_visible_view(i)
....

```

When scrolling horizontally on the screen, the elements are no longer selectable. 
This happens after hiding the first column.
As long as the first column remains visible, the table is selectable by `get_visible_view`.
If the first column is hidden, `get_visible_view` will return None.

### Code and Logs
platform Windows 10 - 1909.
#### LOG
-------------------------
```python
[select_all] else something
cell_row_obj = None
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File ".\test2.py", line 502, in <module>
     Example().run()
   File "~user~\venv\kivy20\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "~user~\venv\kivy20\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "~user~\venv\kivy20\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "~user~\venv\kivy20\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "~user~\venv\kivy20\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "~user~\venv\kivy20\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "~user~\venv\kivy20\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 296, in on_touch_up
     return super().on_touch_up(touch)
   File "~user~\venv\kivy20\lib\site-packages\kivymd\uix\button.py", line 902, in on_touch_up
     return super().on_touch_up(touch)
   File "~user~\venv\kivy20\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "~user~\venv\kivy20\lib\site-packages\kivymd\uix\datatables.py", line 567, in _sort_release
     self.table_data.select_all("normal")
   File "~user~\venv\kivy20\lib\site-packages\kivymd\uix\datatables.py", line 791, in select_all
     self.on_mouse_select(cell_row_obj)
   File "~user~\venv\kivy20\lib\site-packages\kivymd\uix\datatables.py", line 882, in on_mouse_select
     if self.ids.row_controller.selected_row != instance.index:
 AttributeError: 'NoneType' object has no attribute 'index'
(kivy20) PS ~user~\source>
```
-------------------------

Code Example:
```py
from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("UMID", dp(30), self.sort_on_UMID),
                ("Fecha", dp(40), self.sort_on_date),
                ("Nombre", dp(80), self.sort_on_name),
                ("Resumen", dp(120)),
                ("Direccion", dp(40), self.sort_on_dir),
                ("Autor", dp(30), self.sort_on_autor),
                ("Editores", dp(30)),
            ],
            row_data=[
                ("1", ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                 "Astrid: NE shared managed", "Medium", "Triaged", "0:33",
                 "Chase Nguyen"),
                ("2", ("alert-circle", [1, 0, 0, 1], "Offline"),
                 "Cosmo: prod shared ares", "Huge", "Triaged", "0:39",
                 "Brie Furman"),
                ("3", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Phoenix: prod shared lyra-lists", "Minor",
                 "Not Triaged", "3:12", "Jeremy lake"),
                ("4", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: NW prod shared locations",
                 "Negligible",
                 "Triaged", "13:18", "Angelica Howards"),
                ("5", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: prod independent account",
                 "Negligible",
                 "Triaged", "22:06", "Diane Okuma"),

            ],
            sorted_on="Schedule",
            sorted_order="ASC",
            elevation=2
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        layout.add_widget(self.data_tables)
        return layout

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    def sort_on_UMID(self, data):
        return sorted(data, key=lambda l: l[0])

    #
    def sort_on_date(self, data):
        return sorted(data, key=lambda l: l[1])

    #
    def sort_on_name(self, data):
        return sorted(data, key=lambda l: l[2])

    #
    def sort_on_dir(self, data):
        return sorted(data, key=lambda l: l[4])

    #
    def sort_on_autor(self, data):
        return sorted(data, key=lambda l: l[5])

Example().run()

```
-------------------------
### Screenshots

![8trKCRj5wv](https://user-images.githubusercontent.com/5509325/106405577-4e35f700-63fc-11eb-8f4b-b99d0494d96f.gif)
here's an example.

### Versions

* OS: Windows 10 - 1909
* Python:  3.7
* Kivy: 2.0
* KivyMD:  master

**Comment by HeaTTheatR** [comment]
Please attach example code...

**Comment by podraco** [comment]
code updated

**Comment by HeaTTheatR** [comment]
@podraco I'll deal with this issue later ...

**Comment by kabcasa** [comment]
@HeaTTheatR
hi , any idea i always face this issue when i use MDDataTable
i have take this code example but on  other  same error :

 Traceback (most recent call last):
   File "tab6.py", line 88, in <module>
     Example().run()
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "tab6.py", line 52, in build
     elevation=2
   File "/home/pi/.local/lib/python3.7/site-packages/kivymd/uix/datatables.py", line 923, in __init__
     super().__init__(**kwargs)
   File "/home/pi/.local/lib/python3.7/site-packages/kivymd/theming.py", line 907, in __init__
     super().__init__(**kwargs)
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/uix/modalview.py", line 187, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/pi/.local/lib/python3.7/site-packages/kivy/uix/widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)

 TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by HeaTTheatR** [comment]
@kabcasa Nobody has dealt with this issue yet ...

**Comment by kevin-schumann** [comment]
@HeaTTheatR 

This bug seems to fixed since my pull request yesterday.

```python
from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("No.", dp(30)),
                ("Status", dp(30)),
                ("Signal Name", dp(60), self.sort_on_signal),
                ("Severity", dp(30)),
                ("Stage", dp(30)),
                ("Schedule", dp(30)),
                ("Team Lead", dp(30))
            ],
            row_data=[
                (1,) * 7,
                (2,) * 7,
                (3,) * 7,
                (4,) * 7,
                (5,) * 7,
                (6,) * 7,
                (7,) * 7,
                (8,) * 7,
                (9,) * 7,

            ],
            sorted_on="Schedule",
            sorted_order="ASC",
            elevation=2
        )

        self.data_tables.bind(on_check_press=self.on_check_press)
        layout.add_widget(self.data_tables)
        return layout

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    def sort_on_signal(self, data):
        ''' 
        Returns a
             - Tuple of indices (the permutation to sort the data in ascending order)
             - Tuple of the ascending ordered data
        '''
        return zip(*sorted(enumerate(data), key=lambda l: int(l[1][3])))

Example().run()
```

**Comment by HeaTTheatR** [comment]
@podraco 
This problem needs to be updated, because the first time you click on the sort icon, the application crashes with an error:

```python
   File "kivymd/uix/datatables.py", line 583, in _sort_release
     indices, sorted_data = self.sort_action(self.table_data.row_data)
 ValueError: too many values to unpack (expected 2)
```

**Comment by kevin-schumann** [comment]
@HeaTTheatR  I've updated the code it goes as follows:

```python
from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            size_hint=(0.7, 0.6),
            use_pagination=True,
            check=True,
            column_data=[
                ("UMID", dp(30), self.sort_on_UMID),
                ("Fecha", dp(40), self.sort_on_date),
                ("Nombre", dp(80), self.sort_on_name),
                ("Resumen", dp(120)),
                ("Direccion", dp(40), self.sort_on_dir),
                ("Autor", dp(30), self.sort_on_autor),
                ("Editores", dp(30)),
            ],
            row_data=[
                ("1", ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                 "Astrid: NE shared managed", "Medium", "Triaged", "0:33",
                 "Chase Nguyen"),
                ("2", ("alert-circle", [1, 0, 0, 1], "Offline"),
                 "Cosmo: prod shared ares", "Huge", "Triaged", "0:39",
                 "Brie Furman"),
                ("3", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Phoenix: prod shared lyra-lists", "Minor",
                 "Not Triaged", "3:12", "Jeremy lake"),
                ("4", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: NW prod shared locations",
                 "Negligible",
                 "Triaged", "13:18", "Angelica Howards"),
                ("5", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: prod independent account",
                 "Negligible",
                 "Triaged", "22:06", "Diane Okuma"),

            ],
            sorted_on="Schedule",
            sorted_order="ASC",
            elevation=2
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        layout.add_widget(self.data_tables)
        return layout

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    def sort_on_UMID(self, data):
        return zip(*sorted(enumerate(data), key=lambda l: l[1][0]))

    #
    def sort_on_date(self, data):
        return zip(*sorted(enumerate(data), key=lambda l: l[1][1]))

    #
    def sort_on_name(self, data):
        return zip(*sorted(enumerate(data), key=lambda l: l[1][2]))

    #
    def sort_on_dir(self, data):
        return zip(*sorted(enumerate(data), key=lambda l: l[1][4]))

    #
    def sort_on_autor(self, data):
        return zip(*sorted(enumerate(data), key=lambda l: l[1][5]))

Example().run()
```

**Comment by kevin-schumann** [comment]
@HeaTTheatR This issue can be closed as this bug doesn't occur anymore. See the code I provided previously.
