### ISSUE TITLE
Unknown class <MDNavigationLayout>

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivymd/KivyMD#802]
### Description of the Bug

I have created a new project and have install kivy and kivymd by run these commands:
pip install kivy
pip install kivymd

But then I run my code - it finished with the error:  kivy.factory.FactoryException: Unknown class <MDNavigationLayout>

How to fix it? Thanks!!!

Log:
```
(venv) C:\Users\user123\PycharmProjects\test_22>pip install kivy
Collecting kivy
  Using cached Kivy-2.0.0-cp39-cp39-win_amd64.whl (4.1 MB)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting kivy-deps.glew~=0.3.0
  Using cached kivy_deps.glew-0.3.0-cp39-cp39-win_amd64.whl (123 kB)
Collecting kivy-deps.angle~=0.3.0
  Using cached kivy_deps.angle-0.3.0-cp39-cp39-win_amd64.whl (4.7 MB)
Collecting kivy-deps.sdl2~=0.3.1
  Using cached kivy_deps.sdl2-0.3.1-cp39-cp39-win_amd64.whl (2.5 MB)
Collecting docutils
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting Kivy-Garden>=0.1.4
  Using cached kivy-garden-0.1.4.tar.gz (6.8 kB)
Collecting pygments
  Using cached Pygments-2.7.4-py3-none-any.whl (950 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pywin32>=223
  Using cached pywin32-300-cp39-cp39-win_amd64.whl (9.2 MB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
     |████████████████████████████████| 137 kB 2.2 MB/s
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Using legacy 'setup.py install' for Kivy-Garden, since package 'wheel' is not installed.
Installing collected packages: urllib3, idna, chardet, certifi, requests, pywin32, pypiwin32, pygments, Kivy-Garden, kivy-deps.sdl2, kivy-deps.glew, kivy-d
eps.angle, docutils, kivy
    Running setup.py install for Kivy-Garden ... done
Successfully installed Kivy-Garden-0.1.4 certifi-2020.12.5 chardet-4.0.0 docutils-0.16 idna-2.10 kivy-2.0.0 kivy-deps.angle-0.3.0 kivy-deps.glew-0.3.0 kivy
-deps.sdl2-0.3.1 pygments-2.7.4 pypiwin32-223 pywin32-300 requests-2.25.1 urllib3-1.26.3

(venv) C:\Users\user123\PycharmProjects\test_22>pip install kivymd
Collecting kivymd
  Using cached kivymd-0.104.1-py3-none-any.whl (2.4 MB)
Collecting pillow
  Using cached Pillow-8.1.0-cp39-cp39-win_amd64.whl (2.2 MB)
Requirement already satisfied: kivy in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivymd) (2.0.0)
Requirement already satisfied: requests in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivymd) (2.25.1)
Requirement already satisfied: kivy-deps.glew~=0.3.0 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (0.3.0)
Requirement already satisfied: kivy-deps.sdl2~=0.3.1 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (0.3.1)
Requirement already satisfied: Kivy-Garden>=0.1.4 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (0.1.4)
Requirement already satisfied: docutils in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (0.16)
Requirement already satisfied: kivy-deps.angle~=0.3.0 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (0.3.0)
Requirement already satisfied: pypiwin32 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (223)
Requirement already satisfied: pygments in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from kivy->kivymd) (2.7.4)
Requirement already satisfied: pywin32>=223 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from pypiwin32->kivy->kivymd) (300)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from requests->kivymd) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from requests->kivymd) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from requests->kivymd) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user123\pycharmprojects\test_22\venv\lib\site-packages (from requests->kivymd) (2020.12.5)
Installing collected packages: pillow, kivymd
Successfully installed kivymd-0.104.1 pillow-8.1.0

(venv) C:\Users\user123\PycharmProjects\test_22>

```

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

from kivy.uix.floatlayout import FloatLayout
from kivymd.uix.tab import MDTabsBase

KV = '''
#https://stackoverflow.com/questions/65698145/kivymd-tab-name-containing-icons-and-text
# this import will prevent disappear tabs through some clicks on them)))
#:import md_icons kivymd.icon_definitions.md_icons
#:import fonts kivymd.font_definitions.fonts

Screen:

    MDNavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDTabs:
                        id: tabs                     
                        height: "48dp"
                        tab_indicator_anim: False

                        Tab:
                            id: tab1
                            name: 'tab1'
                            text: f"[size=20][font={fonts[-1]['fn_regular']}]{md_icons['star']}[/size][/font] Star"

                            BoxLayout:
                                orientation: 'vertical'
                                padding: "10dp"   

                                BoxLayout:
                                    orientation: 'horizontal'                               

                                    MDIconButton:
                                        icon: "calendar"

                                    MDTextField:
                                        id: start_date
                                        hint_text: "Date"
                                        text: "Why this text grey? I want blue text here!!! (with no Focus)"                                      
                                        text_hint_color:[0,0,1,1]                                     

                                BoxLayout:
                                    orientation: 'horizontal'                         

                                    MDIconButton:
                                        icon: "cash"

                                    MDTextField:
                                        id: test
                                        hint_text: "test"
                                        text: "Why this text grey? I want blue text here!!!"
                                        text_hint_color:[0,0,1,1]
                        Tab:
                            id: tab2
                            name: 'tab2'
                            text: f"[size=20][font={fonts[-1]['fn_regular']}]{md_icons['star']}[/size][/font] Star 2"

                            BoxLayout:
                                orientation: 'vertical'
                                padding: "10dp"   

                                BoxLayout:
                                    orientation: 'horizontal'                               

                                    MDIconButton:
                                        icon: "calendar"

                                    MDTextField:
                                        id: start_date2
                                        hint_text: "Date"                                      

                                BoxLayout:
                                    orientation: 'horizontal'                         

                                    MDIconButton:
                                        icon: "cash"

                                    MDTextField:
                                        id: test2
                                        hint_text: "test2"

                        Tab:
                            id: tab3
                            name: 'tab3'
                            text: f"[size=20][font={fonts[-1]['fn_regular']}]{md_icons['star']}[/size][/font] Star3"

                            BoxLayout:
                                orientation: 'vertical'
                                padding: "10dp"   

                                BoxLayout:
                                    orientation: 'horizontal'                               

                                    MDIconButton:
                                        icon: "calendar"

                                    MDTextField:
                                        id: start_date3
                                        hint_text: "Date"                                      

                                BoxLayout:
                                    orientation: 'horizontal'                         

                                    MDIconButton:
                                        icon: "cash"

                                    MDTextField:
                                        id: test3
                                        hint_text: "test3"



'''


class Tab(FloatLayout, MDTabsBase):
    '''Class implementing content for a tab.'''


class TestApp(MDApp):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)

    def build(self):
        self.theme_cls.theme_style = "Light"  # "Dark"  # "Light"
        # return Builder.load_string(KV)
        return self.screen

    def on_start(self):
        pass

    def on_tab_switch(self, instance_tabs, instance_tab, instance_tabs_label, tab_text):
        pass


TestApp().run()
```

Here is the error:
```
C:\Users\user123\PycharmProjects\test_22\venv\Scripts\python.exe C:/Users/user123/PycharmProjects/test_22/main.py
[INFO   ] [Logger      ] Record log in C:\Users\user123\.kivy\logs\kivy_21-02-01_30.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\user123\PycharmProjects\test_22\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\user123\PycharmProjects\test_22\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 457.30'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1070/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:\Users\user123\PycharmProjects\test_22\main.py", line 147, in <module>
     TestApp().run()
   File "C:\Users\user123\PycharmProjects\test_22\main.py", line 133, in __init__
     self.screen = Builder.load_string(KV)
   File "C:\Users\user123\PycharmProjects\test_22\venv\lib\site-packages\kivy\lang\builder.py", line 408, in load_string
     self._apply_rule(
   File "C:\Users\user123\PycharmProjects\test_22\venv\lib\site-packages\kivy\lang\builder.py", line 621, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\user123\PycharmProjects\test_22\venv\lib\site-packages\kivy\factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <MDNavigationLayout>

Process finished with exit code 1
```

### Versions

* OS: Windows 10
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
The `MDNavigationLayout` class is only available in the master branch of the library.
