### ISSUE TITLE
 kivy.factory.FactoryException: Unknown class <NavigationLayout>

### ISSUE THREAD

**Issue by romybompart** [kivymd/KivyMD#806]
### Description of the Bug

Hi Guys I am running the kitchen_sink demo, I am trying to see the Navigationdrawer example, but I have the an error: 

     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <NavigationLayout>

### Code and Logs

[INFO   ] [Logger      ] Record log in C:\Users\Romy1\.kivy\logs\kivy_21-02-03_5.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "c:\Users\Romy1\Anaconda3\envs\kivy_env\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 24.20.100.6286'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 24.20.100.6286'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-01-23 (installed at "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Romy1\Documents\Documentos Romy\Proyectos Personales\kivyMD\KivyMD\demos\kitchen_sink\main.py", line 143, in <module>
     KitchenSinkApp().run()
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd\uix\list.py", line 854, in on_touch_up
     super().on_touch_up(touch)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd\uix\behaviors\ripple_behavior.py", line 296, in on_touch_up
     return super().on_touch_up(touch)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Romy1\Documents\Documentos Romy\Proyectos Personales\kivyMD\KivyMD\demos\kitchen_sink\main.py", line 86, in <lambda>
     x
   File "C:\Users\Romy1\Documents\Documentos Romy\Proyectos Personales\kivyMD\KivyMD\demos\kitchen_sink\main.py", line 107, in set_example_screen
     screen_object = eval(self.data_screens[name_screen]["Factory"])
   File "<string>", line 1, in <module>
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
     rule_children=rule_children)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\uix\widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\lang\builder.py", line 543, in apply
     rule_children=rule_children)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\lang\builder.py", line 621, in _apply_rule
     cls = Factory_get(cname)
   File "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <NavigationLayout>
[Finished in 7.3s]

### Versions

* OS:  Microsoft Windows [Version 10.0.19041.746]
* Python: 3.7.7
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by romybompart** [comment]
I found in another issue this problem and the solution was to use MDNavigationLayout instead. 
But the documentation and the examples states: 


https://github.com/kivymd/KivyMD/wiki/Components-Navigation-Drawer
![image](https://user-images.githubusercontent.com/8228572/106804868-9129e180-662b-11eb-8b16-47112bfa4519.png)

Best Regards

**Comment by HeaTTheatR** [comment]
@romybompart Yes, no one has edited the `Wiki` section for a long time. I advise you to use the documentation from the `readthedocs`.

**Comment by romybompart** [comment]
Thank you @HeaTTheatR 

I can see the difference:
https://kivymd.readthedocs.io/en/latest/components/navigation-drawer/

Best Regards
