### ISSUE TITLE
MDDatePicker example from the documentation crash.

### ISSUE THREAD

**Issue by Avekia** [kivymd/KivyMD#825]
### Description of the Bug
The application crash when I just copy/paste the example from the page [https://kivymd.readthedocs.io/en/latest/components/pickers/index.html#mddatepicker](url)

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.picker import MDDatePicker

KV = '''
MDFloatLayout:

    MDToolbar:
        title: "MDDatePicker"
        pos_hint: {"top": 1}
        elevation: 10

    MDRaisedButton:
        text: "Open time picker"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_date_picker()
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_save(self, instance, value, date_range):
        '''
        Events called when the "OK" dialog box button is clicked.

        :type instance: <kivymd.uix.picker.MDDatePicker object>;

        :param value: selected date;
        :type value: <class 'datetime.date'>;

        :param date_range: list of 'datetime.date' objects in the selected range;
        :type date_range: <class 'list'>;
        '''

        print(instance, value, date_range)

    def on_cancel(self, instance, value):
        '''Events called when the "CANCEL" dialog box button is clicked.'''

    def show_date_picker(self):
        date_dialog = MDDatePicker()
        date_dialog.bind(on_save=self.on_save, on_cancel=self.on_cancel)
        date_dialog.open()


Test().run()
```

```
D:\Documents\Python_projects\Test_kivy\venv\Scripts\python.exe D:/Documents/Startup/Vinci_micro_devis/main.py
[INFO   ] [Logger      ] Record log in C:\Users\aymer\.kivy\logs\kivy_21-02-09_35.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\Documents\Python_projects\Test_kivy\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 23.20.16.4973'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 23.20.16.4973'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "D:/Documents/Startup/Vinci_micro_devis/main.py", line 54, in <module>
     Test().run()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivymd\uix\button.py", line 1083, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "C:\Users\aymer\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 12, in <module>
   File "D:/Documents/Startup/Vinci_micro_devis/main.py", line 49, in show_date_picker
     date_dialog = MDDatePicker()
 TypeError: __init__() missing 1 required positional argument: 'callback'

Process finished with exit code 1

```

### Versions

* OS: Windows 10
* Python:  3.7
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@AvekIA The api that you are using is intended for `KivyMD` version `0.104.2`, and you are using KivyMD version `0.104.1`.
