### ISSUE TITLE
MDSwiper remove_widget issue

### ISSUE THREAD

**Issue by fedor360139** [kivymd/KivyMD#860]
### Description of the Bug

First issue:
swiper.children doesn't work for swiper.

### First issue

```python
from kivy.lang import Builder
from kivymd.app import MDApp

from kivy.clock import Clock
from functools import partial

KV = '''
<MySwiper@MDSwiperItem>

    FitImage:
        source: "logo"
        radius: [20,]

MDScreen:

    MDToolbar:
        id: toolbar
        title: "MDSwiper"
        elevation: 10
        pos_hint: {"top": 1}

    MDSwiper:
        id: swiper
        size_hint_y: None
        height: root.height - toolbar.height - dp(40)
        y: root.height - self.height - toolbar.height - dp(20)

        MySwiper:
            id: swiper_item_1

        MySwiper:
            id: swiper_item_2
'''


class MainApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def del_all(self, layout, _):
        for i in layout.children:
            print(i)  # => <kivymd.uix.boxlayout.MDBoxLayout object at 0x113cc95f8>
            #i.parent.remove_widget(i)

    def on_start(self):
        Clock.schedule_once(partial(self.del_all, self.root.ids.swiper), 5)


MainApp().run()
```
 ### Second issue
 When all swiper's items are deleted by id and i click on the area which contained these items early, i get error and app crashes

```python
from kivy.lang import Builder
from kivymd.app import MDApp

from kivy.clock import Clock
from functools import partial

KV = '''
<MySwiper@MDSwiperItem>

    FitImage:
        source: "logo"
        radius: [20,]

MDScreen:

    MDToolbar:
        id: toolbar
        title: "MDSwiper"
        elevation: 10
        pos_hint: {"top": 1}

    MDSwiper:
        id: swiper
        size_hint_y: None
        height: root.height - toolbar.height - dp(40)
        y: root.height - self.height - toolbar.height - dp(20)

        MySwiper:
            id: swiper_item_1

        MySwiper:
            id: swiper_item_2
'''


class MainApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def del_all(self, _):
        for i in [i for i, v in self.root.ids.items() if 'swiper_item' in i]:
            child_ = self.root.ids[i]
            self.root.ids.swiper.remove_widget(child_)

    def on_start(self):
        Clock.schedule_once(partial(self.del_all), 5) # i noted that partial can be removed here


MainApp().run()
``` 
Error
```
 Traceback (most recent call last):
   File "/Users/Imac/Downloads/dataset/wikiart/finman/icon.py", line 50, in <module>
     MainApp().run()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/base.py", line 248, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1416, in on_motion
     self.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1452, in on_touch_up
     if w.dispatch('on_touch_up', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/uix/relativelayout.py", line 313, in on_touch_up
     ret = super(RelativeLayout, self).on_touch_up(touch)
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivy/uix/widget.py", line 567, in on_touch_up
     if child.dispatch('on_touch_up', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivymd/uix/swiper.py", line 549, in on_touch_up
     self._reset_size()
   File "/Users/Imac/miniconda3/envs/python36env/lib/python3.6/site-packages/kivymd/uix/swiper.py", line 455, in _reset_size
     child = children[self._selected]
 IndexError: list index out of range
```
### Versions

* OS: mac os
* Python: 3.6
* Kivy: 2.0
* KivyMD: 2021-02-03

**Comment by quitegreensky** [comment]
@fedor360139 for your first issue you should use `get_items()` instead of children 
https://kivymd.readthedocs.io/en/latest/components/mdswiper/#kivymd.uix.swiper.MDSwiper.get_items
