### ISSUE TITLE
MDNavigationRail.visible is set to an invalid option True

### ISSUE THREAD

**Issue by dafri92** [kivymd/KivyMD#861]
### Description of the Bug

MDNavigationRail is not working as expected. It always crashes as soon as I hover over the Kivy window with the mouse.
I expect Kivy not crashing when hovering over with the mouse.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp


KV = '''
MDNavigationRail:
    MDNavigationRailItem:
        icon: "language-cpp"
        text: "C++"

    MDNavigationRailItem:
        icon: "language-python"
        text: "Python"

    MDNavigationRailItem:
        icon: "language-swift"
        text: "Swift"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

```
[INFO   ] [Logger      ] Record log in /Users/daniel/.kivy/logs/kivy_21-02-16_48.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.1 (default, Feb  3 2021, 07:38:02) 
[Clang 12.0.0 (clang-1200.0.32.29)]
[INFO   ] [Python      ] Interpreter at "/usr/local/opt/python@3.9/bin/python3.9"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-ffba10e, 2021-02-16 (installed at "/usr/local/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-16.1.11'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 6000'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/Users/daniel/Downloads/navrail.py", line 26, in <module>
     Test().run()
   File "/usr/local/lib/python3.9/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/usr/local/lib/python3.9/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/usr/local/lib/python3.9/site-packages/kivy/base.py", line 349, in mainloop
     self.window.mainloop()
   File "/usr/local/lib/python3.9/site-packages/kivy/core/window/window_sdl2.py", line 524, in mainloop
     x, y = self._fix_mouse_pos(x, y)
   File "/usr/local/lib/python3.9/site-packages/kivy/core/window/window_sdl2.py", line 473, in _fix_mouse_pos
     self.mouse_pos = (x * self._density,
   File "properties.pyx", line 498, in kivy.properties.Property.__set__
   File "properties.pyx", line 545, in kivy.properties.Property.set
   File "properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/usr/local/lib/python3.9/site-packages/kivymd/uix/behaviors/hover_behavior.py", line 186, in on_mouse_update
     self.visible = True
   File "properties.pyx", line 498, in kivy.properties.Property.__set__
   File "properties.pyx", line 542, in kivy.properties.Property.set
   File "properties.pyx", line 533, in kivy.properties.Property.set
   File "properties.pyx", line 1253, in kivy.properties.OptionProperty.check
 ValueError: MDNavigationRail.visible is set to an invalid option True. Must be one of: ['Selected', 'Persistent', 'Unlabeled']
```

### Versions

* OS: macOS 11.2.1
* Python: 3.9.1
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0 commit ffba10e

**Comment by dafri92** [comment]
So from the looks of it, #855 changed `HoverBehavior` and now uses https://github.com/kivymd/KivyMD/blob/ffba10e9457ed00a19aa1c72a3cb1cbca851d95d/kivymd/uix/behaviors/hover_behavior.py#L186. There is now a naming conflict because `MDNavigationRailItem` inherits from `HoverBehavior`.

**Comment by HeaTTheatR** [comment]
@Obrekr I cannot reproduce the error you are talking about. Can you record the screen?

**Comment by dafri92** [comment]
Sure, please see this video with KivyMD version 91be68f (before merging of pull request #855) which is working as expected:

https://user-images.githubusercontent.com/930308/108088236-871ad080-7078-11eb-9030-4869cba48920.mov

and KivyMD version ffba10e (current master) which crashes:

https://user-images.githubusercontent.com/930308/108088344-a31e7200-7078-11eb-98ac-275f1612d704.mov

**Comment by HeaTTheatR** [comment]
@Obrekr Try reinstalling KivyMD library from branch master ...

**Comment by dafri92** [comment]
I just did for the video, as far as I can see ffba10e is still HEAD of master.

**Comment by HeaTTheatR** [comment]
@Obrekr Try reinstalling the KivyMD library from the branch master with the latest changes ...

**Comment by dafri92** [comment]
Okay, I tried reinstalling again and recorded my screen for you. Maybe this is helpful. It's still broken for me.

https://user-images.githubusercontent.com/930308/108093028-93555c80-707d-11eb-9ebd-cc95035d5050.mp4

**Comment by dafri92** [comment]
@runette mind taking a look? I think this is related to your commits in #855. Maybe you can reproduce this issue?

**Comment by runette** [comment]
@Obrekr I think I know what the problem is. I can fix that.

**Comment by runette** [comment]
That PR should fix it.

**Comment by dafri92** [comment]
Thank you for your very fast response and fixing this issue. It now works as expected for me 👍
