### ISSUE TITLE
Date Picker Calender Numbers cannot be seen in Dark Mode

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#873]
### Description of the Bug

In Dark mode the numbers in the calendar are illegible

From the Kitchen Sink :

![Feb-18-2021 00-51-56](https://user-images.githubusercontent.com/2239795/108287924-8ae74980-7183-11eb-977c-9a2bfb60012e.gif)

NOTE - in real life the contrast between the numbers and the background was even less than that.

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by ayubk** [comment]
I found a bug when clicking the Open time picker button in the example code:

Traceback (most recent call last):
   File "ktest.py", line 49, in <module>
     Test().run()
   File "C:\py\kv\envk\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\py\kv\envk\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\py\kv\envk\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\py\kv\envk\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\py\kv\envk\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\py\kv\envk\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\py\kv\envk\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\py\kv\envk\lib\site-packages\kivymd\uix\button.py", line 1083, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\py\kv\envk\lib\site-packages\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\py\kv\envk\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\py\kv\envk\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 12, in <module>
   File "ktest.py", line 44, in show_date_picker
     date_dialog = MDDatePicker(mode="picker")
 TypeError: __init__() missing 1 required positional argument: 'callback'

---------------------------------
Thanks

**Comment by HeaTTheatR** [comment]
@ayubk Use dev version of KivyMD library.
