### ISSUE TITLE
It is not possible to use MDNavigationRailItem in python code 

### ISSUE THREAD

**Issue by bibibo-77** [kivymd/KivyMD#903]
Hello, I try to use MDNavigationRailItem in Python code = it means without KV language but it is not possible. A lot of errors appear. If i use the code without MDNavigationRailItem class everything works fine.

```python
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.toolbar import MDToolbar
from geocoder.api import elevation

class MyApp(MDApp):
    def build(self):
        boxlayout1 = MDBoxLayout(orientation = "vertical")
        toolbar = MDToolbar(title = "Hello")
        boxlayout1.add_widget(toolbar)
        boxlayout2 = MDBoxLayout()
        boxlayout1.add_widget(boxlayout2)
        
        from kivymd.uix.navigationrail import MDNavigationRail, MDNavigationRailItem
        navigationrail = MDNavigationRail()
        navigationrail.add_widget(MDNavigationRailItem())        
        boxlayout2.add_widget(navigationrail)
        
        return boxlayout1

root = MyApp()
root.run()

```

### Versions

* OS: macOS 11.2.2
* Python: 3.7.6
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by alex-conanec** [comment]
This code is not working for me. It return the following error:

 Traceback (most recent call last):
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 84, in <module>
 AttributeError: 'NoneType' object has no attribute 'visible'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 695, in _apply_rule
     value, bound = create_handler(
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 245, in create_handler
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 84:
 ...
      82:        theme_text_color: "Custom"
      83:        text_color:
 >>   84:            btn_icon.text_color             if root.navigation_rail.visible == "Persistent" else (0, 0, 0, 0)
      85:
      86:
 ...
 AttributeError: 'NoneType' object has no attribute 'visible'
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 84, in <module>
 
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/alex/Documents/data_science/farmusik/test4/main.py", line 24, in <module>
     root.run()
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/alex/Documents/data_science/farmusik/test4/main.py", line 18, in build
     navigationrail.add_widget(MDNavigationRailItem())        
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/uix/navigationrail.py", line 327, in __init__
     super().__init__(**kwargs)
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/theming.py", line 1140, in __init__
     super().__init__(**kwargs)
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/uix/behaviors/hover_behavior.py", line 140, in __init__
     super(HoverBehavior, self).__init__(**kwargs)
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 189, in __init__
     super().__init__(**kwargs)
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 147, in __init__
     super().__init__(**kwarg)
   File "/home/alex/Documents/data_science/farmusik/test4/kivymd/uix/behaviors/elevation.py", line 847, in __init__
     super().__init__(**kwargs)
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 84:
 ...
      82:        theme_text_color: "Custom"
      83:        text_color:
 >>   84:            btn_icon.text_color             if root.navigation_rail.visible == "Persistent" else (0, 0, 0, 0)
      85:
      86:
 ...
 BuilderException: Parser: File "<inline>", line 84:
 ...
      82:        theme_text_color: "Custom"
      83:        text_color:
 >>   84:            btn_icon.text_color             if root.navigation_rail.visible == "Persistent" else (0, 0, 0, 0)
      85:
      86:
 ...
 AttributeError: 'NoneType' object has no attribute 'visible'
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 84, in <module>
 
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 695, in _apply_rule
     value, bound = create_handler(
   File "/home/alex/miniconda3/envs/kivy/lib/python3.9/site-packages/kivy/lang/builder.py", line 245, in create_handler
     raise BuilderException(rule.ctx, rule.line,

Can you tell me why ? I also very interested in using MDNavigationRailItem dynamically !

**Comment by alex-conanec** [comment]
Try this
```
from kivymd.app import MDApp
from kivymd.uix.label import MDLabel
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.floatlayout import MDFloatLayout
from kivymd.uix.toolbar import MDToolbar
from kivy.utils import get_color_from_hex 

class MyApp(MDApp):
    def build(self):
        boxlayout1 = MDBoxLayout(orientation = "vertical")
        toolbar = MDToolbar(title = "Hello")
        boxlayout1.add_widget(toolbar)
        boxlayout2 = MDBoxLayout()
        boxlayout1.add_widget(boxlayout2)
        
        from kivymd.uix.navigationrail import MDNavigationRail, MDNavigationRailItem
        navigationrail = MDNavigationRail(
                md_bg_color = get_color_from_hex("#344954"),
                # color_normal = get_color_from_hex("#718089"), #crash the app when clicking on an item, don't understand why...
                color_active = get_color_from_hex("#f3ab44"),
                visible = "Persistent")
        for i in range(3):
            item = MDNavigationRailItem(navigation_rail = navigationrail, text="item%d" %(i+1))
            navigationrail.add_widget(item)        
        boxlayout2.add_widget(navigationrail)
        
        return boxlayout1

root = MyApp()
root.run()
```

**Comment by HeaTTheatR** [comment]
Fix in master branch.
