### ISSUE TITLE
MDDataTable Fails to Open

### ISSUE THREAD

**Issue by pademo57** [kivymd/KivyMD#912]
### Description of the Bug

MDDataTable fails to open. The main screen appears for a brief moment and then crashes.
Error appears to be line 113: orientation: "vertical"

### Code and Logs
# Test MDDataTables
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivy.uix.screenmanager import Screen
from kivy.metrics import dp

class MainApp(MDApp):
    def build(self):
        screen = Screen()
        table = MDDataTable(column_data=[("Test", dp(30))])

        screen.add_widget(table)
        return screen

MainApp().run()

"C:\kivy tutorial\KivyMD_DataTables\venv\Scripts\python.exe" "C:/kivy tutorial/KivyMD_DataTables/main.py"
[INFO   ] [Logger      ] Record log in C:\Users\padem\.kivy\logs\kivy_21-03-13_5.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\kivy tutorial\KivyMD_DataTables\venv\Scripts\python.exe"
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.13587 Compatibility Profile Context 19.40.54.01 26.20.14054.1001'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon(TM) Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\lang\builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1253, in kivy.properties.OptionProperty.check
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:\kivy tutorial\KivyMD_DataTables\main.py", line 17, in <module>
     MainApp().run()
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "C:\kivy tutorial\KivyMD_DataTables\main.py", line 11, in build
     table = MDDataTable(column_data=[("Food", dp(30))])
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivymd\uix\datatables.py", line 927, in __init__
     self.table_data = TableData(
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivymd\uix\datatables.py", line 488, in __init__
     super().__init__(**kwargs)
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\uix\recycleview\__init__.py", line 409, in __init__
     super(RecycleView, self).__init__(**kwargs)
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\uix\recycleview\__init__.py", line 201, in __init__
     super(RecycleViewBehavior, self).__init__(**kwargs)
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\uix\scrollview.py", line 539, in __init__
     super(ScrollView, self).__init__(**kwargs)
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 113:
 ...
     111:        height: self.minimum_height
     112:        width: self.minimum_width
 >>  113:        orientation: "vertical"
     114:        multiselect: True
     115:        touch_multiselect: True
 ...
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
   File "C:\kivy tutorial\KivyMD_DataTables\venv\lib\site-packages\kivy\lang\builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1253, in kivy.properties.OptionProperty.check

Process finished with exit code 1

### Versions

* OS: Windows 10
* Python: v3.9.0
* Kivy: V.2.0.0
* KivyMD: v0.104.1

**Comment by HeaTTheatR** [comment]
@pademo57 Use KivyMD library from master branch.
