### ISSUE TITLE
TapTargetView  crashing during close

### ISSUE THREAD

**Issue by Sahil-pixel** [kivymd/KivyMD#981]
### Description of the Bug

TapTargetView showing error when i am closing TapTargetView 

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.taptargetview import MDTapTargetView

KV = '''
Screen:

    MDFloatingActionButton:
        id: button
        icon: "plus"
        pos: 10, 10
        on_release: app.tap_target_start()
'''


class TapTargetViewDemo(MDApp):
    def build(self):
        screen = Builder.load_string(KV)
        self.tap_target_view = MDTapTargetView(
            widget=screen.ids.button,
            title_text="This is an add button",
            description_text="This is a description of the button",
            widget_position="left_bottom",
        )

        return screen

    def tap_target_start(self):
        if self.tap_target_view.state == "close":
            self.tap_target_view.start()
        else:
            self.tap_target_view.stop()


TapTargetViewDemo().run()

logs 
INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "m.py", line 36, in <module>
     TapTargetViewDemo().run() 
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/base.py", line 387, in idle
     Clock.tick()
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/animation.py", line 353, in _update
     self.stop(widget)
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/animation.py", line 218, in stop
     self.dispatch('on_complete', widget)
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "/home/sahil/.local/lib/python3.6/site-packages/kivymd/uix/taptargetview.py", line 614, in _after_stop
     args[0].stop_all(self.widget)
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/animation.py", line 180, in stop_all
     animation.stop(widget)
   File "/home/sahil/.local/lib/python3.6/site-packages/kivy/animation.py", line 218, in stop
     self.dispatch('on_complete', widget)
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "/home/sahil/.local/lib/python3.6/site-packages/kivymd/uix/taptargetview.py", line 618, in _after_stop
     self._fix_elev()
   File "/home/sahil/.local/lib/python3.6/site-packages/kivymd/uix/taptargetview.py", line 631, in _fix_elev
     size=self.widget._soft_shadow_size,
   File "kivy/weakproxy.pyx", line 32, in kivy.weakproxy.WeakProxy.__getattr__
 AttributeError: 'MDFloatingActionButton' object has no attribute '_soft_shadow_size'




```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: kubuntu 18.04
* Python: v 3.6.9
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by HeaTTheatR** [comment]
Update KivyMD library from master branch.
